// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x6DF8
			namespace CCSBot /*: public CS2::server::CBot*/ {
				constexpr std::ptrdiff_t m_eyePosition = 0x108; // GlobalTypes::VectorWS  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_name = 0x114; // char m_name[64]; |  0x114 | Schema_FixedArray | Size: 0x40
				constexpr std::ptrdiff_t m_combatRange = 0x154; // float32 m_combatRange; |  0x154 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_isRogue = 0x158; // bool m_isRogue; |  0x158 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_rogueTimer = 0x160; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_diedLastRound = 0x17c; // bool m_diedLastRound; |  0x17c | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_safeTime = 0x180; // float32 m_safeTime; |  0x180 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_wasSafe = 0x184; // bool m_wasSafe; |  0x184 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_blindFire = 0x18c; // bool m_blindFire; |  0x18c | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_surpriseTimer = 0x190; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_bAllowActive = 0x1a8; // bool m_bAllowActive; |  0x1a8 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_isFollowing = 0x1a9; // bool m_isFollowing; |  0x1a9 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_leader = 0x1ac; // GlobalTypes::CHandle<server::CCSPlayerPawn>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_followTimestamp = 0x1b0; // float32 m_followTimestamp; |  0x1b0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_allowAutoFollowTime = 0x1b4; // float32 m_allowAutoFollowTime; |  0x1b4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_hurryTimer = 0x1b8; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_alertTimer = 0x1d0; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_sneakTimer = 0x1e8; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_panicTimer = 0x200; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_stateTimestamp = 0x578; // float32 m_stateTimestamp; |  0x578 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_isAttacking = 0x57c; // bool m_isAttacking; |  0x57c | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_isOpeningDoor = 0x57d; // bool m_isOpeningDoor; |  0x57d | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_taskEntity = 0x584; // GlobalTypes::CHandle<server::CBaseEntity>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_goalPosition = 0x594; // GlobalTypes::VectorWS  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_goalEntity = 0x5a0; // GlobalTypes::CHandle<server::CBaseEntity>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_avoid = 0x5a4; // GlobalTypes::CHandle<server::CBaseEntity>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_avoidTimestamp = 0x5a8; // float32 m_avoidTimestamp; |  0x5a8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_isStopping = 0x5ac; // bool m_isStopping; |  0x5ac | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_hasVisitedEnemySpawn = 0x5ad; // bool m_hasVisitedEnemySpawn; |  0x5ad | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_stillTimer = 0x5b0; // server::IntervalTimer  | Schema_DeclaredClass | Size: 0x10
				constexpr std::ptrdiff_t m_bEyeAnglesUnderPathFinderControl = 0x5c0; // bool m_bEyeAnglesUnderPathFinderControl; |  0x5c0 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_pathIndex = 0x5ec0; // int32_t m_pathIndex; |  0x5ec0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_areaEnteredTimestamp = 0x5ec4; // entity2::GameTime_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_repathTimer = 0x5ec8; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_avoidFriendTimer = 0x5ee0; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_isFriendInTheWay = 0x5ef8; // bool m_isFriendInTheWay; |  0x5ef8 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_politeTimer = 0x5f00; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_isWaitingBehindFriend = 0x5f18; // bool m_isWaitingBehindFriend; |  0x5f18 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_pathLadderEnd = 0x5f44; // float32 m_pathLadderEnd; |  0x5f44 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_mustRunTimer = 0x5f90; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_waitTimer = 0x5fa8; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_updateTravelDistanceTimer = 0x5fc0; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_playerTravelDistance = 0x5fd8; // float32 m_playerTravelDistance[64]; |  0x5fd8 | Schema_FixedArray | Size: 0x100
				constexpr std::ptrdiff_t m_travelDistancePhase = 0x60d8; // uint8_t m_travelDistancePhase; |  0x60d8 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_hostageEscortCount = 0x6270; // uint8_t m_hostageEscortCount; |  0x6270 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_hostageEscortCountTimestamp = 0x6274; // float32 m_hostageEscortCountTimestamp; |  0x6274 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_desiredTeam = 0x6278; // int32_t m_desiredTeam; |  0x6278 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_hasJoined = 0x627c; // bool m_hasJoined; |  0x627c | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_isWaitingForHostage = 0x627d; // bool m_isWaitingForHostage; |  0x627d | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_inhibitWaitingForHostageTimer = 0x6280; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_waitForHostageTimer = 0x6298; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_noisePosition = 0x62b0; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_noiseTravelDistance = 0x62bc; // float32 m_noiseTravelDistance; |  0x62bc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_noiseTimestamp = 0x62c0; // float32 m_noiseTimestamp; |  0x62c0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_noiseSource = 0x62c8; // server::CCSPlayerPawn**  | Schema_Ptr | Size: 0x8
				constexpr std::ptrdiff_t m_noiseBendTimer = 0x62e0; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_bentNoisePosition = 0x62f8; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_bendNoisePositionValid = 0x6304; // bool m_bendNoisePositionValid; |  0x6304 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_lookAroundStateTimestamp = 0x6308; // float32 m_lookAroundStateTimestamp; |  0x6308 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_lookAheadAngle = 0x630c; // float32 m_lookAheadAngle; |  0x630c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_forwardAngle = 0x6310; // float32 m_forwardAngle; |  0x6310 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_inhibitLookAroundTimestamp = 0x6314; // float32 m_inhibitLookAroundTimestamp; |  0x6314 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_lookAtSpot = 0x631c; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_lookAtSpotDuration = 0x632c; // float32 m_lookAtSpotDuration; |  0x632c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_lookAtSpotTimestamp = 0x6330; // float32 m_lookAtSpotTimestamp; |  0x6330 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_lookAtSpotAngleTolerance = 0x6334; // float32 m_lookAtSpotAngleTolerance; |  0x6334 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_lookAtSpotClearIfClose = 0x6338; // bool m_lookAtSpotClearIfClose; |  0x6338 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_lookAtSpotAttack = 0x6339; // bool m_lookAtSpotAttack; |  0x6339 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_lookAtDesc = 0x6340; // char* m_lookAtDesc; |  0x6340 | Schema_Ptr | Size: 0x8
				constexpr std::ptrdiff_t m_peripheralTimestamp = 0x6348; // float32 m_peripheralTimestamp; |  0x6348 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_approachPointCount = 0x64d0; // uint8_t m_approachPointCount; |  0x64d0 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_approachPointViewPosition = 0x64d4; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_viewSteadyTimer = 0x64e0; // server::IntervalTimer  | Schema_DeclaredClass | Size: 0x10
				constexpr std::ptrdiff_t m_tossGrenadeTimer = 0x64f8; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_isAvoidingGrenade = 0x6518; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_spotCheckTimestamp = 0x6538; // float32 m_spotCheckTimestamp; |  0x6538 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_checkedHidingSpotCount = 0x6940; // int32_t m_checkedHidingSpotCount; |  0x6940 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_lookPitch = 0x6944; // float32 m_lookPitch; |  0x6944 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_lookPitchVel = 0x6948; // float32 m_lookPitchVel; |  0x6948 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_lookYaw = 0x694c; // float32 m_lookYaw; |  0x694c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_lookYawVel = 0x6950; // float32 m_lookYawVel; |  0x6950 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_targetSpot = 0x6954; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_targetSpotVelocity = 0x6960; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_targetSpotPredicted = 0x696c; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_aimError = 0x6978; // GlobalTypes::QAngle  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_aimGoal = 0x6984; // GlobalTypes::QAngle  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_targetSpotTime = 0x6990; // entity2::GameTime_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_aimFocus = 0x6994; // float32 m_aimFocus; |  0x6994 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_aimFocusInterval = 0x6998; // float32 m_aimFocusInterval; |  0x6998 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_aimFocusNextUpdate = 0x699c; // entity2::GameTime_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_ignoreEnemiesTimer = 0x69a8; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_enemy = 0x69c0; // GlobalTypes::CHandle<server::CCSPlayerPawn>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_isEnemyVisible = 0x69c4; // bool m_isEnemyVisible; |  0x69c4 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_visibleEnemyParts = 0x69c5; // uint8_t m_visibleEnemyParts; |  0x69c5 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_lastEnemyPosition = 0x69c8; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_lastSawEnemyTimestamp = 0x69d4; // float32 m_lastSawEnemyTimestamp; |  0x69d4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_firstSawEnemyTimestamp = 0x69d8; // float32 m_firstSawEnemyTimestamp; |  0x69d8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_currentEnemyAcquireTimestamp = 0x69dc; // float32 m_currentEnemyAcquireTimestamp; |  0x69dc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_enemyDeathTimestamp = 0x69e0; // float32 m_enemyDeathTimestamp; |  0x69e0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_friendDeathTimestamp = 0x69e4; // float32 m_friendDeathTimestamp; |  0x69e4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_isLastEnemyDead = 0x69e8; // bool m_isLastEnemyDead; |  0x69e8 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_nearbyEnemyCount = 0x69ec; // int32_t m_nearbyEnemyCount; |  0x69ec | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_bomber = 0x6bf8; // GlobalTypes::CHandle<server::CCSPlayerPawn>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_nearbyFriendCount = 0x6bfc; // int32_t m_nearbyFriendCount; |  0x6bfc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_closestVisibleFriend = 0x6c00; // GlobalTypes::CHandle<server::CCSPlayerPawn>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_closestVisibleHumanFriend = 0x6c04; // GlobalTypes::CHandle<server::CCSPlayerPawn>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_attentionInterval = 0x6c08; // server::IntervalTimer  | Schema_DeclaredClass | Size: 0x10
				constexpr std::ptrdiff_t m_attacker = 0x6c18; // GlobalTypes::CHandle<server::CCSPlayerPawn>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_attackedTimestamp = 0x6c1c; // float32 m_attackedTimestamp; |  0x6c1c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_burnedByFlamesTimer = 0x6c20; // server::IntervalTimer  | Schema_DeclaredClass | Size: 0x10
				constexpr std::ptrdiff_t m_lastVictimID = 0x6c30; // int32_t m_lastVictimID; |  0x6c30 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_isAimingAtEnemy = 0x6c34; // bool m_isAimingAtEnemy; |  0x6c34 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_isRapidFiring = 0x6c35; // bool m_isRapidFiring; |  0x6c35 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_equipTimer = 0x6c38; // server::IntervalTimer  | Schema_DeclaredClass | Size: 0x10
				constexpr std::ptrdiff_t m_zoomTimer = 0x6c48; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_fireWeaponTimestamp = 0x6c60; // entity2::GameTime_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_lookForWeaponsOnGroundTimer = 0x6c68; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_bIsSleeping = 0x6c80; // bool m_bIsSleeping; |  0x6c80 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_isEnemySniperVisible = 0x6c81; // bool m_isEnemySniperVisible; |  0x6c81 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_sawEnemySniperTimer = 0x6c88; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_enemyQueueIndex = 0x6d40; // uint8_t m_enemyQueueIndex; |  0x6d40 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_enemyQueueCount = 0x6d41; // uint8_t m_enemyQueueCount; |  0x6d41 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_enemyQueueAttendIndex = 0x6d42; // uint8_t m_enemyQueueAttendIndex; |  0x6d42 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_isStuck = 0x6d43; // bool m_isStuck; |  0x6d43 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_stuckTimestamp = 0x6d44; // entity2::GameTime_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_stuckSpot = 0x6d48; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_wiggleTimer = 0x6d58; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_stuckJumpTimer = 0x6d70; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
				constexpr std::ptrdiff_t m_nextCleanupCheckTimestamp = 0x6d88; // entity2::GameTime_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_avgVel = 0x6d8c; // float32 m_avgVel[10]; |  0x6d8c | Schema_FixedArray | Size: 0x28
				constexpr std::ptrdiff_t m_avgVelIndex = 0x6db4; // int32_t m_avgVelIndex; |  0x6db4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_avgVelCount = 0x6db8; // int32_t m_avgVelCount; |  0x6db8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_lastOrigin = 0x6dbc; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_lastRadioRecievedTimestamp = 0x6dcc; // float32 m_lastRadioRecievedTimestamp; |  0x6dcc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_lastRadioSentTimestamp = 0x6dd0; // float32 m_lastRadioSentTimestamp; |  0x6dd0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_radioSubject = 0x6dd4; // GlobalTypes::CHandle<server::CCSPlayerPawn>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_radioPosition = 0x6dd8; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_voiceEndTimestamp = 0x6de4; // float32 m_voiceEndTimestamp; |  0x6de4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_lastValidReactionQueueFrame = 0x6df0; // int32_t m_lastValidReactionQueueFrame; |  0x6df0 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
