// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CPulseCell_BaseYieldingInflow.hpp"
#include "CPulseRuntimeMethodArg.hpp"
#include "PulseMethodCallMode_t.hpp"
#include "CPulse_ResumePoint.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace pulse_runtime_lib {
		class CPulseCell_Step_CallExternalMethod : public CS2::pulse_runtime_lib::CPulseCell_BaseYieldingInflow {
		public:
			PROPERTY(m_MethodName,GlobalTypes::PulseSymbol_t, 0x48);
			PROPERTY(m_GameBlackboard,GlobalTypes::PulseSymbol_t, 0x58);
			// PROPERTY(m_ExpectedArgs,IDENTITY(GlobalTypes::CUtlLeanVector<pulse_runtime_lib::CPulseRuntimeMethodArg>), 0x68);
			PROPERTY(m_nAsyncCallMode,IDENTITY(pulse_runtime_lib::PulseMethodCallMode_t), 0x78);
			NESTED_PROPERTY(m_OnFinished,IDENTITY(pulse_runtime_lib::CPulse_ResumePoint), 0x80);
			S2_PAD(0x80);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::pulse_runtime_lib::CPulseCell_Step_CallExternalMethod) == 0xC8, "CPulseCell_Step_CallExternalMethod size should be 0xC8");

#endif
	}
}
