// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace pulse_runtime_lib {
		class PulseNodeDynamicOutflows_t  {
		public:
			PROPERTY(m_Outflows,assetpreview::CUtlVector<pulse_runtime_lib::PulseNodeDynamicOutflows_t::DynamicOutflow_t>, 0x0);
			S2_PAD(0x18);
		};
		//static_assert(sizeof(CS2::pulse_runtime_lib::PulseNodeDynamicOutflows_t) == 0x18, "PulseNodeDynamicOutflows_t size should be 0x18");
	}
}
