// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/worldrenderer/BakedLightingInfo_t.hpp>



namespace CS2 {
	namespace worldrenderer {
		class SceneObject_t;
		class AggregateSceneObject_t;
		class ClutterSceneObject_t;
		class ExtraVertexStreamOverride_t;
		class MaterialOverride_t;
		class WorldNodeOnDiskBufferData_t;
		class AggregateInstanceStreamOnDiskData_t;
		class AggregateVertexAlbedoStreamOnDiskData_t;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace worldrenderer {
		class WorldNode_t  {
		public:
			PROPERTY(m_sceneObjects,GlobalTypes::CUtlVector<worldrenderer::SceneObject_t>, 0x0);
			PROPERTY(m_visClusterMembership,GlobalTypes::CUtlVector< uint16 >, 0x18);
			PROPERTY(m_aggregateSceneObjects,GlobalTypes::CUtlVector<worldrenderer::AggregateSceneObject_t>, 0x30);
			PROPERTY(m_clutterSceneObjects,GlobalTypes::CUtlVector<worldrenderer::ClutterSceneObject_t>, 0x48);
			PROPERTY(m_extraVertexStreamOverrides,GlobalTypes::CUtlVector<worldrenderer::ExtraVertexStreamOverride_t>, 0x60);
			PROPERTY(m_materialOverrides,GlobalTypes::CUtlVector<worldrenderer::MaterialOverride_t>, 0x78);
			PROPERTY(m_extraVertexStreams,GlobalTypes::CUtlVector<worldrenderer::WorldNodeOnDiskBufferData_t>, 0x90);
			PROPERTY(m_aggregateInstanceStreams,GlobalTypes::CUtlVector<worldrenderer::AggregateInstanceStreamOnDiskData_t>, 0xa8);
			PROPERTY(m_vertexAlbedoStreams,GlobalTypes::CUtlVector<worldrenderer::AggregateVertexAlbedoStreamOnDiskData_t>, 0xc0);
			PROPERTY(m_layerNames,GlobalTypes::CUtlVector<GlobalTypes::CUtlString>, 0xd8);
			PROPERTY(m_sceneObjectLayerIndices,GlobalTypes::CUtlVector< uint8 >, 0xf0);
			PROPERTY(m_grassFileName,GlobalTypes::CUtlString* , 0x108);
			PROPERTY(m_nodeLightingInfo,worldrenderer::BakedLightingInfo_t , 0x110);
			PROPERTY(m_bHasBakedGeometryFlag,bool , 0x158);
			S2_PAD(0x160);
		};
		//static_assert(sizeof(CS2::worldrenderer::WorldNode_t) == 0x160, "WorldNode_t size should be 0x160");
	}
}
