// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem_lowlevel/VMixSubgraphSwitchInterpolationType_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_lowlevel {
		class VMixSubgraphSwitchDesc_t  {
		public:
			PROPERTY(m_interpolationMode,soundsystem_lowlevel::VMixSubgraphSwitchInterpolationType_t , 0x0);
			PROPERTY(m_bOnlyTailsOnFadeOut,bool , 0x4);
			PROPERTY(m_flInterpolationTime,float32 , 0x8);
			S2_PAD(0xC);
		};
		//static_assert(sizeof(CS2::soundsystem_lowlevel::VMixSubgraphSwitchDesc_t) == 0xC, "VMixSubgraphSwitchDesc_t size should be 0xC");
	}
}
