// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace modellib {
		class CHitBoxSet;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace modellib {
		class CHitBoxSetList  {
		public:
			PROPERTY(m_HitBoxSets,GlobalTypes::CUtlVector<modellib::CHitBoxSet>, 0x0);
			S2_PAD(0x18);
		};
		//static_assert(sizeof(CS2::modellib::CHitBoxSetList) == 0x18, "CHitBoxSetList size should be 0x18");
	}
}
