// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace modellib {
		class CMorphData;
		class CFlexDesc;
		class CFlexController;
		class CFlexRule;
	}
	namespace resourcesystem {
		class InfoForResourceTypeCTextureBase;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace modellib {
		class CMorphSetData  {
		public:
			PROPERTY(m_nWidth,int32_t , 0x10);
			PROPERTY(m_nHeight,int32_t , 0x14);
			PROPERTY(m_bundleTypes,GlobalTypes::CUtlVector< MorphBundleType_t >, 0x18);
			PROPERTY(m_morphDatas,GlobalTypes::CUtlVector<modellib::CMorphData>, 0x30);
			PROPERTY(m_pTextureAtlas,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCTextureBase>, 0x48);
			PROPERTY(m_FlexDesc,GlobalTypes::CUtlVector<modellib::CFlexDesc>, 0x50);
			PROPERTY(m_FlexControllers,GlobalTypes::CUtlVector<modellib::CFlexController>, 0x68);
			PROPERTY(m_FlexRules,GlobalTypes::CUtlVector<modellib::CFlexRule>, 0x80);
			S2_PAD(0x98);
		};
		//static_assert(sizeof(CS2::modellib::CMorphSetData) == 0x98, "CMorphSetData size should be 0x98");
	}
}
