// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace modellib {
		class RenderSkeletonBone_t;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace modellib {
		class CRenderSkeleton  {
		public:
			PROPERTY(m_bones,GlobalTypes::CUtlVector<modellib::RenderSkeletonBone_t>, 0x0);
			PROPERTY(m_boneParents,GlobalTypes::CUtlVector< int32 >, 0x30);
			PROPERTY(m_nBoneWeightCount,int32_t , 0x48);
			S2_PAD(0x50);
		};
		//static_assert(sizeof(CS2::modellib::CRenderSkeleton) == 0x50, "CRenderSkeleton size should be 0x50");
	}
}
