// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace physicslib {
		class RnSoftbodyParticle_t;
		class RnSoftbodySpring_t;
		class RnSoftbodyCapsule_t;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace modellib {
		class PhysSoftbodyDesc_t  {
		public:
			PROPERTY(m_ParticleBoneHash,GlobalTypes::CUtlVector< uint32 >, 0x0);
			PROPERTY(m_Particles,GlobalTypes::CUtlVector<physicslib::RnSoftbodyParticle_t>, 0x18);
			PROPERTY(m_Springs,GlobalTypes::CUtlVector<physicslib::RnSoftbodySpring_t>, 0x30);
			PROPERTY(m_Capsules,GlobalTypes::CUtlVector<physicslib::RnSoftbodyCapsule_t>, 0x48);
			PROPERTY(m_InitPose,GlobalTypes::CUtlVector<GlobalTypes::CTransform>, 0x60);
			PROPERTY(m_ParticleBoneName,GlobalTypes::CUtlVector<GlobalTypes::CUtlString>, 0x78);
			S2_PAD(0x90);
		};
		//static_assert(sizeof(CS2::modellib::PhysSoftbodyDesc_t) == 0x90, "PhysSoftbodyDesc_t size should be 0x90");
	}
}
