// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace modellib {
		class Bone_t;
		class Frame_t;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace modellib {
		class SkeletonAnimCapture_t  {
		public:
			PROPERTY(m_nEntIndex,GlobalTypes::CEntityIndex , 0x0);
			PROPERTY(m_nEntParent,GlobalTypes::CEntityIndex , 0x4);
			PROPERTY(m_ImportedCollision,GlobalTypes::CUtlVector<GlobalTypes::CEntityIndex>, 0x8);
			PROPERTY(m_ModelName,GlobalTypes::CUtlString* , 0x20);
			PROPERTY(m_CaptureName,GlobalTypes::CUtlString* , 0x28);
			PROPERTY(m_ModelBindPose,GlobalTypes::CUtlVector<modellib::SkeletonAnimCapture_t::Bone_t>, 0x30);
			PROPERTY(m_FeModelInitPose,GlobalTypes::CUtlVector<modellib::SkeletonAnimCapture_t::Bone_t>, 0x48);
			PROPERTY(m_nFlexControllers,int32_t , 0x60);
			PROPERTY(m_bPredicted,bool , 0x64);
			PROPERTY(m_Frames,GlobalTypes::CUtlVector<modellib::SkeletonAnimCapture_t::Frame_t>, 0xa8);
			S2_PAD(0xC0);
		};
		//static_assert(sizeof(CS2::modellib::SkeletonAnimCapture_t) == 0xC0, "SkeletonAnimCapture_t size should be 0xC0");
	}
}
