// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionInitializer.hpp"
#include "../particleslib/CParticleTransformInput.hpp"
#include "ParticleControlPointAxis_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_NormalAlignToCP : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_transformInput,IDENTITY(particleslib::CParticleTransformInput), 0x1d8);
			PROPERTY(m_nControlPointAxis,IDENTITY(particles::ParticleControlPointAxis_t), 0x240);
			S2_PAD(0x70);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_NormalAlignToCP) == 0x248, "C_INIT_NormalAlignToCP size should be 0x248");

#endif
	}
}
