// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionInitializer.hpp"
#include "../particleslib/CPerParticleFloatInput.hpp"
#include "../particleslib/CParticleCollectionFloatInput.hpp"
#include "CPathParameters.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_CreateSequentialPathV2 : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_fMaxDistance,IDENTITY(particleslib::CPerParticleFloatInput), 0x1d8);
			NESTED_PROPERTY(m_flNumToAssign,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x348);
			PROPERTY(m_bLoop,bool, 0x4b8);
			PROPERTY(m_bCPPairs,bool, 0x4b9);
			PROPERTY(m_bSaveOffset,bool, 0x4ba);
			NESTED_PROPERTY(m_PathParams,IDENTITY(particles::CPathParameters), 0x4c0);
			S2_PAD(0x338);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_CreateSequentialPathV2) == 0x510, "C_INIT_CreateSequentialPathV2 size should be 0x510");

#endif
	}
}
