// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionInitializer.hpp"
#include "../particleslib/CPerParticleVecInput.hpp"
#include "../particleslib/CParticleTransformInput.hpp"
#include "CRandomNumberGeneratorParameters.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_PositionOffset : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_OffsetMin,IDENTITY(particleslib::CPerParticleVecInput), 0x1d8);
			NESTED_PROPERTY(m_OffsetMax,IDENTITY(particleslib::CPerParticleVecInput), 0x890);
			NESTED_PROPERTY(m_TransformInput,IDENTITY(particleslib::CParticleTransformInput), 0xf48);
			PROPERTY(m_bLocalCoords,bool, 0xfb0);
			PROPERTY(m_bProportional,bool, 0xfb1);
			NESTED_PROPERTY(m_randomnessParameters,IDENTITY(particles::CRandomNumberGeneratorParameters), 0xfb4);
			S2_PAD(0xDE8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_PositionOffset) == 0xFC0, "C_INIT_PositionOffset size should be 0xFC0");

#endif
	}
}
