// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionInitializer.hpp"
#include "ParticleAttributeIndex_t.hpp"
#include "../particleslib/CPerParticleFloatInput.hpp"
#include "ParticleTraceSet_t.hpp"
#include "ParticleSetMethod_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_DistanceToCPInit : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_nFieldOutput,IDENTITY(particles::ParticleAttributeIndex_t), 0x1d8);
			NESTED_PROPERTY(m_flInputMin,IDENTITY(particleslib::CPerParticleFloatInput), 0x1e0);
			NESTED_PROPERTY(m_flInputMax,IDENTITY(particleslib::CPerParticleFloatInput), 0x350);
			NESTED_PROPERTY(m_flOutputMin,IDENTITY(particleslib::CPerParticleFloatInput), 0x4c0);
			NESTED_PROPERTY(m_flOutputMax,IDENTITY(particleslib::CPerParticleFloatInput), 0x630);
			PROPERTY(m_nStartCP,int32_t, 0x7a0);
			PROPERTY(m_bLOS,bool, 0x7a4);
			PROPERTY_ARRAY(m_CollisionGroupName,char, 128 , 0x7a5);
			PROPERTY(m_nTraceSet,IDENTITY(particles::ParticleTraceSet_t), 0x828);
			NESTED_PROPERTY(m_flMaxTraceLength,IDENTITY(particleslib::CPerParticleFloatInput), 0x830);
			PROPERTY(m_flLOSScale,float32, 0x9a0);
			PROPERTY(m_nSetMethod,IDENTITY(particles::ParticleSetMethod_t), 0x9a4);
			PROPERTY(m_bActiveRange,bool, 0x9a8);
			PROPERTY(m_vecDistanceScale,GlobalTypes::Vector, 0x9ac);
			PROPERTY(m_flRemapBias,float32, 0x9b8);
			S2_PAD(0x7E8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_DistanceToCPInit) == 0x9C0, "C_INIT_DistanceToCPInit size should be 0x9C0");

#endif
	}
}
