// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionInitializer.hpp"
#include "../particleslib/CParticleTransformInput.hpp"
#include "../particleslib/CParticleCollectionFloatInput.hpp"
#include "../particleslib/CPerParticleFloatInput.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_RingWave : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_TransformInput,IDENTITY(particleslib::CParticleTransformInput), 0x1d8);
			NESTED_PROPERTY(m_flParticlesPerOrbit,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x240);
			NESTED_PROPERTY(m_flInitialRadius,IDENTITY(particleslib::CPerParticleFloatInput), 0x3b0);
			NESTED_PROPERTY(m_flThickness,IDENTITY(particleslib::CPerParticleFloatInput), 0x520);
			NESTED_PROPERTY(m_flInitialSpeedMin,IDENTITY(particleslib::CPerParticleFloatInput), 0x690);
			NESTED_PROPERTY(m_flInitialSpeedMax,IDENTITY(particleslib::CPerParticleFloatInput), 0x800);
			NESTED_PROPERTY(m_flRoll,IDENTITY(particleslib::CPerParticleFloatInput), 0x970);
			NESTED_PROPERTY(m_flPitch,IDENTITY(particleslib::CPerParticleFloatInput), 0xae0);
			NESTED_PROPERTY(m_flYaw,IDENTITY(particleslib::CPerParticleFloatInput), 0xc50);
			PROPERTY(m_bEvenDistribution,bool, 0xdc0);
			PROPERTY(m_bXYVelocityOnly,bool, 0xdc1);
			S2_PAD(0xBF0);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_RingWave) == 0xDC8, "C_INIT_RingWave size should be 0xDC8");

#endif
	}
}
