// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionInitializer.hpp"
#include "ParticleAttributeIndex_t.hpp"
#include "CRandomNumberGeneratorParameters.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_AddVectorToVector : public CS2::particles::CParticleFunctionInitializer {
		public:
			PROPERTY(m_vecScale,GlobalTypes::Vector, 0x1d8);
			NESTED_PROPERTY(m_nFieldOutput,IDENTITY(particles::ParticleAttributeIndex_t), 0x1e4);
			NESTED_PROPERTY(m_nFieldInput,IDENTITY(particles::ParticleAttributeIndex_t), 0x1e8);
			PROPERTY(m_vOffsetMin,GlobalTypes::Vector, 0x1ec);
			PROPERTY(m_vOffsetMax,GlobalTypes::Vector, 0x1f8);
			NESTED_PROPERTY(m_randomnessParameters,IDENTITY(particles::CRandomNumberGeneratorParameters), 0x204);
			S2_PAD(0x38);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_AddVectorToVector) == 0x210, "C_INIT_AddVectorToVector size should be 0x210");

#endif
	}
}
