// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionInitializer.hpp"
#include "../particleslib/CPerParticleFloatInput.hpp"
#include "../particleslib/CPerParticleVecInput.hpp"
#include "../particleslib/CParticleTransformInput.hpp"
#include "ParticleAttributeIndex_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_CreateWithinSphereTransform : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_fRadiusMin,IDENTITY(particleslib::CPerParticleFloatInput), 0x1d8);
			NESTED_PROPERTY(m_fRadiusMax,IDENTITY(particleslib::CPerParticleFloatInput), 0x348);
			NESTED_PROPERTY(m_vecDistanceBias,IDENTITY(particleslib::CPerParticleVecInput), 0x4b8);
			PROPERTY(m_vecDistanceBiasAbs,GlobalTypes::Vector, 0xb70);
			NESTED_PROPERTY(m_TransformInput,IDENTITY(particleslib::CParticleTransformInput), 0xb80);
			NESTED_PROPERTY(m_fSpeedMin,IDENTITY(particleslib::CPerParticleFloatInput), 0xbe8);
			NESTED_PROPERTY(m_fSpeedMax,IDENTITY(particleslib::CPerParticleFloatInput), 0xd58);
			PROPERTY(m_fSpeedRandExp,float32, 0xec8);
			PROPERTY(m_bLocalCoords,bool, 0xecc);
			NESTED_PROPERTY(m_LocalCoordinateSystemSpeedMin,IDENTITY(particleslib::CPerParticleVecInput), 0xed0);
			NESTED_PROPERTY(m_LocalCoordinateSystemSpeedMax,IDENTITY(particleslib::CPerParticleVecInput), 0x1588);
			NESTED_PROPERTY(m_nFieldOutput,IDENTITY(particles::ParticleAttributeIndex_t), 0x1c40);
			NESTED_PROPERTY(m_nFieldVelocity,IDENTITY(particles::ParticleAttributeIndex_t), 0x1c44);
			S2_PAD(0x1A70);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_CreateWithinSphereTransform) == 0x1C48, "C_INIT_CreateWithinSphereTransform size should be 0x1C48");

#endif
	}
}
