// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionInitializer.hpp"
#include "SequenceWeightedList_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_RandomSequence : public CS2::particles::CParticleFunctionInitializer {
		public:
			PROPERTY(m_nSequenceMin,int32_t, 0x1d8);
			PROPERTY(m_nSequenceMax,int32_t, 0x1dc);
			PROPERTY(m_bShuffle,bool, 0x1e0);
			PROPERTY(m_bLinear,bool, 0x1e1);
			NESTED_PROPERTY(m_WeightedList,IDENTITY(GlobalTypes::CUtlVector<particles::SequenceWeightedList_t>), 0x1e8);
			S2_PAD(0x30);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_RandomSequence) == 0x208, "C_INIT_RandomSequence size should be 0x208");

#endif
	}
}
