// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionInitializer.hpp"
#include "../particleslib/CParticleCollectionVecInput.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_INIT_ScaleVelocity : public CS2::particles::CParticleFunctionInitializer {
		public:
			NESTED_PROPERTY(m_vecScale,IDENTITY(particleslib::CParticleCollectionVecInput), 0x1d8);
			S2_PAD(0x6B8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_INIT_ScaleVelocity) == 0x890, "C_INIT_ScaleVelocity size should be 0x890");

#endif
	}
}
