// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionOperator.hpp"
#include "ParticleAttributeIndex_t.hpp"
#include "../particleslib/CParticleCollectionFloatInput.hpp"
#include "../particleslib/CPerParticleFloatInput.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_SetFromCPSnapshot : public CS2::particles::CParticleFunctionOperator {
		public:
			PROPERTY(m_nControlPointNumber,int32_t, 0x1d0);
			PROPERTY(m_strSnapshotSubset,GlobalTypes::CUtlString*, 0x1d8);
			NESTED_PROPERTY(m_nAttributeToRead,IDENTITY(particles::ParticleAttributeIndex_t), 0x1e0);
			NESTED_PROPERTY(m_nAttributeToWrite,IDENTITY(particles::ParticleAttributeIndex_t), 0x1e4);
			PROPERTY(m_nLocalSpaceCP,int32_t, 0x1e8);
			PROPERTY(m_bRandom,bool, 0x1ec);
			PROPERTY(m_bReverse,bool, 0x1ed);
			PROPERTY(m_nRandomSeed,int32_t, 0x1f0);
			NESTED_PROPERTY(m_nSnapShotStartPoint,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x1f8);
			NESTED_PROPERTY(m_nSnapShotIncrement,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x368);
			NESTED_PROPERTY(m_flInterpolation,IDENTITY(particleslib::CPerParticleFloatInput), 0x4d8);
			PROPERTY(m_bSubSample,bool, 0x648);
			PROPERTY(m_bPrev,bool, 0x649);
			S2_PAD(0x480);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_SetFromCPSnapshot) == 0x650, "C_OP_SetFromCPSnapshot size should be 0x650");

#endif
	}
}
