// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionConstraint.hpp"
#include "../particleslib/CParticleCollectionVecInput.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_BoxConstraint : public CS2::particles::CParticleFunctionConstraint {
		public:
			NESTED_PROPERTY(m_vecMin,IDENTITY(particleslib::CParticleCollectionVecInput), 0x1d0);
			NESTED_PROPERTY(m_vecMax,IDENTITY(particleslib::CParticleCollectionVecInput), 0x888);
			PROPERTY(m_nCP,int32_t, 0xf40);
			PROPERTY(m_bLocalSpace,bool, 0xf44);
			PROPERTY(m_bAccountForRadius,bool, 0xf45);
			S2_PAD(0xD78);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_BoxConstraint) == 0xF48, "C_OP_BoxConstraint size should be 0xF48");

#endif
	}
}
