// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionConstraint.hpp"
#include "CPathParameters.hpp"
#include "ParticleAttributeIndex_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_ConstrainDistanceToPath : public CS2::particles::CParticleFunctionConstraint {
		public:
			PROPERTY(m_fMinDistance,float32, 0x1d0);
			PROPERTY(m_flMaxDistance0,float32, 0x1d4);
			PROPERTY(m_flMaxDistanceMid,float32, 0x1d8);
			PROPERTY(m_flMaxDistance1,float32, 0x1dc);
			NESTED_PROPERTY(m_PathParameters,IDENTITY(particles::CPathParameters), 0x1e0);
			PROPERTY(m_flTravelTime,float32, 0x220);
			NESTED_PROPERTY(m_nFieldScale,IDENTITY(particles::ParticleAttributeIndex_t), 0x224);
			NESTED_PROPERTY(m_nManualTField,IDENTITY(particles::ParticleAttributeIndex_t), 0x228);
			S2_PAD(0x60);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_ConstrainDistanceToPath) == 0x230, "C_OP_ConstrainDistanceToPath size should be 0x230");

#endif
	}
}
