// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionOperator.hpp"
#include "../particleslib/CPerParticleVecInput.hpp"
#include "ParticleAttributeIndex_t.hpp"
#include "../particleslib/CParticleRemapFloatInput.hpp"
#include "ParticleSetMethod_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_ScreenSpacePositionOfTarget : public CS2::particles::CParticleFunctionOperator {
		public:
			NESTED_PROPERTY(m_vecTargetPosition,IDENTITY(particleslib::CPerParticleVecInput), 0x1d0);
			PROPERTY(m_bOututBehindness,bool, 0x888);
			NESTED_PROPERTY(m_nBehindFieldOutput,IDENTITY(particles::ParticleAttributeIndex_t), 0x88c);
			NESTED_PROPERTY(m_flBehindOutputRemap,IDENTITY(particleslib::CParticleRemapFloatInput), 0x890);
			PROPERTY(m_nBehindSetMethod,IDENTITY(particles::ParticleSetMethod_t), 0xa00);
			S2_PAD(0x838);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_ScreenSpacePositionOfTarget) == 0xA08, "C_OP_ScreenSpacePositionOfTarget size should be 0xA08");

#endif
	}
}
