// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionOperator.hpp"
#include "ParticleAttributeIndex_t.hpp"
#include "../particleslib/CParticleTransformInput.hpp"
#include "../particleslib/CPerParticleFloatInput.hpp"
#include "ParticleTraceSet_t.hpp"
#include "ParticleSetMethod_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_DistanceBetweenTransforms : public CS2::particles::CParticleFunctionOperator {
		public:
			NESTED_PROPERTY(m_nFieldOutput,IDENTITY(particles::ParticleAttributeIndex_t), 0x1d0);
			NESTED_PROPERTY(m_TransformStart,IDENTITY(particleslib::CParticleTransformInput), 0x1d8);
			NESTED_PROPERTY(m_TransformEnd,IDENTITY(particleslib::CParticleTransformInput), 0x240);
			NESTED_PROPERTY(m_flInputMin,IDENTITY(particleslib::CPerParticleFloatInput), 0x2a8);
			NESTED_PROPERTY(m_flInputMax,IDENTITY(particleslib::CPerParticleFloatInput), 0x418);
			NESTED_PROPERTY(m_flOutputMin,IDENTITY(particleslib::CPerParticleFloatInput), 0x588);
			NESTED_PROPERTY(m_flOutputMax,IDENTITY(particleslib::CPerParticleFloatInput), 0x6f8);
			PROPERTY(m_flMaxTraceLength,float32, 0x868);
			PROPERTY(m_flLOSScale,float32, 0x86c);
			PROPERTY_ARRAY(m_CollisionGroupName,char, 128 , 0x870);
			PROPERTY(m_nTraceSet,IDENTITY(particles::ParticleTraceSet_t), 0x8f0);
			PROPERTY(m_bLOS,bool, 0x8f4);
			PROPERTY(m_nSetMethod,IDENTITY(particles::ParticleSetMethod_t), 0x8f8);
			S2_PAD(0x730);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_DistanceBetweenTransforms) == 0x900, "C_OP_DistanceBetweenTransforms size should be 0x900");

#endif
	}
}
