// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionOperator.hpp"
#include "VectorExpressionType_t.hpp"
#include "../particleslib/CPerParticleVecInput.hpp"
#include "../particleslib/CPerParticleFloatInput.hpp"
#include "ParticleAttributeIndex_t.hpp"
#include "ParticleSetMethod_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_SetVectorAttributeToVectorExpression : public CS2::particles::CParticleFunctionOperator {
		public:
			PROPERTY(m_nExpression,IDENTITY(particles::VectorExpressionType_t), 0x1d0);
			NESTED_PROPERTY(m_vInput1,IDENTITY(particleslib::CPerParticleVecInput), 0x1d8);
			NESTED_PROPERTY(m_vInput2,IDENTITY(particleslib::CPerParticleVecInput), 0x890);
			NESTED_PROPERTY(m_flLerp,IDENTITY(particleslib::CPerParticleFloatInput), 0xf48);
			NESTED_PROPERTY(m_nOutputField,IDENTITY(particles::ParticleAttributeIndex_t), 0x10b8);
			PROPERTY(m_nSetMethod,IDENTITY(particles::ParticleSetMethod_t), 0x10bc);
			PROPERTY(m_bNormalizedOutput,bool, 0x10c0);
			S2_PAD(0xF60);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_SetVectorAttributeToVectorExpression) == 0x1130, "C_OP_SetVectorAttributeToVectorExpression size should be 0x1130");

#endif
	}
}
