// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionPreEmission.hpp"
#include "ParticleEntityPos_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_SetControlPointToPlayer : public CS2::particles::CParticleFunctionPreEmission {
		public:
			PROPERTY(m_nCP1,int32_t, 0x1d8);
			PROPERTY(m_vecCP1Pos,GlobalTypes::Vector, 0x1dc);
			PROPERTY(m_bOrientToEyes,bool, 0x1e8);
			PROPERTY(m_nPosition,IDENTITY(particles::ParticleEntityPos_t), 0x1ec);
			S2_PAD(0x18);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_SetControlPointToPlayer) == 0x1F0, "C_OP_SetControlPointToPlayer size should be 0x1F0");

#endif
	}
}
