// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionPreEmission.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_SetControlPointOrientationToCPVelocity : public CS2::particles::CParticleFunctionPreEmission {
		public:
			PROPERTY(m_nCPInput,int32_t, 0x1d8);
			PROPERTY(m_nCPOutput,int32_t, 0x1dc);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_SetControlPointOrientationToCPVelocity) == 0x1E0, "C_OP_SetControlPointOrientationToCPVelocity size should be 0x1E0");

#endif
	}
}
