// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionOperator.hpp"
#include "ParticleAttributeIndex_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_FadeOutSimple : public CS2::particles::CParticleFunctionOperator {
		public:
			PROPERTY(m_flFadeOutTime,float32, 0x1d0);
			NESTED_PROPERTY(m_nFieldOutput,IDENTITY(particles::ParticleAttributeIndex_t), 0x1d4);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_FadeOutSimple) == 0x1D8, "C_OP_FadeOutSimple size should be 0x1D8");

#endif
	}
}
