// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionPreEmission.hpp"
#include "../particleslib/CParticleVariableRef.hpp"
#include "../particleslib/CParticleTransformInput.hpp"
#include "../particleslib/CParticleCollectionVecInput.hpp"
#include "../particleslib/CParticleCollectionFloatInput.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_SetVariable : public CS2::particles::CParticleFunctionPreEmission {
		public:
			NESTED_PROPERTY(m_variableReference,IDENTITY(particleslib::CParticleVariableRef), 0x1d8);
			NESTED_PROPERTY(m_transformInput,IDENTITY(particleslib::CParticleTransformInput), 0x228);
			PROPERTY(m_positionOffset,GlobalTypes::Vector, 0x290);
			PROPERTY(m_rotationOffset,GlobalTypes::QAngle, 0x29c);
			NESTED_PROPERTY(m_vecInput,IDENTITY(particleslib::CParticleCollectionVecInput), 0x2a8);
			NESTED_PROPERTY(m_floatInput,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x960);
			S2_PAD(0x8F8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_SetVariable) == 0xAD0, "C_OP_SetVariable size should be 0xAD0");

#endif
	}
}
