// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionOperator.hpp"
#include "../particleslib/CParticleCollectionFloatInput.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_ConnectParentParticleToNearest : public CS2::particles::CParticleFunctionOperator {
		public:
			PROPERTY(m_nFirstControlPoint,int32_t, 0x1d0);
			PROPERTY(m_nSecondControlPoint,int32_t, 0x1d4);
			PROPERTY(m_bUseRadius,bool, 0x1d8);
			NESTED_PROPERTY(m_flRadiusScale,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x1e0);
			NESTED_PROPERTY(m_flParentRadiusScale,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x350);
			S2_PAD(0x2F0);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_ConnectParentParticleToNearest) == 0x4C0, "C_OP_ConnectParentParticleToNearest size should be 0x4C0");

#endif
	}
}
