// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionRenderer.hpp"
#include "../particleslib/CParticleCollectionVecInput.hpp"
#include "ParticleColorBlendType_t.hpp"
#include "../particleslib/CParticleCollectionFloatInput.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_RenderLightBeam : public CS2::particles::CParticleFunctionRenderer {
		public:
			NESTED_PROPERTY(m_vColorBlend,IDENTITY(particleslib::CParticleCollectionVecInput), 0x220);
			PROPERTY(m_nColorBlendType,IDENTITY(particles::ParticleColorBlendType_t), 0x8d8);
			NESTED_PROPERTY(m_flBrightnessLumensPerMeter,IDENTITY(particleslib::CParticleCollectionFloatInput), 0x8e0);
			PROPERTY(m_bCastShadows,bool, 0xa50);
			NESTED_PROPERTY(m_flSkirt,IDENTITY(particleslib::CParticleCollectionFloatInput), 0xa58);
			NESTED_PROPERTY(m_flRange,IDENTITY(particleslib::CParticleCollectionFloatInput), 0xbc8);
			NESTED_PROPERTY(m_flThickness,IDENTITY(particleslib::CParticleCollectionFloatInput), 0xd38);
			S2_PAD(0xC88);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_RenderLightBeam) == 0xEA8, "C_OP_RenderLightBeam size should be 0xEA8");

#endif
	}
}
