// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionPreEmission.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_SetParentControlPointsToChildCP : public CS2::particles::CParticleFunctionPreEmission {
		public:
			PROPERTY(m_nChildGroupID,int32_t, 0x1d8);
			PROPERTY(m_nChildControlPoint,int32_t, 0x1dc);
			PROPERTY(m_nNumControlPoints,int32_t, 0x1e0);
			PROPERTY(m_nFirstSourcePoint,int32_t, 0x1e4);
			PROPERTY(m_bSetOrientation,bool, 0x1e8);
			S2_PAD(0x18);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_SetParentControlPointsToChildCP) == 0x1F0, "C_OP_SetParentControlPointsToChildCP size should be 0x1F0");

#endif
	}
}
