// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionOperator.hpp"
#include "ParticleAttributeIndex_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_RemapScalarEndCap : public CS2::particles::CParticleFunctionOperator {
		public:
			NESTED_PROPERTY(m_nFieldInput,IDENTITY(particles::ParticleAttributeIndex_t), 0x1d0);
			NESTED_PROPERTY(m_nFieldOutput,IDENTITY(particles::ParticleAttributeIndex_t), 0x1d4);
			PROPERTY(m_flInputMin,float32, 0x1d8);
			PROPERTY(m_flInputMax,float32, 0x1dc);
			PROPERTY(m_flOutputMin,float32, 0x1e0);
			PROPERTY(m_flOutputMax,float32, 0x1e4);
			S2_PAD(0x18);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_RemapScalarEndCap) == 0x1E8, "C_OP_RemapScalarEndCap size should be 0x1E8");

#endif
	}
}
