// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CParticleFunctionOperator.hpp"
#include "ParticleAttributeIndex_t.hpp"



namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeCModel;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace particles {
		class C_OP_RemapNamedModelElementEndCap : public CS2::particles::CParticleFunctionOperator {
		public:
			PROPERTY(m_hModel,IDENTITY(GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCModel>), 0x1d0);
			PROPERTY(m_inNames,IDENTITY(GlobalTypes::CUtlVector<GlobalTypes::CUtlString>), 0x1d8);
			PROPERTY(m_outNames,IDENTITY(GlobalTypes::CUtlVector<GlobalTypes::CUtlString>), 0x1f0);
			PROPERTY(m_fallbackNames,IDENTITY(GlobalTypes::CUtlVector<GlobalTypes::CUtlString>), 0x208);
			PROPERTY(m_bModelFromRenderer,bool, 0x220);
			NESTED_PROPERTY(m_nFieldInput,IDENTITY(particles::ParticleAttributeIndex_t), 0x224);
			NESTED_PROPERTY(m_nFieldOutput,IDENTITY(particles::ParticleAttributeIndex_t), 0x228);
			S2_PAD(0x60);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::particles::C_OP_RemapNamedModelElementEndCap) == 0x230, "C_OP_RemapNamedModelElementEndCap size should be 0x230");

#endif
	}
}
