// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "RnShapeDesc_t.hpp"
#include "RnMesh_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace physicslib {
		class RnMeshDesc_t : public CS2::physicslib::RnShapeDesc_t {
		public:
			NESTED_PROPERTY(m_Mesh,IDENTITY(physicslib::RnMesh_t), 0x18);
			S2_PAD(0xC0);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::physicslib::RnMeshDesc_t) == 0xD8, "RnMeshDesc_t size should be 0xD8");

#endif
	}
}
