// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_BaseToggle.hpp"
#include "../entity2/CEntityIOOutput.hpp"
#include "C_BaseEntity.hpp"



namespace CS2 {
	namespace client {
		class CBaseFilter;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_BaseTrigger : public CS2::client::C_BaseToggle {
		public:
			NESTED_PROPERTY(m_OnStartTouch,IDENTITY(entity2::CEntityIOOutput), 0xe88);
			NESTED_PROPERTY(m_OnStartTouchAll,IDENTITY(entity2::CEntityIOOutput), 0xea0);
			NESTED_PROPERTY(m_OnEndTouch,IDENTITY(entity2::CEntityIOOutput), 0xeb8);
			NESTED_PROPERTY(m_OnEndTouchAll,IDENTITY(entity2::CEntityIOOutput), 0xed0);
			NESTED_PROPERTY(m_OnTouching,IDENTITY(entity2::CEntityIOOutput), 0xee8);
			NESTED_PROPERTY(m_OnTouchingEachEntity,IDENTITY(entity2::CEntityIOOutput), 0xf00);
			NESTED_PROPERTY(m_OnNotTouching,IDENTITY(entity2::CEntityIOOutput), 0xf18);
			NESTED_PROPERTY(m_hTouchingEntities,IDENTITY(GlobalTypes::CUtlVector<GlobalTypes::CHandle<client::C_BaseEntity>>), 0xf30);
			PROPERTY(m_iFilterName,GlobalTypes::CUtlSymbolLarge*, 0xf48);
			PROPERTY(m_hFilter,IDENTITY(GlobalTypes::CHandle<client::CBaseFilter>), 0xf50);
			PROPERTY(m_bDisabled,bool, 0xf54);
			S2_PAD(0xD0);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_BaseTrigger) == 0xF58, "C_BaseTrigger size should be 0xF58");

#endif
	}
}
