// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseFlex.hpp>
#include <SDK/modellib/AttachmentHandle_t.hpp>
#include <SDK/client/WaterWakeMode_t.hpp>




using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_EconWearable;
		class C_BaseCombatCharacter : public CS2::client::C_BaseFlex {
		public:
			PROPERTY(m_hMyWearables,GlobalTypes::C_NetworkUtlVectorBase<GlobalTypes::CHandle<client::C_EconWearable>>, 0x1368);
			PROPERTY(m_leftFootAttachment,modellib::AttachmentHandle_t , 0x1380);
			PROPERTY(m_rightFootAttachment,modellib::AttachmentHandle_t , 0x1381);
			PROPERTY(m_nWaterWakeMode,client::WaterWakeMode_t , 0x1384);
			PROPERTY(m_flWaterWorldZ,float32 , 0x1388);
			PROPERTY(m_flWaterNextTraceTime,float32 , 0x138c);
			S2_PAD(0x88);
		};
		//static_assert(sizeof(CS2::client::C_BaseCombatCharacter) == 0x13F0, "C_BaseCombatCharacter size should be 0x13F0");
	}
}
