// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseEntity.hpp>
#include <SDK/client/CHitboxComponent.hpp>
#include <SDK/client/HitGroup_t.hpp>
#include <SDK/client/RenderMode_t.hpp>
#include <SDK/client/RenderFx_t.hpp>
#include <SDK/client/CCollisionProperty.hpp>
#include <SDK/client/CGlowProperty.hpp>
#include <SDK/client/DecalMode_t.hpp>
#include <SDK/client/CNetworkViewOffsetVector.hpp>



namespace CS2 {
	namespace client {
		class CRenderComponent;
		class CDestructiblePartsComponent;
		class EntityRenderAttribute_t;
		class CClientAlphaProperty;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_BaseModelEntity : public CS2::client::C_BaseEntity {
		public:
			PROPERTY(m_CRenderComponent,client::CRenderComponent* , 0xae0);
			PROPERTY(m_CHitboxComponent,client::CHitboxComponent , 0xae8);
			PROPERTY(m_pDestructiblePartsSystemComponent,client::CDestructiblePartsComponent* , 0xb00);
			PROPERTY(m_LastHitGroup,client::HitGroup_t , 0xb08);
			PROPERTY(m_sLastDamageSourceName,GlobalTypes::CGlobalSymbol , 0xb10);
			PROPERTY(m_vLastDamagePosition,GlobalTypes::VectorWS , 0xb18);
			PROPERTY(m_bInitModelEffects,bool , 0xb40);
			PROPERTY(m_bIsStaticProp,bool , 0xb41);
			PROPERTY(m_nLastAddDecal,int32_t , 0xb44);
			PROPERTY(m_nDecalsAdded,int32_t , 0xb48);
			PROPERTY(m_iOldHealth,int32_t , 0xb4c);
			PROPERTY(m_nRenderMode,client::RenderMode_t , 0xb50);
			PROPERTY(m_nRenderFX,client::RenderFx_t , 0xb51);
			PROPERTY(m_bAllowFadeInView,bool , 0xb52);
			PROPERTY(m_clrRender,GlobalTypes::Color , 0xb70);
			PROPERTY(m_vecRenderAttributes,GlobalTypes::C_UtlVectorEmbeddedNetworkVar<client::EntityRenderAttribute_t>, 0xb78);
			PROPERTY(m_bRenderToCubemaps,bool , 0xbf8);
			PROPERTY(m_bNoInterpolate,bool , 0xbf9);
			PROPERTY(m_Collision,client::CCollisionProperty , 0xc00);
			PROPERTY(m_Glow,client::CGlowProperty , 0xcb0);
			PROPERTY(m_flGlowBackfaceMult,float32 , 0xd08);
			PROPERTY(m_fadeMinDist,float32 , 0xd0c);
			PROPERTY(m_fadeMaxDist,float32 , 0xd10);
			PROPERTY(m_flFadeScale,float32 , 0xd14);
			PROPERTY(m_flShadowStrength,float32 , 0xd18);
			PROPERTY(m_nObjectCulling,uint8_t , 0xd1c);
			PROPERTY(m_nAddDecal,int32_t , 0xd20);
			PROPERTY(m_vDecalPosition,GlobalTypes::Vector , 0xd24);
			PROPERTY(m_vDecalForwardAxis,GlobalTypes::Vector , 0xd30);
			PROPERTY(m_nDecalMode,client::DecalMode_t , 0xd3c);
			PROPERTY(m_nRequiredDecalMode,client::DecalMode_t , 0xd3d);
			PROPERTY(m_ConfigEntitiesToPropagateMaterialDecalsTo,GlobalTypes::C_NetworkUtlVectorBase<GlobalTypes::CHandle<client::C_BaseModelEntity>>, 0xd40);
			PROPERTY(m_vecViewOffset,Vector , 0xd80);
			PROPERTY(m_pClientAlphaProperty,client::CClientAlphaProperty* , 0xe60);
			PROPERTY(m_ClientOverrideTint,GlobalTypes::Color , 0xe68);
			PROPERTY(m_bUseClientOverrideTint,bool , 0xe6c);
			PROPERTY_ARRAY(m_bvDisabledHitGroups,uint32_t , 1 , 0xea8);
			S2_PAD(0x8B8);
		};
		//static_assert(sizeof(CS2::client::C_BaseModelEntity) == 0xEB0, "C_BaseModelEntity size should be 0xEB0");
	}
}
