// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_BaseToggle.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_BaseDoor : public CS2::client::C_BaseToggle {
		public:
			PROPERTY(m_bIsUsable,bool, 0xe88);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_BaseDoor) == 0xE90, "C_BaseDoor size should be 0xE90");

#endif
	}
}
