// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseModelEntity.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/client/BeamType_t.hpp>
#include <SDK/modellib/AttachmentHandle_t.hpp>
#include <SDK/client/BeamClipStyle_t.hpp>



namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeIMaterial2;
	}
	namespace client {
		class C_BaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_Beam : public CS2::client::C_BaseModelEntity {
		public:
			PROPERTY(m_flFrameRate,float32 , 0xeb0);
			PROPERTY(m_flHDRColorScale,float32 , 0xeb4);
			PROPERTY(m_flFireTime,entity2::GameTime_t , 0xeb8);
			PROPERTY(m_flDamage,float32 , 0xebc);
			PROPERTY(m_nNumBeamEnts,uint8_t , 0xec0);
			PROPERTY(m_queryHandleHalo,int32_t , 0xec4);
			PROPERTY(m_hBaseMaterial,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>, 0xee8);
			PROPERTY(m_nHaloIndex,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>, 0xef0);
			PROPERTY(m_nBeamType,client::BeamType_t , 0xef8);
			PROPERTY(m_nBeamFlags,uint32_t , 0xefc);
			PROPERTY_ARRAY(m_hAttachEntity,client::CHandle< C_BaseEntity >, 10 , 0xf00);
			PROPERTY_ARRAY(m_nAttachIndex,modellib::AttachmentHandle_t , 10 , 0xf28);
			PROPERTY(m_fWidth,float32 , 0xf34);
			PROPERTY(m_fEndWidth,float32 , 0xf38);
			PROPERTY(m_fFadeLength,float32 , 0xf3c);
			PROPERTY(m_fHaloScale,float32 , 0xf40);
			PROPERTY(m_fAmplitude,float32 , 0xf44);
			PROPERTY(m_fStartFrame,float32 , 0xf48);
			PROPERTY(m_fSpeed,float32 , 0xf4c);
			PROPERTY(m_flFrame,float32 , 0xf50);
			PROPERTY(m_nClipStyle,client::BeamClipStyle_t , 0xf54);
			PROPERTY(m_bTurnedOff,bool , 0xf58);
			PROPERTY(m_vecEndPos,GlobalTypes::VectorWS , 0xf5c);
			PROPERTY(m_hEndEntity,GlobalTypes::CHandle<client::C_BaseEntity>, 0xf68);
			S2_PAD(0xC0);
		};
		//static_assert(sizeof(CS2::client::C_Beam) == 0xF70, "C_Beam size should be 0xF70");
	}
}
