// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_BaseModelEntity.hpp"
#include "../entity2/GameTime_t.hpp"
#include "BeamType_t.hpp"
#include "CHandle< C_BaseEntity >.hpp"
#include "../modellib/AttachmentHandle_t.hpp"
#include "BeamClipStyle_t.hpp"



namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeIMaterial2;
	}
	namespace client {
		class C_BaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_Beam : public CS2::client::C_BaseModelEntity {
		public:
			PROPERTY(m_flFrameRate,float32, 0xe88);
			PROPERTY(m_flHDRColorScale,float32, 0xe8c);
			NESTED_PROPERTY(m_flFireTime,IDENTITY(entity2::GameTime_t), 0xe90);
			PROPERTY(m_flDamage,float32, 0xe94);
			PROPERTY(m_nNumBeamEnts,uint8_t, 0xe98);
			PROPERTY(m_queryHandleHalo,int32_t, 0xe9c);
			PROPERTY(m_hBaseMaterial,IDENTITY(GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>), 0xec0);
			PROPERTY(m_nHaloIndex,IDENTITY(GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>), 0xec8);
			PROPERTY(m_nBeamType,IDENTITY(client::BeamType_t), 0xed0);
			PROPERTY(m_nBeamFlags,uint32_t, 0xed4);
			// PROPERTY_ARRAY(m_hAttachEntity,IDENTITY(GlobalTypes::CHandle< C_BaseEntity >[10]), 10 , 0xed8);
			PROPERTY_ARRAY(m_nAttachIndex,IDENTITY(modellib::AttachmentHandle_t), 10 , 0xf00);
			PROPERTY(m_fWidth,float32, 0xf0c);
			PROPERTY(m_fEndWidth,float32, 0xf10);
			PROPERTY(m_fFadeLength,float32, 0xf14);
			PROPERTY(m_fHaloScale,float32, 0xf18);
			PROPERTY(m_fAmplitude,float32, 0xf1c);
			PROPERTY(m_fStartFrame,float32, 0xf20);
			PROPERTY(m_fSpeed,float32, 0xf24);
			PROPERTY(m_flFrame,float32, 0xf28);
			PROPERTY(m_nClipStyle,IDENTITY(client::BeamClipStyle_t), 0xf2c);
			PROPERTY(m_bTurnedOff,bool, 0xf30);
			PROPERTY(m_vecEndPos,GlobalTypes::VectorWS, 0xf34);
			PROPERTY(m_hEndEntity,IDENTITY(GlobalTypes::CHandle<client::C_BaseEntity>), 0xf40);
			S2_PAD(0xC0);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_Beam) == 0xF48, "C_Beam size should be 0xF48");

#endif
	}
}
