// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CBaseProp.hpp>
#include <SDK/client/CPropDataComponent.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>
#include <SDK/client/PerformanceMode_t.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/client/BreakableContentsType_t.hpp>



namespace CS2 {
	namespace client {
		class C_BaseEntity;
		class C_BasePlayerPawn;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_BreakableProp : public CS2::client::CBaseProp {
		public:
			PROPERTY(m_CPropDataComponent,client::CPropDataComponent , 0x1190);
			PROPERTY(m_OnStartDeath,entity2::CEntityIOOutput , 0x11d0);
			PROPERTY(m_OnBreak,entity2::CEntityIOOutput , 0x11f8);
			PROPERTY(m_OnHealthChanged,GlobalTypes::CEntityOutputTemplate< float32 >, 0x1220);
			PROPERTY(m_OnTakeDamage,entity2::CEntityIOOutput , 0x1248);
			PROPERTY(m_impactEnergyScale,float32 , 0x1270);
			PROPERTY(m_iMinHealthDmg,int32_t , 0x1274);
			PROPERTY(m_flPressureDelay,float32 , 0x1278);
			PROPERTY(m_flDefBurstScale,float32 , 0x127c);
			PROPERTY(m_vDefBurstOffset,GlobalTypes::Vector , 0x1280);
			PROPERTY(m_hBreaker,GlobalTypes::CHandle<client::C_BaseEntity>, 0x128c);
			PROPERTY(m_PerformanceMode,client::PerformanceMode_t , 0x1290);
			PROPERTY(m_flPreventDamageBeforeTime,entity2::GameTime_t , 0x1294);
			PROPERTY(m_BreakableContentsType,client::BreakableContentsType_t , 0x1298);
			PROPERTY(m_strBreakableContentsPropGroupOverride,GlobalTypes::CUtlString* , 0x12a0);
			PROPERTY(m_strBreakableContentsParticleOverride,GlobalTypes::CUtlString* , 0x12a8);
			PROPERTY(m_bHasBreakPiecesOrCommands,bool , 0x12b0);
			PROPERTY(m_explodeDamage,float32 , 0x12b4);
			PROPERTY(m_explodeRadius,float32 , 0x12b8);
			PROPERTY(m_explosionDelay,float32 , 0x12c0);
			PROPERTY(m_explosionBuildupSound,GlobalTypes::CUtlSymbolLarge* , 0x12c8);
			PROPERTY(m_explosionCustomEffect,GlobalTypes::CUtlSymbolLarge* , 0x12d0);
			PROPERTY(m_explosionCustomSound,GlobalTypes::CUtlSymbolLarge* , 0x12d8);
			PROPERTY(m_explosionModifier,GlobalTypes::CUtlSymbolLarge* , 0x12e0);
			PROPERTY(m_hPhysicsAttacker,GlobalTypes::CHandle<client::C_BasePlayerPawn>, 0x12e8);
			PROPERTY(m_flLastPhysicsInfluenceTime,entity2::GameTime_t , 0x12ec);
			PROPERTY(m_flDefaultFadeScale,float32 , 0x12f0);
			PROPERTY(m_hLastAttacker,GlobalTypes::CHandle<client::C_BaseEntity>, 0x12f4);
			S2_PAD(0x170);
		};
		//static_assert(sizeof(CS2::client::C_BreakableProp) == 0x1300, "C_BreakableProp size should be 0x1300");
	}
}
