// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_CSWeaponBase.hpp>
#include <SDK/client/ParticleIndex_t.hpp>
#include <SDK/client/C4LightEffect_t.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/client/EntitySpottedState_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_C4 : public CS2::client::C_CSWeaponBase {
		public:
			PROPERTY(m_activeLightParticleIndex,client::ParticleIndex_t , 0x1f80);
			PROPERTY(m_eActiveLightEffect,client::C4LightEffect_t , 0x1f84);
			PROPERTY(m_bStartedArming,bool , 0x1f88);
			PROPERTY(m_fArmedTime,entity2::GameTime_t , 0x1f8c);
			PROPERTY(m_bBombPlacedAnimation,bool , 0x1f90);
			PROPERTY(m_bIsPlantingViaUse,bool , 0x1f91);
			PROPERTY(m_entitySpottedState,client::EntitySpottedState_t , 0x1f98);
			PROPERTY(m_nSpotRules,int32_t , 0x1fb0);
			PROPERTY_ARRAY(m_bPlayedArmingBeeps,bool , 7 , 0x1fb4);
			PROPERTY(m_bBombPlanted,bool , 0x1fbb);
			S2_PAD(0x40);
		};
		//static_assert(sizeof(CS2::client::C_C4) == 0x1FC0, "C_C4 size should be 0x1FC0");
	}
}
