// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_DynamicProp.hpp>
#include <SDK/client/C_AttributeContainer.hpp>
#include <SDK/client/ParticleIndex_t.hpp>



namespace CS2 {
	namespace client {
		class CBaseAnimGraph;
		class C_CSPlayerPawn;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_Chicken : public CS2::client::C_DynamicProp {
		public:
			PROPERTY(m_hHolidayHatAddon,GlobalTypes::CHandle<client::CBaseAnimGraph>, 0x1428);
			PROPERTY(m_jumpedThisFrame,bool , 0x142c);
			PROPERTY(m_leader,GlobalTypes::CHandle<client::C_CSPlayerPawn>, 0x1430);
			PROPERTY(m_AttributeManager,client::C_AttributeContainer , 0x1438);
			PROPERTY(m_bAttributesInitialized,bool , 0x1910);
			PROPERTY(m_hWaterWakeParticles,client::ParticleIndex_t , 0x1914);
			PROPERTY(m_bIsPreviewModel,bool , 0x1918);
			S2_PAD(0x510);
		};
		//static_assert(sizeof(CS2::client::C_Chicken) == 0x1930, "C_Chicken size should be 0x1930");
	}
}
