// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseTrigger.hpp>
#include <SDK/entity2/GameTime_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_ColorCorrectionVolume : public CS2::client::C_BaseTrigger {
		public:
			PROPERTY(m_LastEnterWeight,float32 , 0xff0);
			PROPERTY(m_LastEnterTime,entity2::GameTime_t , 0xff4);
			PROPERTY(m_LastExitWeight,float32 , 0xff8);
			PROPERTY(m_LastExitTime,entity2::GameTime_t , 0xffc);
			PROPERTY(m_bEnabled,bool , 0x1000);
			PROPERTY(m_MaxWeight,float32 , 0x1004);
			PROPERTY(m_FadeDuration,float32 , 0x1008);
			PROPERTY(m_Weight,float32 , 0x100c);
			PROPERTY_ARRAY(m_lookupFilename,char , 512 , 0x1010);
			S2_PAD(0x228);
		};
		//static_assert(sizeof(CS2::client::C_ColorCorrectionVolume) == 0x1218, "C_ColorCorrectionVolume size should be 0x1218");
	}
}
