// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_CSPlayerPawn.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_CSGO_PreviewPlayer : public CS2::client::C_CSPlayerPawn {
		public:
			PROPERTY(m_animgraphCharacterModeString,GlobalTypes::CGlobalSymbol, 0x3ef0);
			PROPERTY(m_flInitialModelScale,float32, 0x3ef8);
			S2_PAD(0xB0);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_CSGO_PreviewPlayer) == 0x3FA0, "C_CSGO_PreviewPlayer size should be 0x3FA0");

#endif
	}
}
