// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_CSPlayerPawnBase.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_CSObserverPawn : public CS2::client::C_CSPlayerPawnBase {
		public:
			PROPERTY(m_hDetectParentChange,GlobalTypes::CEntityHandle, 0x1650);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_CSObserverPawn) == 0x1658, "C_CSObserverPawn size should be 0x1658");

#endif
	}
}
