// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_CSGO_MapPreviewCameraPath.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_CSGO_TeamPreviewCamera : public CS2::client::C_CSGO_MapPreviewCameraPath {
		public:
			PROPERTY(m_nVariant,int32_t, 0x690);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_CSGO_TeamPreviewCamera) == 0x698, "C_CSGO_TeamPreviewCamera size should be 0x698");

#endif
	}
}
