// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseCSGrenadeProjectile.hpp>
#include <SDK/entity2/GameTime_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_DecoyProjectile : public CS2::client::C_BaseCSGrenadeProjectile {
		public:
			PROPERTY(m_nDecoyShotTick,int32_t , 0x1450);
			PROPERTY(m_nClientLastKnownDecoyShotTick,int32_t , 0x1454);
			PROPERTY(m_flTimeParticleEffectSpawn,entity2::GameTime_t , 0x1478);
			S2_PAD(0x30);
		};
		//static_assert(sizeof(CS2::client::C_DecoyProjectile) == 0x1480, "C_DecoyProjectile size should be 0x1480");
	}
}
