// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_BaseCSGrenadeProjectile.hpp"
#include "../entity2/GameTime_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_DecoyProjectile : public CS2::client::C_BaseCSGrenadeProjectile {
		public:
			PROPERTY(m_nDecoyShotTick,int32_t, 0x1438);
			PROPERTY(m_nClientLastKnownDecoyShotTick,int32_t, 0x143c);
			NESTED_PROPERTY(m_flTimeParticleEffectSpawn,IDENTITY(entity2::GameTime_t), 0x1460);
			S2_PAD(0x30);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_DecoyProjectile) == 0x1468, "C_DecoyProjectile size should be 0x1468");

#endif
	}
}
