// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_EconEntity.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_EconWearable : public CS2::client::C_EconEntity {
		public:
			PROPERTY(m_nForceSkin,int32_t, 0x18c0);
			PROPERTY(m_bAlwaysAllow,bool, 0x18c4);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_EconWearable) == 0x18C8, "C_EconWearable size should be 0x18C8");

#endif
	}
}
