// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/IEconItemInterface.hpp>
#include <SDK/client/CAttributeList.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_EconItemView : public CS2::client::IEconItemInterface {
		public:
			PROPERTY(m_bInventoryImageRgbaRequested,bool , 0x60);
			PROPERTY(m_bInventoryImageTriedCache,bool , 0x61);
			PROPERTY(m_nInventoryImageRgbaWidth,int32_t , 0x80);
			PROPERTY(m_nInventoryImageRgbaHeight,int32_t , 0x84);
			PROPERTY_ARRAY(m_szCurrentLoadCachedFileName,char , 260 , 0x88);
			PROPERTY(m_bRestoreCustomMaterialAfterPrecache,bool , 0x1b8);
			PROPERTY(m_iItemDefinitionIndex,uint16_t , 0x1ba);
			PROPERTY(m_iEntityQuality,int32_t , 0x1bc);
			PROPERTY(m_iEntityLevel,uint32_t , 0x1c0);
			PROPERTY(m_iItemID,uint64_t , 0x1c8);
			PROPERTY(m_iItemIDHigh,uint32_t , 0x1d0);
			PROPERTY(m_iItemIDLow,uint32_t , 0x1d4);
			PROPERTY(m_iAccountID,uint32_t , 0x1d8);
			PROPERTY(m_iInventoryPosition,uint32_t , 0x1dc);
			PROPERTY(m_bInitialized,bool , 0x1e8);
			PROPERTY(m_bDisallowSOC,bool , 0x1e9);
			PROPERTY(m_bIsStoreItem,bool , 0x1ea);
			PROPERTY(m_bIsTradeItem,bool , 0x1eb);
			PROPERTY(m_iEntityQuantity,int32_t , 0x1ec);
			PROPERTY(m_iRarityOverride,int32_t , 0x1f0);
			PROPERTY(m_iQualityOverride,int32_t , 0x1f4);
			PROPERTY(m_iOriginOverride,int32_t , 0x1f8);
			PROPERTY(m_ubStyleOverride,uint8_t , 0x1fc);
			PROPERTY(m_unClientFlags,uint8_t , 0x1fd);
			PROPERTY(m_AttributeList,client::CAttributeList , 0x210);
			PROPERTY(m_NetworkedDynamicAttributes,client::CAttributeList , 0x288);
			PROPERTY_ARRAY(m_szCustomName,char , 161 , 0x300);
			PROPERTY_ARRAY(m_szCustomNameOverride,char , 161 , 0x3a1);
			PROPERTY(m_bInitializedTags,bool , 0x470);
			S2_PAD(0x470);
		};
		//static_assert(sizeof(CS2::client::C_EconItemView) == 0x478, "C_EconItemView size should be 0x478");
	}
}
