// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseModelEntity.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/client/EntityDisolveType_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_EntityDissolve : public CS2::client::C_BaseModelEntity {
		public:
			PROPERTY(m_flStartTime,entity2::GameTime_t , 0xeb8);
			PROPERTY(m_flFadeInStart,float32 , 0xebc);
			PROPERTY(m_flFadeInLength,float32 , 0xec0);
			PROPERTY(m_flFadeOutModelStart,float32 , 0xec4);
			PROPERTY(m_flFadeOutModelLength,float32 , 0xec8);
			PROPERTY(m_flFadeOutStart,float32 , 0xecc);
			PROPERTY(m_flFadeOutLength,float32 , 0xed0);
			PROPERTY(m_flNextSparkTime,entity2::GameTime_t , 0xed4);
			PROPERTY(m_nDissolveType,client::EntityDisolveType_t , 0xed8);
			PROPERTY(m_vDissolverOrigin,GlobalTypes::Vector , 0xedc);
			PROPERTY(m_nMagnitude,uint32_t , 0xee8);
			PROPERTY(m_bCoreExplode,bool , 0xeec);
			PROPERTY(m_bLinkedToServerEnt,bool , 0xeed);
			S2_PAD(0x48);
		};
		//static_assert(sizeof(CS2::client::C_EntityDissolve) == 0xEF8, "C_EntityDissolve size should be 0xEF8");
	}
}
