// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseEntity.hpp>
#include <SDK/client/C_EnvWindShared.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_EnvWindController : public CS2::client::C_BaseEntity {
		public:
			PROPERTY(m_EnvWindShared,client::C_EnvWindShared , 0x5f8);
			PROPERTY(m_fDirectionVariation,float32 , 0x6f0);
			PROPERTY(m_fSpeedVariation,float32 , 0x6f4);
			PROPERTY(m_fTurbulence,float32 , 0x6f8);
			PROPERTY(m_fVolumeHalfExtentXY,float32 , 0x6fc);
			PROPERTY(m_fVolumeHalfExtentZ,float32 , 0x700);
			PROPERTY(m_nVolumeResolutionXY,int32_t , 0x704);
			PROPERTY(m_nVolumeResolutionZ,int32_t , 0x708);
			PROPERTY(m_nClipmapLevels,int32_t , 0x70c);
			PROPERTY(m_bIsMaster,bool , 0x710);
			PROPERTY(m_bFirstTime,bool , 0x711);
			S2_PAD(0x120);
		};
		//static_assert(sizeof(CS2::client::C_EnvWindController) == 0x718, "C_EnvWindController size should be 0x718");
	}
}
