// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_ParticleSystem.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_EnvParticleGlow : public CS2::client::C_ParticleSystem {
		public:
			PROPERTY(m_flAlphaScale,float32 , 0x1460);
			PROPERTY(m_flRadiusScale,float32 , 0x1464);
			PROPERTY(m_flSelfIllumScale,float32 , 0x1468);
			PROPERTY(m_ColorTint,GlobalTypes::Color , 0x146c);
			PROPERTY(m_hTextureOverride,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCTextureBase>, 0x1470);
			S2_PAD(0x18);
		};
		//static_assert(sizeof(CS2::client::C_EnvParticleGlow) == 0x1478, "C_EnvParticleGlow size should be 0x1478");
	}
}
