// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_EnvVolumetricFogVolume : public CS2::client::C_BaseEntity {
		public:
			PROPERTY(m_bActive,bool , 0x5f8);
			PROPERTY(m_vBoxMins,GlobalTypes::Vector , 0x5fc);
			PROPERTY(m_vBoxMaxs,GlobalTypes::Vector , 0x608);
			PROPERTY(m_bStartDisabled,bool , 0x614);
			PROPERTY(m_bIndirectUseLPVs,bool , 0x615);
			PROPERTY(m_flStrength,float32 , 0x618);
			PROPERTY(m_nFalloffShape,int32_t , 0x61c);
			PROPERTY(m_flFalloffExponent,float32 , 0x620);
			PROPERTY(m_flHeightFogDepth,float32 , 0x624);
			PROPERTY(m_fHeightFogEdgeWidth,float32 , 0x628);
			PROPERTY(m_fIndirectLightStrength,float32 , 0x62c);
			PROPERTY(m_fSunLightStrength,float32 , 0x630);
			PROPERTY(m_fNoiseStrength,float32 , 0x634);
			PROPERTY(m_TintColor,GlobalTypes::Color , 0x638);
			PROPERTY(m_bOverrideTintColor,bool , 0x63c);
			PROPERTY(m_bOverrideIndirectLightStrength,bool , 0x63d);
			PROPERTY(m_bOverrideSunLightStrength,bool , 0x63e);
			PROPERTY(m_bOverrideNoiseStrength,bool , 0x63f);
			S2_PAD(0x48);
		};
		//static_assert(sizeof(CS2::client::C_EnvVolumetricFogVolume) == 0x640, "C_EnvVolumetricFogVolume size should be 0x640");
	}
}
