// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseModelEntity.hpp>
#include <SDK/client/C_InfoLadderDismount.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_FuncLadder : public CS2::client::C_BaseModelEntity {
		public:
			PROPERTY(m_vecLadderDir,GlobalTypes::Vector , 0xeb0);
			PROPERTY(m_Dismounts,GlobalTypes::CUtlVector<GlobalTypes::CHandle<client::C_InfoLadderDismount>>, 0xec0);
			PROPERTY(m_vecLocalTop,GlobalTypes::Vector , 0xed8);
			PROPERTY(m_vecPlayerMountPositionTop,GlobalTypes::VectorWS , 0xee4);
			PROPERTY(m_vecPlayerMountPositionBottom,GlobalTypes::VectorWS , 0xef0);
			PROPERTY(m_flAutoRideSpeed,float32 , 0xefc);
			PROPERTY(m_bDisabled,bool , 0xf00);
			PROPERTY(m_bFakeLadder,bool , 0xf01);
			PROPERTY(m_bHasSlack,bool , 0xf02);
			S2_PAD(0x58);
		};
		//static_assert(sizeof(CS2::client::C_FuncLadder) == 0xF08, "C_FuncLadder size should be 0xF08");
	}
}
