// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_FuncBrush.hpp>
#include <SDK/client/ParticleIndex_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_FuncElectrifiedVolume : public CS2::client::C_FuncBrush {
		public:
			PROPERTY(m_nAmbientEffect,client::ParticleIndex_t , 0xeb0);
			PROPERTY(m_EffectName,GlobalTypes::CUtlSymbolLarge* , 0xeb8);
			PROPERTY(m_bState,bool , 0xec0);
			S2_PAD(0x18);
		};
		//static_assert(sizeof(CS2::client::C_FuncElectrifiedVolume) == 0xEC8, "C_FuncElectrifiedVolume size should be 0xEC8");
	}
}
