// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_Item.hpp"



namespace CS2 {
	namespace client {
		class C_CSPlayerPawn;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_ItemDogtags : public CS2::client::C_Item {
		public:
			PROPERTY(m_OwningPlayer,IDENTITY(GlobalTypes::CHandle<client::C_CSPlayerPawn>), 0x19c0);
			PROPERTY(m_KillingPlayer,IDENTITY(GlobalTypes::CHandle<client::C_CSPlayerPawn>), 0x19c4);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_ItemDogtags) == 0x19C8, "C_ItemDogtags size should be 0x19C8");

#endif
	}
}
