// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_BaseCSGrenadeProjectile.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_MolotovProjectile : public CS2::client::C_BaseCSGrenadeProjectile {
		public:
			PROPERTY(m_bIsIncGrenade,bool, 0x1438);
			S2_PAD(0x28);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_MolotovProjectile) == 0x1460, "C_MolotovProjectile size should be 0x1460");

#endif
	}
}
