// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BreakableProp.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/client/DamageTypes_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_PhysPropClientside : public CS2::client::C_BreakableProp {
		public:
			PROPERTY(m_flTouchDelta,entity2::GameTime_t , 0x1300);
			PROPERTY(m_fDeathTime,entity2::GameTime_t , 0x1304);
			PROPERTY(m_vecDamagePosition,GlobalTypes::Vector , 0x1308);
			PROPERTY(m_vecDamageDirection,GlobalTypes::Vector , 0x1314);
			PROPERTY(m_nDamageType,client::DamageTypes_t , 0x1320);
			S2_PAD(0x30);
		};
		//static_assert(sizeof(CS2::client::C_PhysPropClientside) == 0x1330, "C_PhysPropClientside size should be 0x1330");
	}
}
