// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_BaseEntity.hpp"



namespace CS2 {
	namespace client {
		class C_CSPlayerPawn;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_PlayerPing : public CS2::client::C_BaseEntity {
		public:
			PROPERTY(m_hPlayer,IDENTITY(GlobalTypes::CHandle<client::C_CSPlayerPawn>), 0x638);
			PROPERTY(m_hPingedEntity,IDENTITY(GlobalTypes::CHandle<client::C_BaseEntity>), 0x63c);
			PROPERTY(m_iType,int32_t, 0x640);
			PROPERTY(m_bUrgent,bool, 0x644);
			PROPERTY_ARRAY(m_szPlaceName,char, 18 , 0x645);
			S2_PAD(0x50);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_PlayerPing) == 0x658, "C_PlayerPing size should be 0x658");

#endif
	}
}
