// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseEntity.hpp>



namespace CS2 {
	namespace client {
		class C_CSPlayerPawn;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_PlayerPing : public CS2::client::C_BaseEntity {
		public:
			PROPERTY(m_hPlayer,GlobalTypes::CHandle<client::C_CSPlayerPawn>, 0x628);
			PROPERTY(m_hPingedEntity,GlobalTypes::CHandle<client::C_BaseEntity>, 0x62c);
			PROPERTY(m_iType,int32_t , 0x630);
			PROPERTY(m_bUrgent,bool , 0x634);
			PROPERTY_ARRAY(m_szPlaceName,char , 18 , 0x635);
			S2_PAD(0x50);
		};
		//static_assert(sizeof(CS2::client::C_PlayerPing) == 0x648, "C_PlayerPing size should be 0x648");
	}
}
