// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseClientUIEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_PointClientUIHUD : public CS2::client::C_BaseClientUIEntity {
		public:
			PROPERTY(m_bCheckCSSClasses,bool , 0xee8);
			PROPERTY(m_bIgnoreInput,bool , 0x1060);
			PROPERTY(m_flWidth,float32 , 0x1064);
			PROPERTY(m_flHeight,float32 , 0x1068);
			PROPERTY(m_flDPI,float32 , 0x106c);
			PROPERTY(m_flInteractDistance,float32 , 0x1070);
			PROPERTY(m_flDepthOffset,float32 , 0x1074);
			PROPERTY(m_unOwnerContext,uint32_t , 0x1078);
			PROPERTY(m_unHorizontalAlign,uint32_t , 0x107c);
			PROPERTY(m_unVerticalAlign,uint32_t , 0x1080);
			PROPERTY(m_unOrientation,uint32_t , 0x1084);
			PROPERTY(m_bAllowInteractionFromAllSceneWorlds,bool , 0x1088);
			PROPERTY(m_vecCSSClasses,GlobalTypes::C_NetworkUtlVectorBase<GlobalTypes::CUtlSymbolLarge>, 0x1090);
			S2_PAD(0x1C8);
		};
		//static_assert(sizeof(CS2::client::C_PointClientUIHUD) == 0x10A8, "C_PointClientUIHUD size should be 0x10A8");
	}
}
