// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseEntity.hpp>
#include <SDK/client/ValueRemapperInputType_t.hpp>
#include <SDK/client/ValueRemapperOutputType_t.hpp>
#include <SDK/client/ValueRemapperHapticsType_t.hpp>
#include <SDK/client/ValueRemapperMomentumType_t.hpp>
#include <SDK/client/ValueRemapperRatchetType_t.hpp>
#include <SDK/entity2/GameTime_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_PointValueRemapper : public CS2::client::C_BaseEntity {
		public:
			PROPERTY(m_bDisabled,bool , 0x5f8);
			PROPERTY(m_bDisabledOld,bool , 0x5f9);
			PROPERTY(m_bUpdateOnClient,bool , 0x5fa);
			PROPERTY(m_nInputType,client::ValueRemapperInputType_t , 0x5fc);
			PROPERTY(m_hRemapLineStart,GlobalTypes::CHandle<client::C_BaseEntity>, 0x600);
			PROPERTY(m_hRemapLineEnd,GlobalTypes::CHandle<client::C_BaseEntity>, 0x604);
			PROPERTY(m_flMaximumChangePerSecond,float32 , 0x608);
			PROPERTY(m_flDisengageDistance,float32 , 0x60c);
			PROPERTY(m_flEngageDistance,float32 , 0x610);
			PROPERTY(m_bRequiresUseKey,bool , 0x614);
			PROPERTY(m_nOutputType,client::ValueRemapperOutputType_t , 0x618);
			PROPERTY(m_hOutputEntities,GlobalTypes::C_NetworkUtlVectorBase<GlobalTypes::CHandle<client::C_BaseEntity>>, 0x620);
			PROPERTY(m_nHapticsType,client::ValueRemapperHapticsType_t , 0x638);
			PROPERTY(m_nMomentumType,client::ValueRemapperMomentumType_t , 0x63c);
			PROPERTY(m_flMomentumModifier,float32 , 0x640);
			PROPERTY(m_flSnapValue,float32 , 0x644);
			PROPERTY(m_flCurrentMomentum,float32 , 0x648);
			PROPERTY(m_nRatchetType,client::ValueRemapperRatchetType_t , 0x64c);
			PROPERTY(m_flRatchetOffset,float32 , 0x650);
			PROPERTY(m_flInputOffset,float32 , 0x654);
			PROPERTY(m_bEngaged,bool , 0x658);
			PROPERTY(m_bFirstUpdate,bool , 0x659);
			PROPERTY(m_flPreviousValue,float32 , 0x65c);
			PROPERTY(m_flPreviousUpdateTickTime,entity2::GameTime_t , 0x660);
			PROPERTY(m_vecPreviousTestPoint,GlobalTypes::Vector , 0x664);
			S2_PAD(0x78);
		};
		//static_assert(sizeof(CS2::client::C_PointValueRemapper) == 0x670, "C_PointValueRemapper size should be 0x670");
	}
}
