// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseModelEntity.hpp>
#include <SDK/modellib/AttachmentHandle_t.hpp>
#include <SDK/client/CPhysicsDelegate.hpp>



namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeIMaterial2;
	}
	namespace client {
		class C_BaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_RopeKeyframe : public CS2::client::C_BaseModelEntity {
		public:
			PROPERTY(m_LinksTouchingSomething,GlobalTypes::CBitVec< 10 >, 0xeb8);
			PROPERTY(m_nLinksTouchingSomething,int32_t , 0xebc);
			PROPERTY(m_bApplyWind,bool , 0xec0);
			PROPERTY(m_fPrevLockedPoints,int32_t , 0xec4);
			PROPERTY(m_iForcePointMoveCounter,int32_t , 0xec8);
			PROPERTY_ARRAY(m_bPrevEndPointPos,bool , 2 , 0xecc);
			PROPERTY_ARRAY(m_vPrevEndPointPos,GlobalTypes::Vector , 2 , 0xed0);
			PROPERTY(m_flCurScroll,float32 , 0xee8);
			PROPERTY(m_flScrollSpeed,float32 , 0xeec);
			PROPERTY(m_RopeFlags,uint16_t , 0xef0);
			PROPERTY(m_iRopeMaterialModelIndex,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>, 0xef8);
			PROPERTY(m_nSegments,uint8_t , 0x1170);
			PROPERTY(m_hStartPoint,GlobalTypes::CHandle<client::C_BaseEntity>, 0x1174);
			PROPERTY(m_hEndPoint,GlobalTypes::CHandle<client::C_BaseEntity>, 0x1178);
			PROPERTY(m_iStartAttachment,modellib::AttachmentHandle_t , 0x117c);
			PROPERTY(m_iEndAttachment,modellib::AttachmentHandle_t , 0x117d);
			PROPERTY(m_Subdiv,uint8_t , 0x117e);
			PROPERTY(m_RopeLength,int16_t , 0x1180);
			PROPERTY(m_Slack,int16_t , 0x1182);
			PROPERTY(m_TextureScale,float32 , 0x1184);
			PROPERTY(m_fLockedPoints,uint8_t , 0x1188);
			PROPERTY(m_nChangeCount,uint8_t , 0x1189);
			PROPERTY(m_Width,float32 , 0x118c);
			PROPERTY(m_PhysicsDelegate,client::CPhysicsDelegate , 0x1190);
			PROPERTY(m_hMaterial,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>, 0x11a0);
			PROPERTY(m_TextureHeight,int32_t , 0x11a8);
			PROPERTY(m_vecImpulse,GlobalTypes::Vector , 0x11ac);
			PROPERTY(m_vecPreviousImpulse,GlobalTypes::Vector , 0x11b8);
			PROPERTY(m_flCurrentGustTimer,float32 , 0x11c4);
			PROPERTY(m_flCurrentGustLifetime,float32 , 0x11c8);
			PROPERTY(m_flTimeToNextGust,float32 , 0x11cc);
			PROPERTY(m_vWindDir,GlobalTypes::Vector , 0x11d0);
			PROPERTY(m_vColorMod,GlobalTypes::Vector , 0x11dc);
			PROPERTY_ARRAY(m_vCachedEndPointAttachmentPos,GlobalTypes::Vector , 2 , 0x11e8);
			PROPERTY_ARRAY(m_vCachedEndPointAttachmentAngle,GlobalTypes::QAngle , 2 , 0x1200);
			PROPERTY(m_bConstrainBetweenEndpoints,bool , 0x1218);
			S2_PAD(0x370);
		};
		//static_assert(sizeof(CS2::client::C_RopeKeyframe) == 0x1220, "C_RopeKeyframe size should be 0x1220");
	}
}
