// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseCSGrenadeProjectile.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_SmokeGrenadeProjectile : public CS2::client::C_BaseCSGrenadeProjectile {
		public:
			PROPERTY(m_nSmokeEffectTickBegin,int32_t , 0x1468);
			PROPERTY(m_bDidSmokeEffect,bool , 0x146c);
			PROPERTY(m_nRandomSeed,int32_t , 0x1470);
			PROPERTY(m_vSmokeColor,GlobalTypes::Vector , 0x1474);
			PROPERTY(m_vSmokeDetonationPos,GlobalTypes::Vector , 0x1480);
			PROPERTY(m_VoxelFrameData,GlobalTypes::C_NetworkUtlVectorBase< uint8 >, 0x1490);
			PROPERTY(m_nVoxelFrameDataSize,int32_t , 0x14a8);
			PROPERTY(m_nVoxelUpdate,int32_t , 0x14ac);
			PROPERTY(m_bSmokeVolumeDataReceived,bool , 0x14b0);
			PROPERTY(m_bSmokeEffectSpawned,bool , 0x14b1);
			S2_PAD(0x1B8);
		};
		//static_assert(sizeof(CS2::client::C_SmokeGrenadeProjectile) == 0x1608, "C_SmokeGrenadeProjectile size should be 0x1608");
	}
}
