// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_SoundEventEntity : public CS2::client::C_BaseEntity {
		public:
			PROPERTY(m_bStartOnSpawn,bool , 0x5f8);
			PROPERTY(m_bToLocalPlayer,bool , 0x5f9);
			PROPERTY(m_bStopOnNew,bool , 0x5fa);
			PROPERTY(m_bSaveRestore,bool , 0x5fb);
			PROPERTY(m_bSavedIsPlaying,bool , 0x5fc);
			PROPERTY(m_flSavedElapsedTime,float32 , 0x600);
			PROPERTY(m_iszSourceEntityName,GlobalTypes::CUtlSymbolLarge* , 0x608);
			PROPERTY(m_iszAttachmentName,GlobalTypes::CUtlSymbolLarge* , 0x610);
			PROPERTY(m_onGUIDChanged,GlobalTypes::CEntityOutputTemplate< uint64 >, 0x618);
			PROPERTY(m_onSoundFinished,entity2::CEntityIOOutput , 0x640);
			PROPERTY(m_flClientCullRadius,float32 , 0x668);
			PROPERTY(m_iszSoundName,GlobalTypes::CUtlSymbolLarge* , 0x698);
			PROPERTY(m_hSource,GlobalTypes::CEntityHandle , 0x6b4);
			PROPERTY(m_nEntityIndexSelection,int32_t , 0x6b8);
			S2_PAD(0xC8);
		};
		//static_assert(sizeof(CS2::client::C_SoundEventEntity) == 0x6C0, "C_SoundEventEntity size should be 0x6C0");
	}
}
