// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_SoundOpvarSetPointBase : public CS2::client::C_BaseEntity {
		public:
			PROPERTY(m_iszStackName,GlobalTypes::CUtlSymbolLarge* , 0x5f8);
			PROPERTY(m_iszOperatorName,GlobalTypes::CUtlSymbolLarge* , 0x600);
			PROPERTY(m_iszOpvarName,GlobalTypes::CUtlSymbolLarge* , 0x608);
			PROPERTY(m_iOpvarIndex,int32_t , 0x610);
			PROPERTY(m_bUseAutoCompare,bool , 0x614);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::client::C_SoundOpvarSetPointBase) == 0x618, "C_SoundOpvarSetPointBase size should be 0x618");
	}
}
