// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_SoundAreaEntityBase.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_SoundAreaEntitySphere : public CS2::client::C_SoundAreaEntityBase {
		public:
			PROPERTY(m_flRadius,float32, 0x630);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_SoundAreaEntitySphere) == 0x638, "C_SoundAreaEntitySphere size should be 0x638");

#endif
	}
}
