// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseModelEntity.hpp>
#include <SDK/modellib/AttachmentHandle_t.hpp>
#include <SDK/entity2/GameTime_t.hpp>



namespace CS2 {
	namespace client {
		class C_BaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_Sprite : public CS2::client::C_BaseModelEntity {
		public:
			PROPERTY(m_hSpriteMaterial,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>, 0xeb0);
			PROPERTY(m_hAttachedToEntity,GlobalTypes::CHandle<client::C_BaseEntity>, 0xeb8);
			PROPERTY(m_nAttachment,modellib::AttachmentHandle_t , 0xebc);
			PROPERTY(m_flSpriteFramerate,float32 , 0xec0);
			PROPERTY(m_flFrame,float32 , 0xec4);
			PROPERTY(m_flDieTime,entity2::GameTime_t , 0xec8);
			PROPERTY(m_nBrightness,uint32_t , 0xed8);
			PROPERTY(m_flBrightnessDuration,float32 , 0xedc);
			PROPERTY(m_flSpriteScale,float32 , 0xee0);
			PROPERTY(m_flScaleDuration,float32 , 0xee4);
			PROPERTY(m_bWorldSpaceScale,bool , 0xee8);
			PROPERTY(m_flGlowProxySize,float32 , 0xeec);
			PROPERTY(m_flHDRColorScale,float32 , 0xef0);
			PROPERTY(m_flLastTime,entity2::GameTime_t , 0xef4);
			PROPERTY(m_flMaxFrame,float32 , 0xef8);
			PROPERTY(m_flStartScale,float32 , 0xefc);
			PROPERTY(m_flDestScale,float32 , 0xf00);
			PROPERTY(m_flScaleTimeStart,entity2::GameTime_t , 0xf04);
			PROPERTY(m_nStartBrightness,int32_t , 0xf08);
			PROPERTY(m_nDestBrightness,int32_t , 0xf0c);
			PROPERTY(m_flBrightnessTimeStart,entity2::GameTime_t , 0xf10);
			PROPERTY(m_nSpriteWidth,int32_t , 0xf20);
			PROPERTY(m_nSpriteHeight,int32_t , 0xf24);
			S2_PAD(0x78);
		};
		//static_assert(sizeof(CS2::client::C_Sprite) == 0xF28, "C_Sprite size should be 0xF28");
	}
}
