// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_TonemapController2 : public CS2::client::C_BaseEntity {
		public:
			PROPERTY(m_flAutoExposureMin,float32 , 0x5f8);
			PROPERTY(m_flAutoExposureMax,float32 , 0x5fc);
			PROPERTY(m_flExposureAdaptationSpeedUp,float32 , 0x600);
			PROPERTY(m_flExposureAdaptationSpeedDown,float32 , 0x604);
			PROPERTY(m_flTonemapEVSmoothingRange,float32 , 0x608);
			S2_PAD(0x18);
		};
		//static_assert(sizeof(CS2::client::C_TonemapController2) == 0x610, "C_TonemapController2 size should be 0x610");
	}
}
