// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseTrigger.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_TriggerPhysics : public CS2::client::C_BaseTrigger {
		public:
			PROPERTY(m_gravityScale,float32 , 0xff0);
			PROPERTY(m_linearLimit,float32 , 0xff4);
			PROPERTY(m_linearDamping,float32 , 0xff8);
			PROPERTY(m_angularLimit,float32 , 0xffc);
			PROPERTY(m_angularDamping,float32 , 0x1000);
			PROPERTY(m_linearForce,float32 , 0x1004);
			PROPERTY(m_flFrequency,float32 , 0x1008);
			PROPERTY(m_flDampingRatio,float32 , 0x100c);
			PROPERTY(m_vecLinearForcePointAt,GlobalTypes::Vector , 0x1010);
			PROPERTY(m_bCollapseToForcePoint,bool , 0x101c);
			PROPERTY(m_vecLinearForcePointAtWorld,GlobalTypes::Vector , 0x1020);
			PROPERTY(m_vecLinearForceDirection,GlobalTypes::Vector , 0x102c);
			PROPERTY(m_bConvertToDebrisWhenPossible,bool , 0x1038);
			S2_PAD(0x50);
		};
		//static_assert(sizeof(CS2::client::C_TriggerPhysics) == 0x1040, "C_TriggerPhysics size should be 0x1040");
	}
}
