// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_BaseTrigger.hpp"
#include "CBuoyancyHelper.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_TriggerBuoyancy : public CS2::client::C_BaseTrigger {
		public:
			NESTED_PROPERTY(m_BuoyancyHelper,IDENTITY(client::CBuoyancyHelper), 0xf58);
			PROPERTY(m_flFluidDensity,float32, 0x1070);
			S2_PAD(0x120);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::C_TriggerBuoyancy) == 0x1078, "C_TriggerBuoyancy size should be 0x1078");

#endif
	}
}
