// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "ExternalAnimGraphHandle_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CAnimGraphControllerBase  {
		public:
			NESTED_PROPERTY(m_hExternalGraph,IDENTITY(client::ExternalAnimGraphHandle_t), 0x18);
			S2_PAD(0x90);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::CAnimGraphControllerBase) == 0x90, "CAnimGraphControllerBase size should be 0x90");

#endif
	}
}
