// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CLogicalEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CBaseFilter : public CS2::client::CLogicalEntity {
		public:
			PROPERTY(m_bNegated,bool , 0x5f8);
			PROPERTY(m_OnPass,entity2::CEntityIOOutput , 0x600);
			PROPERTY(m_OnFail,entity2::CEntityIOOutput , 0x628);
			S2_PAD(0x58);
		};
		//static_assert(sizeof(CS2::client::CBaseFilter) == 0x650, "CBaseFilter size should be 0x650");
	}
}
