// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CBodyComponent.hpp"
#include "CSkeletonInstance.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CBodyComponentSkeletonInstance : public CS2::client::CBodyComponent {
		public:
			NESTED_PROPERTY(m_skeletonInstance,IDENTITY(client::CSkeletonInstance), 0x80);
			S2_PAD(0x4D8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::CBodyComponentSkeletonInstance) == 0x550, "CBodyComponentSkeletonInstance size should be 0x550");

#endif
	}
}
