// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_BaseTrigger.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CBombTarget : public CS2::client::C_BaseTrigger {
		public:
			PROPERTY(m_bBombPlantedHere,bool, 0xf58);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::CBombTarget) == 0xF60, "CBombTarget size should be 0xF60");

#endif
	}
}
