// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CPlayerPawnComponent.hpp>
#include <SDK/client/WeaponPurchaseTracker_t.hpp>



namespace CS2 {
	namespace client {
		class C_BasePlayerWeapon;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CCSPlayer_ActionTrackingServices : public CS2::client::CPlayerPawnComponent {
		public:
			PROPERTY(m_hLastWeaponBeforeC4AutoSwitch,GlobalTypes::CHandle<client::C_BasePlayerWeapon>, 0x40);
			PROPERTY(m_bIsRescuing,bool , 0x44);
			PROPERTY(m_weaponPurchasesThisMatch,client::WeaponPurchaseTracker_t , 0x48);
			PROPERTY(m_weaponPurchasesThisRound,client::WeaponPurchaseTracker_t , 0xb8);
			S2_PAD(0xE8);
		};
		//static_assert(sizeof(CS2::client::CCSPlayer_ActionTrackingServices) == 0x128, "CCSPlayer_ActionTrackingServices size should be 0x128");
	}
}
