// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_PointEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CInfoOffscreenPanoramaTexture : public CS2::client::C_PointEntity {
		public:
			PROPERTY(m_bDisabled,bool , 0x5f8);
			PROPERTY(m_nResolutionX,int32_t , 0x5fc);
			PROPERTY(m_nResolutionY,int32_t , 0x600);
			PROPERTY(m_szLayoutFileName,GlobalTypes::CUtlSymbolLarge* , 0x608);
			PROPERTY(m_RenderAttrName,GlobalTypes::CUtlSymbolLarge* , 0x610);
			PROPERTY(m_TargetEntities,GlobalTypes::C_NetworkUtlVectorBase<GlobalTypes::CHandle<client::C_BaseModelEntity>>, 0x618);
			PROPERTY(m_nTargetChangeCount,int32_t , 0x630);
			PROPERTY(m_vecCSSClasses,GlobalTypes::C_NetworkUtlVectorBase<GlobalTypes::CUtlSymbolLarge>, 0x638);
			PROPERTY(m_bCheckCSSClasses,bool , 0x7b0);
			S2_PAD(0x1E0);
		};
		//static_assert(sizeof(CS2::client::CInfoOffscreenPanoramaTexture) == 0x7D8, "CInfoOffscreenPanoramaTexture size should be 0x7D8");
	}
}
