// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CInfoDynamicShadowHint.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CInfoDynamicShadowHintBox : public CS2::client::CInfoDynamicShadowHint {
		public:
			PROPERTY(m_vBoxMins,GlobalTypes::Vector, 0x620);
			PROPERTY(m_vBoxMaxs,GlobalTypes::Vector, 0x62c);
			S2_PAD(0x18);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::CInfoDynamicShadowHintBox) == 0x638, "CInfoDynamicShadowHintBox size should be 0x638");

#endif
	}
}
