// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "../animlib/CNmPassthroughNode_CDefinition.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CNmSnapWeaponNode_CDefinition : public CS2::animlib::CNmPassthroughNode_CDefinition {
		public:
			PROPERTY(m_nEnabledNodeIdx,int16_t, 0x18);
			PROPERTY(m_nLockLeftHandNodeIdx,int16_t, 0x1a);
			PROPERTY(m_flBlendTimeSeconds,float32, 0x1c);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::CNmSnapWeaponNode_CDefinition) == 0x20, "CNmSnapWeaponNode::CDefinition size should be 0x20");

#endif
	}
}
