// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "C_PointClientUIWorldPanel.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CPointOffScreenIndicatorUi : public CS2::client::C_PointClientUIWorldPanel {
		public:
			PROPERTY(m_bBeenEnabled,bool, 0x10e0);
			PROPERTY(m_bHide,bool, 0x10e1);
			PROPERTY(m_flSeenTargetTime,float32, 0x10e4);
			PROPERTY(m_pTargetPanel,IDENTITY(client::C_PointClientUIWorldPanel*), 0x10e8);
			S2_PAD(0x10);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::client::CPointOffScreenIndicatorUi) == 0x10F0, "CPointOffScreenIndicatorUi size should be 0x10F0");

#endif
	}
}
