// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once
#include <cstdint>

namespace CS2 {
	namespace client {
		enum CSWeaponCategory : std::uint32_t {
			WEAPONCATEGORY_COUNT = 0x6,
			WEAPONCATEGORY_HEAVY = 0x5,
			WEAPONCATEGORY_MELEE = 0x1,
			WEAPONCATEGORY_OTHER = 0x0,
			WEAPONCATEGORY_RIFLE = 0x4,
			WEAPONCATEGORY_SECONDARY = 0x2,
			WEAPONCATEGORY_SMG = 0x3
		};
	}
}