// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace animationsystem {
		class CAnimDesc;
		class CAnimDecoder;
		class CAnimFrameSegment;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace animationsystem {
		class CAnimData  {
		public:
			PROPERTY(m_name,GlobalTypes::CBufferString , 0x10);
			PROPERTY(m_animArray,GlobalTypes::CUtlVector<animationsystem::CAnimDesc>, 0x20);
			PROPERTY(m_decoderArray,GlobalTypes::CUtlVector<animationsystem::CAnimDecoder>, 0x38);
			PROPERTY(m_nMaxUniqueFrameIndex,int32_t , 0x50);
			PROPERTY(m_segmentArray,GlobalTypes::CUtlVector<animationsystem::CAnimFrameSegment>, 0x58);
			S2_PAD(0x70);
		};
		//static_assert(sizeof(CS2::animationsystem::CAnimData) == 0x70, "CAnimData size should be 0x70");
	}
}
