// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CAttributeManager.hpp"
#include "CEconItemView.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CAttributeContainer : public CS2::server::CAttributeManager {
		public:
			NESTED_PROPERTY(m_Item,IDENTITY(server::CEconItemView), 0x50);
			S2_PAD(0x2A8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CAttributeContainer) == 0x2F8, "CAttributeContainer size should be 0x2F8");

#endif
	}
}
