// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBarnLight : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_bEnabled,bool , 0x7d8);
			PROPERTY(m_nColorMode,int32_t , 0x7dc);
			PROPERTY(m_Color,GlobalTypes::Color , 0x7e0);
			PROPERTY(m_flColorTemperature,float32 , 0x7e4);
			PROPERTY(m_flBrightness,float32 , 0x7e8);
			PROPERTY(m_flBrightnessScale,float32 , 0x7ec);
			PROPERTY(m_nDirectLight,int32_t , 0x7f0);
			PROPERTY(m_nBakedShadowIndex,int32_t , 0x7f4);
			PROPERTY(m_nLightPathUniqueId,int32_t , 0x7f8);
			PROPERTY(m_nLightMapUniqueId,int32_t , 0x7fc);
			PROPERTY(m_nLuminaireShape,int32_t , 0x800);
			PROPERTY(m_flLuminaireSize,float32 , 0x804);
			PROPERTY(m_flLuminaireAnisotropy,float32 , 0x808);
			PROPERTY(m_LightStyleString,GlobalTypes::CUtlString* , 0x810);
			PROPERTY(m_flLightStyleStartTime,entity2::GameTime_t , 0x818);
			PROPERTY(m_QueuedLightStyleStrings,GlobalTypes::CNetworkUtlVectorBase<GlobalTypes::CUtlString>, 0x820);
			PROPERTY(m_LightStyleEvents,GlobalTypes::CNetworkUtlVectorBase<GlobalTypes::CUtlString>, 0x838);
			PROPERTY(m_LightStyleTargets,server::CNetworkUtlVectorBase<GlobalTypes::CHandle<server::CBaseModelEntity>>, 0x850);
			PROPERTY_ARRAY(m_StyleEvent,entity2::CEntityIOOutput , 4 , 0x868);
			PROPERTY(m_hLightCookie,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCTextureBase>, 0x928);
			PROPERTY(m_flShape,float32 , 0x930);
			PROPERTY(m_flSoftX,float32 , 0x934);
			PROPERTY(m_flSoftY,float32 , 0x938);
			PROPERTY(m_flSkirt,float32 , 0x93c);
			PROPERTY(m_flSkirtNear,float32 , 0x940);
			PROPERTY(m_vSizeParams,GlobalTypes::Vector , 0x944);
			PROPERTY(m_flRange,float32 , 0x950);
			PROPERTY(m_vShear,GlobalTypes::Vector , 0x954);
			PROPERTY(m_nBakeSpecularToCubemaps,int32_t , 0x960);
			PROPERTY(m_vBakeSpecularToCubemapsSize,GlobalTypes::Vector , 0x964);
			PROPERTY(m_nCastShadows,int32_t , 0x970);
			PROPERTY(m_nShadowMapSize,int32_t , 0x974);
			PROPERTY(m_nShadowPriority,int32_t , 0x978);
			PROPERTY(m_bContactShadow,bool , 0x97c);
			PROPERTY(m_bForceShadowsEnabled,bool , 0x97d);
			PROPERTY(m_nBounceLight,int32_t , 0x980);
			PROPERTY(m_flBounceScale,float32 , 0x984);
			PROPERTY(m_flMinRoughness,float32 , 0x988);
			PROPERTY(m_vAlternateColor,GlobalTypes::Vector , 0x98c);
			PROPERTY(m_fAlternateColorBrightness,float32 , 0x998);
			PROPERTY(m_nFog,int32_t , 0x99c);
			PROPERTY(m_flFogStrength,float32 , 0x9a0);
			PROPERTY(m_nFogShadows,int32_t , 0x9a4);
			PROPERTY(m_flFogScale,float32 , 0x9a8);
			PROPERTY(m_bFogMixedShadows,bool , 0x9ac);
			PROPERTY(m_flFadeSizeStart,float32 , 0x9b0);
			PROPERTY(m_flFadeSizeEnd,float32 , 0x9b4);
			PROPERTY(m_flShadowFadeSizeStart,float32 , 0x9b8);
			PROPERTY(m_flShadowFadeSizeEnd,float32 , 0x9bc);
			PROPERTY(m_bPrecomputedFieldsValid,bool , 0x9c0);
			PROPERTY(m_vPrecomputedBoundsMins,GlobalTypes::Vector , 0x9c4);
			PROPERTY(m_vPrecomputedBoundsMaxs,GlobalTypes::Vector , 0x9d0);
			PROPERTY(m_vPrecomputedOBBOrigin,GlobalTypes::Vector , 0x9dc);
			PROPERTY(m_vPrecomputedOBBAngles,GlobalTypes::QAngle , 0x9e8);
			PROPERTY(m_vPrecomputedOBBExtent,GlobalTypes::Vector , 0x9f4);
			PROPERTY(m_nPrecomputedSubFrusta,int32_t , 0xa00);
			PROPERTY(m_vPrecomputedOBBOrigin0,GlobalTypes::Vector , 0xa04);
			PROPERTY(m_vPrecomputedOBBAngles0,GlobalTypes::QAngle , 0xa10);
			PROPERTY(m_vPrecomputedOBBExtent0,GlobalTypes::Vector , 0xa1c);
			PROPERTY(m_vPrecomputedOBBOrigin1,GlobalTypes::Vector , 0xa28);
			PROPERTY(m_vPrecomputedOBBAngles1,GlobalTypes::QAngle , 0xa34);
			PROPERTY(m_vPrecomputedOBBExtent1,GlobalTypes::Vector , 0xa40);
			PROPERTY(m_vPrecomputedOBBOrigin2,GlobalTypes::Vector , 0xa4c);
			PROPERTY(m_vPrecomputedOBBAngles2,GlobalTypes::QAngle , 0xa58);
			PROPERTY(m_vPrecomputedOBBExtent2,GlobalTypes::Vector , 0xa64);
			PROPERTY(m_vPrecomputedOBBOrigin3,GlobalTypes::Vector , 0xa70);
			PROPERTY(m_vPrecomputedOBBAngles3,GlobalTypes::QAngle , 0xa7c);
			PROPERTY(m_vPrecomputedOBBExtent3,GlobalTypes::Vector , 0xa88);
			PROPERTY(m_vPrecomputedOBBOrigin4,GlobalTypes::Vector , 0xa94);
			PROPERTY(m_vPrecomputedOBBAngles4,GlobalTypes::QAngle , 0xaa0);
			PROPERTY(m_vPrecomputedOBBExtent4,GlobalTypes::Vector , 0xaac);
			PROPERTY(m_vPrecomputedOBBOrigin5,GlobalTypes::Vector , 0xab8);
			PROPERTY(m_vPrecomputedOBBAngles5,GlobalTypes::QAngle , 0xac4);
			PROPERTY(m_vPrecomputedOBBExtent5,GlobalTypes::Vector , 0xad0);
			PROPERTY(m_bPvsModifyEntity,bool , 0xadc);
			PROPERTY(m_VisClusters,GlobalTypes::CNetworkUtlVectorBase< uint16 >, 0xae0);
			S2_PAD(0x328);
		};
		//static_assert(sizeof(CS2::server::CBarnLight) == 0xB00, "CBarnLight size should be 0xB00");
	}
}
