// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLogicalEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBaseFilter : public CS2::server::CLogicalEntity {
		public:
			PROPERTY(m_bNegated,bool , 0x4f0);
			PROPERTY(m_OnPass,entity2::CEntityIOOutput , 0x4f8);
			PROPERTY(m_OnFail,entity2::CEntityIOOutput , 0x520);
			S2_PAD(0x58);
		};
		//static_assert(sizeof(CS2::server::CBaseFilter) == 0x548, "CBaseFilter size should be 0x548");
	}
}
