// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseAnimGraph.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/client/SceneEventId_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBaseFlex : public CS2::server::CBaseAnimGraph {
		public:
			PROPERTY(m_flexWeight,GlobalTypes::CNetworkUtlVectorBase< float32 >, 0xa90);
			PROPERTY(m_vLookTargetPosition,GlobalTypes::VectorWS , 0xaa8);
			PROPERTY(m_blinktoggle,bool , 0xab4);
			PROPERTY(m_flAllowResponsesEndTime,entity2::GameTime_t , 0xb08);
			PROPERTY(m_flLastFlexAnimationTime,entity2::GameTime_t , 0xb0c);
			PROPERTY(m_nNextSceneEventId,client::SceneEventId_t , 0xb10);
			PROPERTY(m_bUpdateLayerPriorities,bool , 0xb14);
			S2_PAD(0x90);
		};
		//static_assert(sizeof(CS2::server::CBaseFlex) == 0xB20, "CBaseFlex size should be 0xB20");
	}
}
