// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CDynamicProp.hpp>
#include <SDK/client/DoorState_t.hpp>
#include <SDK/server/locksound_t.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>



namespace CS2 {
	namespace server {
		class CBaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBasePropDoor : public CS2::server::CDynamicProp {
		public:
			PROPERTY(m_flAutoReturnDelay,float32 , 0xd60);
			PROPERTY(m_hDoorList,server::CUtlVector<GlobalTypes::CHandle<server::CBasePropDoor>>, 0xd68);
			PROPERTY(m_nHardwareType,int32_t , 0xd80);
			PROPERTY(m_bNeedsHardware,bool , 0xd84);
			PROPERTY(m_eDoorState,client::DoorState_t , 0xd88);
			PROPERTY(m_bLocked,bool , 0xd8c);
			PROPERTY(m_bNoNPCs,bool , 0xd8d);
			PROPERTY(m_closedPosition,GlobalTypes::Vector , 0xd90);
			PROPERTY(m_closedAngles,GlobalTypes::QAngle , 0xd9c);
			PROPERTY(m_hBlocker,GlobalTypes::CHandle<server::CBaseEntity>, 0xda8);
			PROPERTY(m_bFirstBlocked,bool , 0xdac);
			PROPERTY(m_ls,server::locksound_t , 0xdb0);
			PROPERTY(m_bForceClosed,bool , 0xdd0);
			PROPERTY(m_vecLatchWorldPosition,GlobalTypes::VectorWS , 0xdd4);
			PROPERTY(m_hActivator,GlobalTypes::CHandle<server::CBaseEntity>, 0xde0);
			PROPERTY(m_SoundMoving,GlobalTypes::CUtlSymbolLarge* , 0xdf8);
			PROPERTY(m_SoundOpen,GlobalTypes::CUtlSymbolLarge* , 0xe00);
			PROPERTY(m_SoundClose,GlobalTypes::CUtlSymbolLarge* , 0xe08);
			PROPERTY(m_SoundLock,GlobalTypes::CUtlSymbolLarge* , 0xe10);
			PROPERTY(m_SoundUnlock,GlobalTypes::CUtlSymbolLarge* , 0xe18);
			PROPERTY(m_SoundLatch,GlobalTypes::CUtlSymbolLarge* , 0xe20);
			PROPERTY(m_SoundPound,GlobalTypes::CUtlSymbolLarge* , 0xe28);
			PROPERTY(m_SoundJiggle,GlobalTypes::CUtlSymbolLarge* , 0xe30);
			PROPERTY(m_SoundLockedAnim,GlobalTypes::CUtlSymbolLarge* , 0xe38);
			PROPERTY(m_numCloseAttempts,int32_t , 0xe40);
			PROPERTY(m_nPhysicsMaterial,GlobalTypes::CUtlStringToken* , 0xe44);
			PROPERTY(m_SlaveName,GlobalTypes::CUtlSymbolLarge* , 0xe48);
			PROPERTY(m_hMaster,GlobalTypes::CHandle<server::CBasePropDoor>, 0xe50);
			PROPERTY(m_OnBlockedClosing,entity2::CEntityIOOutput , 0xe58);
			PROPERTY(m_OnBlockedOpening,entity2::CEntityIOOutput , 0xe80);
			PROPERTY(m_OnUnblockedClosing,entity2::CEntityIOOutput , 0xea8);
			PROPERTY(m_OnUnblockedOpening,entity2::CEntityIOOutput , 0xed0);
			PROPERTY(m_OnFullyClosed,entity2::CEntityIOOutput , 0xef8);
			PROPERTY(m_OnFullyOpen,entity2::CEntityIOOutput , 0xf20);
			PROPERTY(m_OnClose,entity2::CEntityIOOutput , 0xf48);
			PROPERTY(m_OnOpen,entity2::CEntityIOOutput , 0xf70);
			PROPERTY(m_OnLockedUse,entity2::CEntityIOOutput , 0xf98);
			PROPERTY(m_OnAjarOpen,entity2::CEntityIOOutput , 0xfc0);
			S2_PAD(0x2A0);
		};
		//static_assert(sizeof(CS2::server::CBasePropDoor) == 0xFF0, "CBasePropDoor size should be 0xFF0");
	}
}
