// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CSkeletonAnimationController.hpp>
#include <SDK/server/CAnimGraphNetworkedVariables.hpp>
#include <SDK/animationsystem/HSequence.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/client/AnimLoopMode_t.hpp>
#include <SDK/client/SequenceFinishNotifyState_t.hpp>



namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeCNmGraphDefinition;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBaseAnimGraphController : public CS2::client::CSkeletonAnimationController {
		public:
			PROPERTY(m_animGraphNetworkedVars,server::CAnimGraphNetworkedVariables , 0x18);
			PROPERTY(m_bSequenceFinished,bool , 0x220);
			PROPERTY(m_flSoundSyncTime,float32 , 0x224);
			PROPERTY(m_nActiveIKChainMask,uint32_t , 0x228);
			PROPERTY(m_hSequence,animationsystem::HSequence , 0x22c);
			PROPERTY(m_flSeqStartTime,entity2::GameTime_t , 0x230);
			PROPERTY(m_flSeqFixedCycle,float32 , 0x234);
			PROPERTY(m_nAnimLoopMode,client::AnimLoopMode_t , 0x238);
			PROPERTY(m_flPlaybackRate,GlobalTypes::CNetworkedQuantizedFloat , 0x23c);
			PROPERTY(m_nNotifyState,client::SequenceFinishNotifyState_t , 0x248);
			PROPERTY(m_bNetworkedAnimationInputsChanged,bool , 0x24a);
			PROPERTY(m_bNetworkedSequenceChanged,bool , 0x24b);
			PROPERTY(m_bLastUpdateSkipped,bool , 0x24c);
			PROPERTY(m_flPrevAnimUpdateTime,entity2::GameTime_t , 0x250);
			PROPERTY(m_hGraphDefinitionAG2,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCNmGraphDefinition>, 0x588);
			PROPERTY(m_bIsUsingAG2,bool , 0x590);
			PROPERTY(m_serializedPoseRecipeAG2,GlobalTypes::CNetworkUtlVectorBase< uint8 >, 0x598);
			PROPERTY(m_nSerializePoseRecipeSizeAG2,int32_t , 0x5b0);
			PROPERTY(m_nSerializePoseRecipeVersionAG2,int32_t , 0x5b4);
			PROPERTY(m_nGraphCreationFlagsAG2,uint8_t , 0x5b8);
			PROPERTY(m_nServerGraphDefReloadCountAG2,int32_t , 0x7a0);
			PROPERTY(m_nServerSerializationContextIteration,int32_t , 0x7a4);
			S2_PAD(0x7A0);
		};
		//static_assert(sizeof(CS2::server::CBaseAnimGraphController) == 0x7B0, "CBaseAnimGraphController size should be 0x7B0");
	}
}
