// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseToggle.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBasePlatTrain : public CS2::server::CBaseToggle {
		public:
			PROPERTY(m_NoiseMoving,GlobalTypes::CUtlSymbolLarge* , 0x858);
			PROPERTY(m_NoiseArrived,GlobalTypes::CUtlSymbolLarge* , 0x860);
			PROPERTY(m_volume,float32 , 0x870);
			PROPERTY(m_flTWidth,float32 , 0x874);
			PROPERTY(m_flTLength,float32 , 0x878);
			S2_PAD(0x28);
		};
		//static_assert(sizeof(CS2::server::CBasePlatTrain) == 0x880, "CBasePlatTrain size should be 0x880");
	}
}
