// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>
#include <SDK/server/PhysicsRagdollPose_t.hpp>



namespace CS2 {
	namespace client {
		class IChoreoServices;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBaseAnimGraph : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_bInitiallyPopulateInterpHistory,bool , 0x858);
			PROPERTY(m_pChoreoServices,client::IChoreoServices* , 0x860);
			PROPERTY(m_bAnimGraphUpdateEnabled,bool , 0x868);
			PROPERTY(m_flMaxSlopeDistance,float32 , 0x86c);
			PROPERTY(m_vLastSlopeCheckPos,GlobalTypes::VectorWS , 0x870);
			PROPERTY(m_bAnimationUpdateScheduled,bool , 0x87c);
			PROPERTY(m_vecForce,GlobalTypes::Vector , 0x880);
			PROPERTY(m_nForceBone,int32_t , 0x88c);
			PROPERTY(m_RagdollPose,server::PhysicsRagdollPose_t , 0x8a0);
			PROPERTY(m_bRagdollEnabled,bool , 0x8c8);
			PROPERTY(m_bRagdollClientSide,bool , 0x8c9);
			PROPERTY(m_xParentedRagdollRootInEntitySpace,GlobalTypes::CTransform , 0x8d0);
			S2_PAD(0x2B8);
		};
		//static_assert(sizeof(CS2::server::CBaseAnimGraph) == 0xA90, "CBaseAnimGraph size should be 0xA90");
	}
}
