// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CPathKeyFrame.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBaseMoveBehavior : public CS2::server::CPathKeyFrame {
		public:
			PROPERTY(m_iPositionInterpolator,int32_t, 0x500);
			PROPERTY(m_iRotationInterpolator,int32_t, 0x504);
			PROPERTY(m_flAnimStartTime,float32, 0x508);
			PROPERTY(m_flAnimEndTime,float32, 0x50c);
			PROPERTY(m_flAverageSpeedAcrossFrame,float32, 0x510);
			PROPERTY(m_pCurrentKeyFrame,IDENTITY(server::CPathKeyFrame*), 0x518);
			PROPERTY(m_pTargetKeyFrame,IDENTITY(server::CPathKeyFrame*), 0x520);
			PROPERTY(m_pPreKeyFrame,IDENTITY(server::CPathKeyFrame*), 0x528);
			PROPERTY(m_pPostKeyFrame,IDENTITY(server::CPathKeyFrame*), 0x530);
			PROPERTY(m_flTimeIntoFrame,float32, 0x538);
			PROPERTY(m_iDirection,int32_t, 0x53c);
			S2_PAD(0x40);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CBaseMoveBehavior) == 0x540, "CBaseMoveBehavior size should be 0x540");

#endif
	}
}
