// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "../client/CSkeletonAnimationController.hpp"
#include "../client/AnimationAlgorithm_t.hpp"
#include "CAnimGraphNetworkedVariables.hpp"
#include "../animgraphlib/IAnimationGraphInstance.hpp"
#include "../client/ExternalAnimGraphHandle_t.hpp"
#include "CBaseAnimGraph.hpp"
#include "../animationsystem/HSequence.hpp"
#include "../entity2/GameTime_t.hpp"
#include "../client/AnimLoopMode_t.hpp"
#include "../client/SequenceFinishNotifyState_t.hpp"
#include "../entity2/GameTick_t.hpp"
#include "../resourcefile/ResourceId_t.hpp"
#include "../client/ExternalAnimGraph_t.hpp"



namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeCNmGraphDefinition;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBaseAnimGraphController : public CS2::client::CSkeletonAnimationController {
		public:
			PROPERTY(m_nAnimationAlgorithm,IDENTITY(client::AnimationAlgorithm_t), 0x18);
			NESTED_PROPERTY(m_animGraphNetworkedVars,IDENTITY(server::CAnimGraphNetworkedVariables), 0x20);
			PROPERTY(m_pAnimGraphInstance,IDENTITY(GlobalTypes::CSmartPtr<animgraphlib::IAnimationGraphInstance>), 0x228);
			NESTED_PROPERTY(m_nNextExternalGraphHandle,IDENTITY(client::ExternalAnimGraphHandle_t), 0x288);
			NESTED_PROPERTY(m_vecSecondarySkeletonNames,IDENTITY(GlobalTypes::CUtlVector<GlobalTypes::CGlobalSymbol>), 0x290);
			// PROPERTY(m_vecSecondarySkeletons,IDENTITY(server::CNetworkUtlVectorBase<GlobalTypes::CHandle<server::CBaseAnimGraph>>), 0x2a8);
			PROPERTY(m_nSecondarySkeletonMasterCount,int32_t, 0x2c0);
			PROPERTY(m_flSoundSyncTime,float32, 0x2c4);
			PROPERTY(m_nActiveIKChainMask,uint32_t, 0x2c8);
			NESTED_PROPERTY(m_hSequence,IDENTITY(animationsystem::HSequence), 0x2cc);
			NESTED_PROPERTY(m_flSeqStartTime,IDENTITY(entity2::GameTime_t), 0x2d0);
			PROPERTY(m_flSeqFixedCycle,float32, 0x2d4);
			PROPERTY(m_nAnimLoopMode,IDENTITY(client::AnimLoopMode_t), 0x2d8);
			PROPERTY(m_flPlaybackRate,GlobalTypes::CNetworkedQuantizedFloat, 0x2dc);
			PROPERTY(m_nNotifyState,IDENTITY(client::SequenceFinishNotifyState_t), 0x2e8);
			PROPERTY(m_bNetworkedAnimationInputsChanged,bool, 0x2e9);
			PROPERTY(m_bNetworkedSequenceChanged,bool, 0x2ea);
			PROPERTY(m_bLastUpdateSkipped,bool, 0x2eb);
			PROPERTY(m_bSequenceFinished,bool, 0x2ec);
			NESTED_PROPERTY(m_nPrevAnimUpdateTick,IDENTITY(entity2::GameTick_t), 0x2f0);
			PROPERTY(m_hGraphDefinitionAG2,IDENTITY(GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCNmGraphDefinition>), 0x590);
			// PROPERTY(m_serializedPoseRecipeAG2,IDENTITY(GlobalTypes::CNetworkUtlVectorBase< uint8 >), 0x598);
			PROPERTY(m_nSerializePoseRecipeSizeAG2,int32_t, 0x5b0);
			PROPERTY(m_nSerializePoseRecipeVersionAG2,int32_t, 0x5b4);
			PROPERTY(m_nServerGraphInstanceIteration,int32_t, 0x5b8);
			PROPERTY(m_nServerSerializationContextIteration,int32_t, 0x5bc);
			NESTED_PROPERTY(m_primaryGraphId,IDENTITY(resourcefile::ResourceId_t), 0x5c0);
			// PROPERTY(m_vecExternalGraphIds,IDENTITY(GlobalTypes::CNetworkUtlVectorBase<resourcefile::ResourceId_t>), 0x5c8);
			// PROPERTY(m_vecExternalClipIds,IDENTITY(GlobalTypes::CNetworkUtlVectorBase<resourcefile::ResourceId_t>), 0x5e0);
			PROPERTY(m_sAnimGraph2Identifier,GlobalTypes::CGlobalSymbol, 0x5f8);
			NESTED_PROPERTY(m_vecExternalGraphs,IDENTITY(GlobalTypes::CUtlVector<client::ExternalAnimGraph_t>), 0x820);
			S2_PAD(0x848);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CBaseAnimGraphController) == 0x858, "CBaseAnimGraphController size should be 0x858");

#endif
	}
}
