// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBaseClientUIEntity : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_bEnabled,bool , 0x7d8);
			PROPERTY(m_DialogXMLName,GlobalTypes::CUtlSymbolLarge* , 0x7e0);
			PROPERTY(m_PanelClassName,GlobalTypes::CUtlSymbolLarge* , 0x7e8);
			PROPERTY(m_PanelID,GlobalTypes::CUtlSymbolLarge* , 0x7f0);
			PROPERTY(m_CustomOutput0,entity2::CEntityIOOutput , 0x7f8);
			PROPERTY(m_CustomOutput1,entity2::CEntityIOOutput , 0x820);
			PROPERTY(m_CustomOutput2,entity2::CEntityIOOutput , 0x848);
			PROPERTY(m_CustomOutput3,entity2::CEntityIOOutput , 0x870);
			PROPERTY(m_CustomOutput4,entity2::CEntityIOOutput , 0x898);
			PROPERTY(m_CustomOutput5,entity2::CEntityIOOutput , 0x8c0);
			PROPERTY(m_CustomOutput6,entity2::CEntityIOOutput , 0x8e8);
			PROPERTY(m_CustomOutput7,entity2::CEntityIOOutput , 0x910);
			PROPERTY(m_CustomOutput8,entity2::CEntityIOOutput , 0x938);
			PROPERTY(m_CustomOutput9,entity2::CEntityIOOutput , 0x960);
			S2_PAD(0x1B0);
		};
		//static_assert(sizeof(CS2::server::CBaseClientUIEntity) == 0x988, "CBaseClientUIEntity size should be 0x988");
	}
}
