// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseFlex.hpp>
#include <SDK/client/Hull_t.hpp>
#include <SDK/server/CMovementStatsProperty.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBaseCombatCharacter : public CS2::server::CBaseFlex {
		public:
			PROPERTY(m_bForceServerRagdoll,bool , 0xb20);
			PROPERTY(m_hMyWearables,server::CNetworkUtlVectorBase<GlobalTypes::CHandle<server::CEconWearable>>, 0xb28);
			PROPERTY(m_impactEnergyScale,float32 , 0xb40);
			PROPERTY(m_bApplyStressDamage,bool , 0xb44);
			PROPERTY(m_bDeathEventsDispatched,bool , 0xb45);
			PROPERTY(m_pVecRelationships,GlobalTypes::CUtlVector< RelationshipOverride_t >**, 0xb88);
			PROPERTY(m_strRelationships,GlobalTypes::CUtlSymbolLarge* , 0xb90);
			PROPERTY(m_eHull,client::Hull_t , 0xb98);
			PROPERTY(m_nNavHullIdx,uint32_t , 0xb9c);
			PROPERTY(m_movementStats,server::CMovementStatsProperty , 0xba0);
			S2_PAD(0xC0);
		};
		//static_assert(sizeof(CS2::server::CBaseCombatCharacter) == 0xBE0, "CBaseCombatCharacter size should be 0xBE0");
	}
}
