// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseAnimGraph.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBaseProp : public CS2::server::CBaseAnimGraph {
		public:
			PROPERTY(m_bModelOverrodeBlockLOS,bool , 0xa90);
			PROPERTY(m_iShapeType,int32_t , 0xa94);
			PROPERTY(m_bConformToCollisionBounds,bool , 0xa98);
			PROPERTY(m_mPreferredCatchTransform,GlobalTypes::CTransform , 0xaa0);
			S2_PAD(0x30);
		};
		//static_assert(sizeof(CS2::server::CBaseProp) == 0xAC0, "CBaseProp size should be 0xAC0");
	}
}
