// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/client/BeamType_t.hpp>
#include <SDK/modellib/AttachmentHandle_t.hpp>
#include <SDK/client/BeamClipStyle_t.hpp>



namespace CS2 {
	namespace server {
		class CBaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBeam : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_flFrameRate,float32 , 0x7d8);
			PROPERTY(m_flHDRColorScale,float32 , 0x7dc);
			PROPERTY(m_flFireTime,entity2::GameTime_t , 0x7e0);
			PROPERTY(m_flDamage,float32 , 0x7e4);
			PROPERTY(m_nNumBeamEnts,uint8_t , 0x7e8);
			PROPERTY(m_hBaseMaterial,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>, 0x7f0);
			PROPERTY(m_nHaloIndex,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>, 0x7f8);
			PROPERTY(m_nBeamType,client::BeamType_t , 0x800);
			PROPERTY(m_nBeamFlags,uint32_t , 0x804);
			PROPERTY_ARRAY(m_hAttachEntity,server::CHandle< CBaseEntity >, 10 , 0x808);
			PROPERTY_ARRAY(m_nAttachIndex,modellib::AttachmentHandle_t , 10 , 0x830);
			PROPERTY(m_fWidth,float32 , 0x83c);
			PROPERTY(m_fEndWidth,float32 , 0x840);
			PROPERTY(m_fFadeLength,float32 , 0x844);
			PROPERTY(m_fHaloScale,float32 , 0x848);
			PROPERTY(m_fAmplitude,float32 , 0x84c);
			PROPERTY(m_fStartFrame,float32 , 0x850);
			PROPERTY(m_fSpeed,float32 , 0x854);
			PROPERTY(m_flFrame,float32 , 0x858);
			PROPERTY(m_nClipStyle,client::BeamClipStyle_t , 0x85c);
			PROPERTY(m_bTurnedOff,bool , 0x860);
			PROPERTY(m_vecEndPos,GlobalTypes::VectorWS , 0x864);
			PROPERTY(m_hEndEntity,GlobalTypes::CHandle<server::CBaseEntity>, 0x870);
			PROPERTY(m_nDissolveType,int32_t , 0x874);
			S2_PAD(0xA0);
		};
		//static_assert(sizeof(CS2::server::CBeam) == 0x878, "CBeam size should be 0x878");
	}
}
