// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBodyComponentSkeletonInstance.hpp>
#include <SDK/server/CBaseAnimGraphController.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBodyComponentBaseAnimGraph : public CS2::server::CBodyComponentSkeletonInstance {
		public:
			PROPERTY(m_animationController,server::CBaseAnimGraphController , 0x510);
			S2_PAD(0x7B0);
		};
		//static_assert(sizeof(CS2::server::CBodyComponentBaseAnimGraph) == 0xCC0, "CBodyComponentBaseAnimGraph size should be 0xCC0");
	}
}
