// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBodyComponent.hpp>
#include <SDK/server/CGameSceneNode.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBodyComponentPoint : public CS2::server::CBodyComponent {
		public:
			PROPERTY(m_sceneNode,server::CGameSceneNode , 0x80);
			S2_PAD(0x168);
		};
		//static_assert(sizeof(CS2::server::CBodyComponentPoint) == 0x1E0, "CBodyComponentPoint size should be 0x1E0");
	}
}
