// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseProp.hpp>
#include <SDK/server/CPropDataComponent.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>
#include <SDK/client/PerformanceMode_t.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/client/BreakableContentsType_t.hpp>



namespace CS2 {
	namespace server {
		class CBaseEntity;
		class CBasePlayerPawn;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBreakableProp : public CS2::server::CBaseProp {
		public:
			PROPERTY(m_CPropDataComponent,server::CPropDataComponent , 0xac8);
			PROPERTY(m_OnStartDeath,entity2::CEntityIOOutput , 0xb08);
			PROPERTY(m_OnBreak,entity2::CEntityIOOutput , 0xb30);
			PROPERTY(m_OnHealthChanged,GlobalTypes::CEntityOutputTemplate< float32 >, 0xb58);
			PROPERTY(m_OnTakeDamage,entity2::CEntityIOOutput , 0xb80);
			PROPERTY(m_impactEnergyScale,float32 , 0xba8);
			PROPERTY(m_iMinHealthDmg,int32_t , 0xbac);
			PROPERTY(m_preferredCarryAngles,GlobalTypes::QAngle , 0xbb0);
			PROPERTY(m_flPressureDelay,float32 , 0xbbc);
			PROPERTY(m_flDefBurstScale,float32 , 0xbc0);
			PROPERTY(m_vDefBurstOffset,GlobalTypes::Vector , 0xbc4);
			PROPERTY(m_hBreaker,GlobalTypes::CHandle<server::CBaseEntity>, 0xbd0);
			PROPERTY(m_PerformanceMode,client::PerformanceMode_t , 0xbd4);
			PROPERTY(m_flPreventDamageBeforeTime,entity2::GameTime_t , 0xbd8);
			PROPERTY(m_BreakableContentsType,client::BreakableContentsType_t , 0xbdc);
			PROPERTY(m_strBreakableContentsPropGroupOverride,GlobalTypes::CUtlString* , 0xbe0);
			PROPERTY(m_strBreakableContentsParticleOverride,GlobalTypes::CUtlString* , 0xbe8);
			PROPERTY(m_bHasBreakPiecesOrCommands,bool , 0xbf0);
			PROPERTY(m_explodeDamage,float32 , 0xbf4);
			PROPERTY(m_explodeRadius,float32 , 0xbf8);
			PROPERTY(m_explosionDelay,float32 , 0xc00);
			PROPERTY(m_explosionBuildupSound,GlobalTypes::CUtlSymbolLarge* , 0xc08);
			PROPERTY(m_explosionCustomEffect,GlobalTypes::CUtlSymbolLarge* , 0xc10);
			PROPERTY(m_explosionCustomSound,GlobalTypes::CUtlSymbolLarge* , 0xc18);
			PROPERTY(m_explosionModifier,GlobalTypes::CUtlSymbolLarge* , 0xc20);
			PROPERTY(m_hPhysicsAttacker,GlobalTypes::CHandle<server::CBasePlayerPawn>, 0xc28);
			PROPERTY(m_flLastPhysicsInfluenceTime,entity2::GameTime_t , 0xc2c);
			PROPERTY(m_flDefaultFadeScale,float32 , 0xc30);
			PROPERTY(m_hLastAttacker,GlobalTypes::CHandle<server::CBaseEntity>, 0xc34);
			PROPERTY(m_iszPuntSound,GlobalTypes::CUtlSymbolLarge* , 0xc38);
			PROPERTY(m_bUsePuntSound,bool , 0xc40);
			PROPERTY(m_bOriginalBlockLOS,bool , 0xc41);
			S2_PAD(0x190);
		};
		//static_assert(sizeof(CS2::server::CBreakableProp) == 0xC50, "CBreakableProp size should be 0xC50");
	}
}
