// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CBaseTrigger.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CBuyZone : public CS2::server::CBaseTrigger {
		public:
			PROPERTY(m_LegacyTeamNum,int32_t, 0x890);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CBuyZone) == 0x898, "CBuyZone size should be 0x898");

#endif
	}
}
