// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CCommentaryAuto : public CS2::server::CBaseEntity {
		public:
			PROPERTY(m_OnCommentaryNewGame,entity2::CEntityIOOutput , 0x4f0);
			PROPERTY(m_OnCommentaryMidGame,entity2::CEntityIOOutput , 0x518);
			PROPERTY(m_OnCommentaryMultiplayerSpawn,entity2::CEntityIOOutput , 0x540);
			S2_PAD(0x78);
		};
		//static_assert(sizeof(CS2::server::CCommentaryAuto) == 0x568, "CCommentaryAuto size should be 0x568");
	}
}
