// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CCSPlayerResource : public CS2::server::CBaseEntity {
		public:
			PROPERTY_ARRAY(m_bHostageAlive,bool , 12 , 0x4f0);
			PROPERTY_ARRAY(m_isHostageFollowingSomeone,bool , 12 , 0x4fc);
			PROPERTY_ARRAY(m_iHostageEntityIDs,GlobalTypes::CEntityIndex , 12 , 0x508);
			PROPERTY(m_bombsiteCenterA,GlobalTypes::Vector , 0x538);
			PROPERTY(m_bombsiteCenterB,GlobalTypes::Vector , 0x544);
			PROPERTY_ARRAY(m_hostageRescueX,int32_t , 4 , 0x550);
			PROPERTY_ARRAY(m_hostageRescueY,int32_t , 4 , 0x560);
			PROPERTY_ARRAY(m_hostageRescueZ,int32_t , 4 , 0x570);
			PROPERTY(m_bEndMatchNextMapAllVoted,bool , 0x580);
			PROPERTY(m_foundGoalPositions,bool , 0x581);
			S2_PAD(0x98);
		};
		//static_assert(sizeof(CS2::server::CCSPlayerResource) == 0x588, "CCSPlayerResource size should be 0x588");
	}
}
