// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPlayer_MovementServices_Humanoid.hpp>
#include <SDK/entity2/GameTime_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CCSPlayer_MovementServices : public CS2::server::CPlayer_MovementServices_Humanoid {
		public:
			PROPERTY(m_vecLadderNormal,GlobalTypes::Vector , 0x280);
			PROPERTY(m_nLadderSurfacePropIndex,int32_t , 0x28c);
			PROPERTY(m_flDuckAmount,float32 , 0x290);
			PROPERTY(m_flDuckSpeed,float32 , 0x294);
			PROPERTY(m_bDuckOverride,bool , 0x298);
			PROPERTY(m_bDesiresDuck,bool , 0x299);
			PROPERTY(m_flDuckOffset,float32 , 0x29c);
			PROPERTY(m_nDuckTimeMsecs,uint32_t , 0x2a0);
			PROPERTY(m_nDuckJumpTimeMsecs,uint32_t , 0x2a4);
			PROPERTY(m_nJumpTimeMsecs,uint32_t , 0x2a8);
			PROPERTY(m_flLastDuckTime,float32 , 0x2ac);
			PROPERTY(m_vecLastPositionAtFullCrouchSpeed,GlobalTypes::Vector2D , 0x2b8);
			PROPERTY(m_duckUntilOnGround,bool , 0x2c0);
			PROPERTY(m_bHasWalkMovedSinceLastJump,bool , 0x2c1);
			PROPERTY(m_bInStuckTest,bool , 0x2c2);
			PROPERTY(m_nTraceCount,int32_t , 0x4d0);
			PROPERTY(m_StuckLast,int32_t , 0x4d4);
			PROPERTY(m_bSpeedCropped,bool , 0x4d8);
			PROPERTY(m_nOldWaterLevel,int32_t , 0x4dc);
			PROPERTY(m_flWaterEntryTime,float32 , 0x4e0);
			PROPERTY(m_vecForward,GlobalTypes::Vector , 0x4e4);
			PROPERTY(m_vecLeft,GlobalTypes::Vector , 0x4f0);
			PROPERTY(m_vecUp,GlobalTypes::Vector , 0x4fc);
			PROPERTY(m_nGameCodeHasMovedPlayerAfterCommand,int32_t , 0x508);
			PROPERTY(m_bMadeFootstepNoise,bool , 0x50c);
			PROPERTY(m_iFootsteps,int32_t , 0x510);
			PROPERTY(m_bOldJumpPressed,bool , 0x514);
			PROPERTY(m_flJumpPressedTime,float32 , 0x518);
			PROPERTY(m_fStashGrenadeParameterWhen,entity2::GameTime_t , 0x51c);
			PROPERTY(m_nButtonDownMaskPrev,uint64_t , 0x520);
			PROPERTY(m_flOffsetTickCompleteTime,float32 , 0x528);
			PROPERTY(m_flOffsetTickStashedSpeed,float32 , 0x52c);
			PROPERTY(m_flStamina,float32 , 0x530);
			PROPERTY(m_flHeightAtJumpStart,float32 , 0x534);
			PROPERTY(m_flMaxJumpHeightThisJump,float32 , 0x538);
			PROPERTY(m_flMaxJumpHeightLastJump,float32 , 0x53c);
			PROPERTY(m_flStaminaAtJumpStart,float32 , 0x540);
			PROPERTY(m_flAccumulatedJumpError,float32 , 0x544);
			PROPERTY(m_flTicksSinceLastSurfingDetected,float32 , 0x548);
			PROPERTY(m_bWasSurfing,bool , 0x54c);
			PROPERTY(m_vecInputRotated,GlobalTypes::Vector , 0x5dc);
			PROPERTY(m_bJumpApexPending,bool , 0xe08);
			S2_PAD(0xB90);
		};
		//static_assert(sizeof(CS2::server::CCSPlayer_MovementServices) == 0xE10, "CCSPlayer_MovementServices size should be 0xE10");
	}
}
