// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CPlayerControllerComponent.hpp>
#include <SDK/server/CSMatchStats_t.hpp>



namespace CS2 {
	namespace server {
		class CSPerRoundStats_t;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CCSPlayerController_ActionTrackingServices : public CS2::client::CPlayerControllerComponent {
		public:
			PROPERTY(m_perRoundStats,server::CUtlVectorEmbeddedNetworkVar<server::CSPerRoundStats_t>, 0x40);
			PROPERTY(m_matchStats,server::CSMatchStats_t , 0xc8);
			PROPERTY(m_iNumRoundKills,int32_t , 0x188);
			PROPERTY(m_iNumRoundKillsHeadshots,int32_t , 0x18c);
			PROPERTY(m_flTotalRoundDamageDealt,float32 , 0x190);
			S2_PAD(0x230);
		};
		//static_assert(sizeof(CS2::server::CCSPlayerController_ActionTrackingServices) == 0x270, "CCSPlayerController_ActionTrackingServices size should be 0x270");
	}
}
