// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CPlayerPawnComponent.hpp>
#include <SDK/server/WeaponPurchaseTracker_t.hpp>



namespace CS2 {
	namespace server {
		class CBasePlayerWeapon;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CCSPlayer_ActionTrackingServices : public CS2::client::CPlayerPawnComponent {
		public:
			PROPERTY(m_hLastWeaponBeforeC4AutoSwitch,GlobalTypes::CHandle<server::CBasePlayerWeapon>, 0x1f0);
			PROPERTY(m_bIsRescuing,bool , 0x21c);
			PROPERTY(m_weaponPurchasesThisMatch,server::WeaponPurchaseTracker_t , 0x220);
			PROPERTY(m_weaponPurchasesThisRound,server::WeaponPurchaseTracker_t , 0x290);
			S2_PAD(0x2C8);
		};
		//static_assert(sizeof(CS2::server::CCSPlayer_ActionTrackingServices) == 0x308, "CCSPlayer_ActionTrackingServices size should be 0x308");
	}
}
