// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBasePlayerWeapon.hpp>
#include <SDK/client/WeaponGameplayAnimState.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>
#include <SDK/client/CSWeaponMode.hpp>
#include <SDK/entity2/GameTick_t.hpp>
#include <SDK/server/CIronSightController.hpp>



namespace CS2 {
	namespace server {
		class CCSPlayerPawn;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CCSWeaponBase : public CS2::server::CBasePlayerWeapon {
		public:
			PROPERTY(m_bRemoveable,bool , 0xea0);
			PROPERTY(m_bPlayerAmmoStockOnPickup,bool , 0xeb0);
			PROPERTY(m_bRequireUseToTouch,bool , 0xeb1);
			PROPERTY(m_iWeaponGameplayAnimState,client::WeaponGameplayAnimState , 0xeb2);
			PROPERTY(m_flWeaponGameplayAnimStateTimestamp,entity2::GameTime_t , 0xeb4);
			PROPERTY(m_flInspectCancelCompleteTime,entity2::GameTime_t , 0xeb8);
			PROPERTY(m_bInspectPending,bool , 0xebc);
			PROPERTY(m_bInspectShouldLoop,bool , 0xebd);
			PROPERTY(m_nLastEmptySoundCmdNum,int32_t , 0xee8);
			PROPERTY(m_bFireOnEmpty,bool , 0xf08);
			PROPERTY(m_OnPlayerPickup,entity2::CEntityIOOutput , 0xf10);
			PROPERTY(m_weaponMode,client::CSWeaponMode , 0xf38);
			PROPERTY(m_flTurningInaccuracyDelta,float32 , 0xf3c);
			PROPERTY(m_vecTurningInaccuracyEyeDirLast,GlobalTypes::Vector , 0xf40);
			PROPERTY(m_flTurningInaccuracy,float32 , 0xf4c);
			PROPERTY(m_fAccuracyPenalty,float32 , 0xf50);
			PROPERTY(m_flLastAccuracyUpdateTime,entity2::GameTime_t , 0xf54);
			PROPERTY(m_fAccuracySmoothedForZoom,float32 , 0xf58);
			PROPERTY(m_iRecoilIndex,int32_t , 0xf5c);
			PROPERTY(m_flRecoilIndex,float32 , 0xf60);
			PROPERTY(m_bBurstMode,bool , 0xf64);
			PROPERTY(m_nPostponeFireReadyTicks,entity2::GameTick_t , 0xf68);
			PROPERTY(m_flPostponeFireReadyFrac,float32 , 0xf6c);
			PROPERTY(m_bInReload,bool , 0xf70);
			PROPERTY(m_flDroppedAtTime,entity2::GameTime_t , 0xf74);
			PROPERTY(m_bIsHauledBack,bool , 0xf78);
			PROPERTY(m_bSilencerOn,bool , 0xf79);
			PROPERTY(m_flTimeSilencerSwitchComplete,entity2::GameTime_t , 0xf7c);
			PROPERTY(m_iOriginalTeamNumber,int32_t , 0xf80);
			PROPERTY(m_iMostRecentTeamNumber,int32_t , 0xf84);
			PROPERTY(m_bDroppedNearBuyZone,bool , 0xf88);
			PROPERTY(m_flNextAttackRenderTimeOffset,float32 , 0xf8c);
			PROPERTY(m_bCanBePickedUp,bool , 0xfa0);
			PROPERTY(m_bUseCanOverrideNextOwnerTouchTime,bool , 0xfa1);
			PROPERTY(m_nextOwnerTouchTime,entity2::GameTime_t , 0xfa4);
			PROPERTY(m_nextPrevOwnerTouchTime,entity2::GameTime_t , 0xfa8);
			PROPERTY(m_nextPrevOwnerUseTime,entity2::GameTime_t , 0xfb0);
			PROPERTY(m_hPrevOwner,GlobalTypes::CHandle<server::CCSPlayerPawn>, 0xfb4);
			PROPERTY(m_nDropTick,entity2::GameTick_t , 0xfb8);
			PROPERTY(m_bWasActiveWeaponWhenDropped,bool , 0xfbc);
			PROPERTY(m_donated,bool , 0xfdc);
			PROPERTY(m_fLastShotTime,entity2::GameTime_t , 0xfe0);
			PROPERTY(m_bWasOwnedByCT,bool , 0xfe4);
			PROPERTY(m_bWasOwnedByTerrorist,bool , 0xfe5);
			PROPERTY(m_numRemoveUnownedWeaponThink,int32_t , 0xfe8);
			PROPERTY(m_IronSightController,server::CIronSightController , 0xff0);
			PROPERTY(m_iIronSightMode,int32_t , 0x1008);
			PROPERTY(m_flLastLOSTraceFailureTime,entity2::GameTime_t , 0x100c);
			PROPERTY(m_flWatTickOffset,float32 , 0x1010);
			PROPERTY(m_flLastShakeTime,entity2::GameTime_t , 0x1020);
			S2_PAD(0x330);
		};
		//static_assert(sizeof(CS2::server::CCSWeaponBase) == 0x11D0, "CCSWeaponBase size should be 0x11D0");
	}
}
