// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CCSWeaponBase.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CCSWeaponBaseGun : public CS2::server::CCSWeaponBase {
		public:
			PROPERTY(m_zoomLevel,int32_t , 0x11d0);
			PROPERTY(m_iBurstShotsRemaining,int32_t , 0x11d4);
			PROPERTY(m_silencedModelIndex,int32_t , 0x11e0);
			PROPERTY(m_inPrecache,bool , 0x11e4);
			PROPERTY(m_bNeedsBoltAction,bool , 0x11e5);
			PROPERTY(m_nRevolverCylinderIdx,int32_t , 0x11e8);
			PROPERTY(m_bSkillReloadAvailable,bool , 0x11ec);
			PROPERTY(m_bSkillReloadLiftedReloadKey,bool , 0x11ed);
			PROPERTY(m_bSkillBoltInterruptAvailable,bool , 0x11ee);
			PROPERTY(m_bSkillBoltLiftedFireKey,bool , 0x11ef);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::server::CCSWeaponBaseGun) == 0x11F0, "CCSWeaponBaseGun size should be 0x11F0");
	}
}
