// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLogicalEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CEnvFade : public CS2::server::CLogicalEntity {
		public:
			PROPERTY(m_fadeColor,GlobalTypes::Color , 0x4f0);
			PROPERTY(m_Duration,float32 , 0x4f4);
			PROPERTY(m_HoldDuration,float32 , 0x4f8);
			PROPERTY(m_OnBeginFade,entity2::CEntityIOOutput , 0x500);
			S2_PAD(0x38);
		};
		//static_assert(sizeof(CS2::server::CEnvFade) == 0x528, "CEnvFade size should be 0x528");
	}
}
