// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPointEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>



namespace CS2 {
	namespace server {
		class CBaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CEnvEntityMaker : public CS2::server::CPointEntity {
		public:
			PROPERTY(m_vecEntityMins,GlobalTypes::Vector , 0x4f0);
			PROPERTY(m_vecEntityMaxs,GlobalTypes::Vector , 0x4fc);
			PROPERTY(m_hCurrentInstance,GlobalTypes::CHandle<server::CBaseEntity>, 0x508);
			PROPERTY(m_hCurrentBlocker,GlobalTypes::CHandle<server::CBaseEntity>, 0x50c);
			PROPERTY(m_vecBlockerOrigin,GlobalTypes::Vector , 0x510);
			PROPERTY(m_angPostSpawnDirection,GlobalTypes::QAngle , 0x51c);
			PROPERTY(m_flPostSpawnDirectionVariance,float32 , 0x528);
			PROPERTY(m_flPostSpawnSpeed,float32 , 0x52c);
			PROPERTY(m_bPostSpawnUseAngles,bool , 0x530);
			PROPERTY(m_iszTemplate,GlobalTypes::CUtlSymbolLarge* , 0x538);
			PROPERTY(m_pOutputOnSpawned,entity2::CEntityIOOutput , 0x540);
			PROPERTY(m_pOutputOnFailedSpawn,entity2::CEntityIOOutput , 0x568);
			S2_PAD(0xA0);
		};
		//static_assert(sizeof(CS2::server::CEnvEntityMaker) == 0x590, "CEnvEntityMaker size should be 0x590");
	}
}
