// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBeam.hpp>
#include <SDK/server/Touch_t.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>



namespace CS2 {
	namespace server {
		class CBaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CEnvBeam : public CS2::server::CBeam {
		public:
			PROPERTY(m_active,int32_t , 0x878);
			PROPERTY(m_spriteTexture,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>, 0x880);
			PROPERTY(m_iszStartEntity,GlobalTypes::CUtlSymbolLarge* , 0x888);
			PROPERTY(m_iszEndEntity,GlobalTypes::CUtlSymbolLarge* , 0x890);
			PROPERTY(m_life,float32 , 0x898);
			PROPERTY(m_boltWidth,float32 , 0x89c);
			PROPERTY(m_noiseAmplitude,float32 , 0x8a0);
			PROPERTY(m_speed,int32_t , 0x8a4);
			PROPERTY(m_restrike,float32 , 0x8a8);
			PROPERTY(m_iszSpriteName,GlobalTypes::CUtlSymbolLarge* , 0x8b0);
			PROPERTY(m_frameStart,int32_t , 0x8b8);
			PROPERTY(m_vEndPointWorld,GlobalTypes::VectorWS , 0x8bc);
			PROPERTY(m_vEndPointRelative,GlobalTypes::Vector , 0x8c8);
			PROPERTY(m_radius,float32 , 0x8d4);
			PROPERTY(m_TouchType,server::Touch_t , 0x8d8);
			PROPERTY(m_iFilterName,GlobalTypes::CUtlSymbolLarge* , 0x8e0);
			PROPERTY(m_hFilter,GlobalTypes::CHandle<server::CBaseEntity>, 0x8e8);
			PROPERTY(m_iszDecal,GlobalTypes::CUtlSymbolLarge* , 0x8f0);
			PROPERTY(m_OnTouchedByEntity,entity2::CEntityIOOutput , 0x8f8);
			S2_PAD(0xA8);
		};
		//static_assert(sizeof(CS2::server::CEnvBeam) == 0x920, "CEnvBeam size should be 0x920");
	}
}
