// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>



namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeIMaterial2;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CEnvSky : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_hSkyMaterial,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>, 0x7d8);
			PROPERTY(m_hSkyMaterialLightingOnly,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>, 0x7e0);
			PROPERTY(m_bStartDisabled,bool , 0x7e8);
			PROPERTY(m_vTintColor,GlobalTypes::Color , 0x7e9);
			PROPERTY(m_vTintColorLightingOnly,GlobalTypes::Color , 0x7ed);
			PROPERTY(m_flBrightnessScale,float32 , 0x7f4);
			PROPERTY(m_nFogType,int32_t , 0x7f8);
			PROPERTY(m_flFogMinStart,float32 , 0x7fc);
			PROPERTY(m_flFogMinEnd,float32 , 0x800);
			PROPERTY(m_flFogMaxStart,float32 , 0x804);
			PROPERTY(m_flFogMaxEnd,float32 , 0x808);
			PROPERTY(m_bEnabled,bool , 0x80c);
			S2_PAD(0x60);
		};
		//static_assert(sizeof(CS2::server::CEnvSky) == 0x838, "CEnvSky size should be 0x838");
	}
}
