// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CEnvSoundscape : public CS2::server::CBaseEntity {
		public:
			PROPERTY(m_OnPlay,entity2::CEntityIOOutput , 0x4f0);
			PROPERTY(m_flRadius,float32 , 0x518);
			PROPERTY(m_soundEventName,GlobalTypes::CUtlSymbolLarge* , 0x520);
			PROPERTY(m_bOverrideWithEvent,bool , 0x528);
			PROPERTY(m_soundscapeIndex,int32_t , 0x52c);
			PROPERTY(m_soundscapeEntityListId,int32_t , 0x530);
			PROPERTY_ARRAY(m_positionNames,GlobalTypes::CUtlSymbolLarge* , 8 , 0x538);
			PROPERTY(m_hProxySoundscape,GlobalTypes::CHandle<server::CEnvSoundscape>, 0x578);
			PROPERTY(m_bDisabled,bool , 0x57c);
			PROPERTY(m_soundscapeName,GlobalTypes::CUtlSymbolLarge* , 0x580);
			PROPERTY(m_soundEventHash,uint32_t , 0x588);
			S2_PAD(0xA0);
		};
		//static_assert(sizeof(CS2::server::CEnvSoundscape) == 0x590, "CEnvSoundscape size should be 0x590");
	}
}
