// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseEntity.hpp>
#include <SDK/entity2/GameTime_t.hpp>



namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeCTextureBase;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CEnvVolumetricFogController : public CS2::server::CBaseEntity {
		public:
			PROPERTY(m_flScattering,float32 , 0x4f0);
			PROPERTY(m_TintColor,GlobalTypes::Color , 0x4f4);
			PROPERTY(m_flAnisotropy,float32 , 0x4f8);
			PROPERTY(m_flFadeSpeed,float32 , 0x4fc);
			PROPERTY(m_flDrawDistance,float32 , 0x500);
			PROPERTY(m_flFadeInStart,float32 , 0x504);
			PROPERTY(m_flFadeInEnd,float32 , 0x508);
			PROPERTY(m_flIndirectStrength,float32 , 0x50c);
			PROPERTY(m_nVolumeDepth,int32_t , 0x510);
			PROPERTY(m_fFirstVolumeSliceThickness,float32 , 0x514);
			PROPERTY(m_nIndirectTextureDimX,int32_t , 0x518);
			PROPERTY(m_nIndirectTextureDimY,int32_t , 0x51c);
			PROPERTY(m_nIndirectTextureDimZ,int32_t , 0x520);
			PROPERTY(m_vBoxMins,GlobalTypes::Vector , 0x524);
			PROPERTY(m_vBoxMaxs,GlobalTypes::Vector , 0x530);
			PROPERTY(m_bActive,bool , 0x53c);
			PROPERTY(m_flStartAnisoTime,entity2::GameTime_t , 0x540);
			PROPERTY(m_flStartScatterTime,entity2::GameTime_t , 0x544);
			PROPERTY(m_flStartDrawDistanceTime,entity2::GameTime_t , 0x548);
			PROPERTY(m_flStartAnisotropy,float32 , 0x54c);
			PROPERTY(m_flStartScattering,float32 , 0x550);
			PROPERTY(m_flStartDrawDistance,float32 , 0x554);
			PROPERTY(m_flDefaultAnisotropy,float32 , 0x558);
			PROPERTY(m_flDefaultScattering,float32 , 0x55c);
			PROPERTY(m_flDefaultDrawDistance,float32 , 0x560);
			PROPERTY(m_bStartDisabled,bool , 0x564);
			PROPERTY(m_bEnableIndirect,bool , 0x565);
			PROPERTY(m_bIsMaster,bool , 0x566);
			PROPERTY(m_hFogIndirectTexture,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCTextureBase>, 0x568);
			PROPERTY(m_nForceRefreshCount,int32_t , 0x570);
			PROPERTY(m_fNoiseSpeed,float32 , 0x574);
			PROPERTY(m_fNoiseStrength,float32 , 0x578);
			PROPERTY(m_vNoiseScale,GlobalTypes::Vector , 0x57c);
			PROPERTY(m_fWindSpeed,float32 , 0x588);
			PROPERTY(m_vWindDirection,GlobalTypes::Vector , 0x58c);
			PROPERTY(m_bFirstTime,bool , 0x598);
			S2_PAD(0xB0);
		};
		//static_assert(sizeof(CS2::server::CEnvVolumetricFogController) == 0x5A0, "CEnvVolumetricFogController size should be 0x5A0");
	}
}
