// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CEnvCubemapFog : public CS2::server::CBaseEntity {
		public:
			PROPERTY(m_flEndDistance,float32 , 0x4f0);
			PROPERTY(m_flStartDistance,float32 , 0x4f4);
			PROPERTY(m_flFogFalloffExponent,float32 , 0x4f8);
			PROPERTY(m_bHeightFogEnabled,bool , 0x4fc);
			PROPERTY(m_flFogHeightWidth,float32 , 0x500);
			PROPERTY(m_flFogHeightEnd,float32 , 0x504);
			PROPERTY(m_flFogHeightStart,float32 , 0x508);
			PROPERTY(m_flFogHeightExponent,float32 , 0x50c);
			PROPERTY(m_flLODBias,float32 , 0x510);
			PROPERTY(m_bActive,bool , 0x514);
			PROPERTY(m_bStartDisabled,bool , 0x515);
			PROPERTY(m_flFogMaxOpacity,float32 , 0x518);
			PROPERTY(m_nCubemapSourceType,int32_t , 0x51c);
			PROPERTY(m_hSkyMaterial,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>, 0x520);
			PROPERTY(m_iszSkyEntity,GlobalTypes::CUtlSymbolLarge* , 0x528);
			PROPERTY(m_hFogCubemapTexture,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCTextureBase>, 0x530);
			PROPERTY(m_bHasHeightFogEnd,bool , 0x538);
			PROPERTY(m_bFirstTime,bool , 0x539);
			S2_PAD(0x50);
		};
		//static_assert(sizeof(CS2::server::CEnvCubemapFog) == 0x540, "CEnvCubemapFog size should be 0x540");
	}
}
