// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBeam.hpp>



namespace CS2 {
	namespace server {
		class CSprite;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CEnvLaser : public CS2::server::CBeam {
		public:
			PROPERTY(m_iszLaserTarget,GlobalTypes::CUtlSymbolLarge* , 0x878);
			PROPERTY(m_pSprite,server::CSprite* , 0x880);
			PROPERTY(m_iszSpriteName,GlobalTypes::CUtlSymbolLarge* , 0x888);
			PROPERTY(m_firePosition,GlobalTypes::Vector , 0x890);
			PROPERTY(m_flStartFrame,float32 , 0x89c);
			S2_PAD(0x28);
		};
		//static_assert(sizeof(CS2::server::CEnvLaser) == 0x8A0, "CEnvLaser size should be 0x8A0");
	}
}
