// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseFilter.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CFilterEnemy : public CS2::server::CBaseFilter {
		public:
			PROPERTY(m_iszEnemyName,GlobalTypes::CUtlSymbolLarge* , 0x548);
			PROPERTY(m_flRadius,float32 , 0x550);
			PROPERTY(m_flOuterRadius,float32 , 0x554);
			PROPERTY(m_nMaxSquadmatesPerEnemy,int32_t , 0x558);
			PROPERTY(m_iszPlayerName,GlobalTypes::CUtlSymbolLarge* , 0x560);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::server::CFilterEnemy) == 0x568, "CFilterEnemy size should be 0x568");
	}
}
