// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseFilter.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CFilterModel : public CS2::server::CBaseFilter {
		public:
			PROPERTY(m_iFilterModel,GlobalTypes::CUtlSymbolLarge* , 0x548);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::server::CFilterModel) == 0x550, "CFilterModel size should be 0x550");
	}
}
