// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CBaseModelEntity.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CFuncNavObstruction : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_bDisabled,bool, 0x748);
			PROPERTY(m_bUseAsyncObstacleUpdate,bool, 0x749);
			S2_PAD(0x20);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CFuncNavObstruction) == 0x750, "CFuncNavObstruction size should be 0x750");

#endif
	}
}
