// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/server/TrainOrientationType_t.hpp>
#include <SDK/server/TrainVelocityType_t.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>



namespace CS2 {
	namespace server {
		class CPathTrack;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CFuncTrackTrain : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_ppath,GlobalTypes::CHandle<server::CPathTrack>, 0x7d8);
			PROPERTY(m_length,float32 , 0x7dc);
			PROPERTY(m_vPosPrev,GlobalTypes::Vector , 0x7e0);
			PROPERTY(m_angPrev,GlobalTypes::QAngle , 0x7ec);
			PROPERTY(m_controlMins,GlobalTypes::Vector , 0x7f8);
			PROPERTY(m_controlMaxs,GlobalTypes::Vector , 0x804);
			PROPERTY(m_lastBlockPos,GlobalTypes::Vector , 0x810);
			PROPERTY(m_lastBlockTick,int32_t , 0x81c);
			PROPERTY(m_flVolume,float32 , 0x820);
			PROPERTY(m_flBank,float32 , 0x824);
			PROPERTY(m_oldSpeed,float32 , 0x828);
			PROPERTY(m_flBlockDamage,float32 , 0x82c);
			PROPERTY(m_height,float32 , 0x830);
			PROPERTY(m_maxSpeed,float32 , 0x834);
			PROPERTY(m_dir,float32 , 0x838);
			PROPERTY(m_iszSoundMove,GlobalTypes::CUtlSymbolLarge* , 0x840);
			PROPERTY(m_iszSoundMovePing,GlobalTypes::CUtlSymbolLarge* , 0x848);
			PROPERTY(m_iszSoundStart,GlobalTypes::CUtlSymbolLarge* , 0x850);
			PROPERTY(m_iszSoundStop,GlobalTypes::CUtlSymbolLarge* , 0x858);
			PROPERTY(m_strPathTarget,GlobalTypes::CUtlSymbolLarge* , 0x860);
			PROPERTY(m_flMoveSoundMinDuration,float32 , 0x868);
			PROPERTY(m_flMoveSoundMaxDuration,float32 , 0x86c);
			PROPERTY(m_flNextMoveSoundTime,entity2::GameTime_t , 0x870);
			PROPERTY(m_flMoveSoundMinPitch,float32 , 0x874);
			PROPERTY(m_flMoveSoundMaxPitch,float32 , 0x878);
			PROPERTY(m_eOrientationType,server::TrainOrientationType_t , 0x87c);
			PROPERTY(m_eVelocityType,server::TrainVelocityType_t , 0x880);
			PROPERTY(m_OnStart,entity2::CEntityIOOutput , 0x898);
			PROPERTY(m_OnNext,entity2::CEntityIOOutput , 0x8c0);
			PROPERTY(m_OnArrivedAtDestinationNode,entity2::CEntityIOOutput , 0x8e8);
			PROPERTY(m_bManualSpeedChanges,bool , 0x910);
			PROPERTY(m_flDesiredSpeed,float32 , 0x914);
			PROPERTY(m_flSpeedChangeTime,entity2::GameTime_t , 0x918);
			PROPERTY(m_flAccelSpeed,float32 , 0x91c);
			PROPERTY(m_flDecelSpeed,float32 , 0x920);
			PROPERTY(m_bAccelToSpeed,bool , 0x924);
			PROPERTY(m_flNextMPSoundTime,entity2::GameTime_t , 0x928);
			S2_PAD(0x158);
		};
		//static_assert(sizeof(CS2::server::CFuncTrackTrain) == 0x930, "CFuncTrackTrain size should be 0x930");
	}
}
