// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>
#include <SDK/server/CBuoyancyHelper.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CFuncWater : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_BuoyancyHelper,server::CBuoyancyHelper , 0x7d8);
			S2_PAD(0x118);
		};
		//static_assert(sizeof(CS2::server::CFuncWater) == 0x8F0, "CFuncWater size should be 0x8F0");
	}
}
