// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CFuncShatterglass : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_matPanelTransform,GlobalTypes::matrix3x4_t , 0x7d8);
			PROPERTY(m_matPanelTransformWsTemp,GlobalTypes::matrix3x4_t , 0x808);
			PROPERTY(m_vecShatterGlassShards,GlobalTypes::CUtlVector< uint32 >, 0x838);
			PROPERTY(m_PanelSize,GlobalTypes::Vector2D , 0x850);
			PROPERTY(m_flLastShatterSoundEmitTime,entity2::GameTime_t , 0x858);
			PROPERTY(m_flLastCleanupTime,entity2::GameTime_t , 0x85c);
			PROPERTY(m_flInitAtTime,entity2::GameTime_t , 0x860);
			PROPERTY(m_flGlassThickness,float32 , 0x864);
			PROPERTY(m_flSpawnInvulnerability,float32 , 0x868);
			PROPERTY(m_bBreakSilent,bool , 0x86c);
			PROPERTY(m_bBreakShardless,bool , 0x86d);
			PROPERTY(m_bBroken,bool , 0x86e);
			PROPERTY(m_bGlassNavIgnore,bool , 0x86f);
			PROPERTY(m_bGlassInFrame,bool , 0x870);
			PROPERTY(m_bStartBroken,bool , 0x871);
			PROPERTY(m_iInitialDamageType,uint8_t , 0x872);
			PROPERTY(m_szDamagePositioningEntityName01,GlobalTypes::CUtlSymbolLarge* , 0x878);
			PROPERTY(m_szDamagePositioningEntityName02,GlobalTypes::CUtlSymbolLarge* , 0x880);
			PROPERTY(m_szDamagePositioningEntityName03,GlobalTypes::CUtlSymbolLarge* , 0x888);
			PROPERTY(m_szDamagePositioningEntityName04,GlobalTypes::CUtlSymbolLarge* , 0x890);
			PROPERTY(m_vInitialDamagePositions,GlobalTypes::CUtlVector<GlobalTypes::Vector>, 0x898);
			PROPERTY(m_vExtraDamagePositions,GlobalTypes::CUtlVector<GlobalTypes::Vector>, 0x8b0);
			PROPERTY(m_vInitialPanelVertices,GlobalTypes::CUtlVector<GlobalTypes::Vector4D>, 0x8c8);
			PROPERTY(m_OnBroken,entity2::CEntityIOOutput , 0x8e0);
			PROPERTY(m_iSurfaceType,uint8_t , 0x908);
			PROPERTY(m_hMaterialDamageBase,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>, 0x910);
			S2_PAD(0x140);
		};
		//static_assert(sizeof(CS2::server::CFuncShatterglass) == 0x918, "CFuncShatterglass size should be 0x918");
	}
}
