// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CFuncPlatRot.hpp"
#include "TRAIN_CODE.hpp"



namespace CS2 {
	namespace server {
		class CPathTrack;
		class CFuncTrackTrain;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CFuncTrackChange : public CS2::server::CFuncPlatRot {
		public:
			PROPERTY(m_trackTop,IDENTITY(server::CPathTrack*), 0x7f8);
			PROPERTY(m_trackBottom,IDENTITY(server::CPathTrack*), 0x800);
			PROPERTY(m_train,IDENTITY(server::CFuncTrackTrain*), 0x808);
			PROPERTY(m_trackTopName,GlobalTypes::CUtlSymbolLarge*, 0x810);
			PROPERTY(m_trackBottomName,GlobalTypes::CUtlSymbolLarge*, 0x818);
			PROPERTY(m_trainName,GlobalTypes::CUtlSymbolLarge*, 0x820);
			PROPERTY(m_code,IDENTITY(server::TRAIN_CODE), 0x828);
			PROPERTY(m_targetState,int32_t, 0x82c);
			PROPERTY(m_use,int32_t, 0x830);
			S2_PAD(0x40);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CFuncTrackChange) == 0x838, "CFuncTrackChange size should be 0x838");

#endif
	}
}
