// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CRulePointEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CGameMoney : public CS2::server::CRulePointEntity {
		public:
			PROPERTY(m_OnMoneySpent,entity2::CEntityIOOutput , 0x7e8);
			PROPERTY(m_OnMoneySpentFail,entity2::CEntityIOOutput , 0x810);
			PROPERTY(m_nMoney,int32_t , 0x838);
			PROPERTY(m_strAwardText,GlobalTypes::CUtlString* , 0x840);
			S2_PAD(0x60);
		};
		//static_assert(sizeof(CS2::server::CGameMoney) == 0x848, "CGameMoney size should be 0x848");
	}
}
