// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseToggle.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>



namespace CS2 {
	namespace server {
		class CBaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CGunTarget : public CS2::server::CBaseToggle {
		public:
			PROPERTY(m_on,bool , 0x858);
			PROPERTY(m_hTargetEnt,GlobalTypes::CHandle<server::CBaseEntity>, 0x85c);
			PROPERTY(m_OnDeath,entity2::CEntityIOOutput , 0x860);
			S2_PAD(0x30);
		};
		//static_assert(sizeof(CS2::server::CGunTarget) == 0x888, "CGunTarget size should be 0x888");
	}
}
