// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CHostageExpresserShim.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>
#include <SDK/server/EntitySpottedState_t.hpp>
#include <SDK/server/CountdownTimer.hpp>
#include <SDK/entity2/GameTime_t.hpp>



namespace CS2 {
	namespace server {
		class CBaseEntity;
		class CCSPlayerPawnBase;
		class CCSPlayerPawn;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CHostage : public CS2::server::CHostageExpresserShim {
		public:
			PROPERTY(m_OnHostageBeginGrab,entity2::CEntityIOOutput , 0xc08);
			PROPERTY(m_OnFirstPickedUp,entity2::CEntityIOOutput , 0xc30);
			PROPERTY(m_OnDroppedNotRescued,entity2::CEntityIOOutput , 0xc58);
			PROPERTY(m_OnRescued,entity2::CEntityIOOutput , 0xc80);
			PROPERTY(m_entitySpottedState,server::EntitySpottedState_t , 0xca8);
			PROPERTY(m_nSpotRules,int32_t , 0xcc0);
			PROPERTY(m_uiHostageSpawnExclusionGroupMask,uint32_t , 0xcc4);
			PROPERTY(m_nHostageSpawnRandomFactor,uint32_t , 0xcc8);
			PROPERTY(m_bRemove,bool , 0xccc);
			PROPERTY(m_vel,GlobalTypes::Vector , 0xcd0);
			PROPERTY(m_isRescued,bool , 0xcdc);
			PROPERTY(m_jumpedThisFrame,bool , 0xcdd);
			PROPERTY(m_nHostageState,int32_t , 0xce0);
			PROPERTY(m_leader,GlobalTypes::CHandle<server::CBaseEntity>, 0xce4);
			PROPERTY(m_lastLeader,GlobalTypes::CHandle<server::CCSPlayerPawnBase>, 0xce8);
			PROPERTY(m_reuseTimer,server::CountdownTimer , 0xcf0);
			PROPERTY(m_hasBeenUsed,bool , 0xd08);
			PROPERTY(m_accel,GlobalTypes::Vector , 0xd0c);
			PROPERTY(m_isRunning,bool , 0xd18);
			PROPERTY(m_isCrouching,bool , 0xd19);
			PROPERTY(m_jumpTimer,server::CountdownTimer , 0xd20);
			PROPERTY(m_isWaitingForLeader,bool , 0xd38);
			PROPERTY(m_repathTimer,server::CountdownTimer , 0x2d48);
			PROPERTY(m_inhibitDoorTimer,server::CountdownTimer , 0x2d60);
			PROPERTY(m_inhibitObstacleAvoidanceTimer,server::CountdownTimer , 0x2df0);
			PROPERTY(m_wiggleTimer,server::CountdownTimer , 0x2e10);
			PROPERTY(m_isAdjusted,bool , 0x2e2c);
			PROPERTY(m_bHandsHaveBeenCut,bool , 0x2e2d);
			PROPERTY(m_hHostageGrabber,GlobalTypes::CHandle<server::CCSPlayerPawn>, 0x2e30);
			PROPERTY(m_fLastGrabTime,entity2::GameTime_t , 0x2e34);
			PROPERTY(m_vecPositionWhenStartedDroppingToGround,GlobalTypes::Vector , 0x2e38);
			PROPERTY(m_vecGrabbedPos,GlobalTypes::Vector , 0x2e44);
			PROPERTY(m_flRescueStartTime,entity2::GameTime_t , 0x2e50);
			PROPERTY(m_flGrabSuccessTime,entity2::GameTime_t , 0x2e54);
			PROPERTY(m_flDropStartTime,entity2::GameTime_t , 0x2e58);
			PROPERTY(m_nApproachRewardPayouts,int32_t , 0x2e5c);
			PROPERTY(m_nPickupEventCount,int32_t , 0x2e60);
			PROPERTY(m_vecSpawnGroundPos,GlobalTypes::Vector , 0x2e64);
			PROPERTY(m_vecHostageResetPosition,GlobalTypes::VectorWS , 0x2e9c);
			S2_PAD(0x22C0);
		};
		//static_assert(sizeof(CS2::server::CHostage) == 0x2EB0, "CHostage size should be 0x2EB0");
	}
}
