// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseAnimGraph.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CItem : public CS2::server::CBaseAnimGraph {
		public:
			PROPERTY(m_OnPlayerTouch,entity2::CEntityIOOutput , 0xa98);
			PROPERTY(m_OnPlayerPickup,entity2::CEntityIOOutput , 0xac0);
			PROPERTY(m_bActivateWhenAtRest,bool , 0xae8);
			PROPERTY(m_OnCacheInteraction,entity2::CEntityIOOutput , 0xaf0);
			PROPERTY(m_OnGlovePulled,entity2::CEntityIOOutput , 0xb18);
			PROPERTY(m_vOriginalSpawnOrigin,GlobalTypes::VectorWS , 0xb40);
			PROPERTY(m_vOriginalSpawnAngles,GlobalTypes::QAngle , 0xb4c);
			PROPERTY(m_bPhysStartAsleep,bool , 0xb58);
			S2_PAD(0xE0);
		};
		//static_assert(sizeof(CS2::server::CItem) == 0xB70, "CItem size should be 0xB70");
	}
}
