// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLogicalEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CLogicCase : public CS2::server::CLogicalEntity {
		public:
			PROPERTY_ARRAY(m_nCase,GlobalTypes::CUtlSymbolLarge* , 32 , 0x4f0);
			PROPERTY(m_nShuffleCases,int32_t , 0x5f0);
			PROPERTY(m_nLastShuffleCase,int32_t , 0x5f4);
			PROPERTY_ARRAY(m_uchShuffleCaseMap,uint8_t , 32 , 0x5f8);
			PROPERTY_ARRAY(m_OnCase,entity2::CEntityIOOutput , 32 , 0x618);
			PROPERTY(m_OnDefault,GlobalTypes::CEntityOutputTemplate<GlobalTypes::CVariantBase<entity2::CVariantDefaultAllocator>>, 0xb18);
			S2_PAD(0x650);
		};
		//static_assert(sizeof(CS2::server::CLogicCase) == 0xB40, "CLogicCase size should be 0xB40");
	}
}
