// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLogicalEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CLogicBranch : public CS2::server::CLogicalEntity {
		public:
			PROPERTY(m_bInValue,bool , 0x4f0);
			PROPERTY(m_Listeners,server::CUtlVector<GlobalTypes::CHandle<server::CBaseEntity>>, 0x4f8);
			PROPERTY(m_OnTrue,entity2::CEntityIOOutput , 0x510);
			PROPERTY(m_OnFalse,entity2::CEntityIOOutput , 0x538);
			S2_PAD(0x70);
		};
		//static_assert(sizeof(CS2::server::CLogicBranch) == 0x560, "CLogicBranch size should be 0x560");
	}
}
