// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLogicalEntity.hpp>
#include <SDK/server/navproperties_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CLogicNavigation : public CS2::server::CLogicalEntity {
		public:
			PROPERTY(m_isOn,bool , 0x4f8);
			PROPERTY(m_navProperty,server::navproperties_t , 0x4fc);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::server::CLogicNavigation) == 0x500, "CLogicNavigation size should be 0x500");
	}
}
