// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLogicalEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CLogicGameEventListener : public CS2::server::CLogicalEntity {
		public:
			PROPERTY(m_OnEventFired,entity2::CEntityIOOutput , 0x500);
			PROPERTY(m_iszGameEventName,GlobalTypes::CUtlSymbolLarge* , 0x528);
			PROPERTY(m_iszGameEventItem,GlobalTypes::CUtlSymbolLarge* , 0x530);
			PROPERTY(m_bEnabled,bool , 0x538);
			PROPERTY(m_bStartDisabled,bool , 0x539);
			S2_PAD(0x50);
		};
		//static_assert(sizeof(CS2::server::CLogicGameEventListener) == 0x540, "CLogicGameEventListener size should be 0x540");
	}
}
