// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CMarkupVolumeTagged.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CMarkupVolumeWithRef : public CS2::server::CMarkupVolumeTagged {
		public:
			PROPERTY(m_bUseRef,bool, 0x778);
			PROPERTY(m_vRefPosEntitySpace,GlobalTypes::Vector, 0x77c);
			PROPERTY(m_vRefPosWorldSpace,GlobalTypes::VectorWS, 0x788);
			PROPERTY(m_flRefDot,float32, 0x794);
			S2_PAD(0x28);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CMarkupVolumeWithRef) == 0x798, "CMarkupVolumeWithRef size should be 0x798");

#endif
	}
}
