// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLogicalEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CMathColorBlend : public CS2::server::CLogicalEntity {
		public:
			PROPERTY(m_flInMin,float32 , 0x4f0);
			PROPERTY(m_flInMax,float32 , 0x4f4);
			PROPERTY(m_OutColor1,GlobalTypes::Color , 0x4f8);
			PROPERTY(m_OutColor2,GlobalTypes::Color , 0x4fc);
			PROPERTY(m_OutValue,GlobalTypes::CEntityOutputTemplate<GlobalTypes::Color>, 0x500);
			S2_PAD(0x38);
		};
		//static_assert(sizeof(CS2::server::CMathColorBlend) == 0x528, "CMathColorBlend size should be 0x528");
	}
}
