// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPointEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CMessage : public CS2::server::CPointEntity {
		public:
			PROPERTY(m_iszMessage,GlobalTypes::CUtlSymbolLarge* , 0x4f0);
			PROPERTY(m_MessageVolume,float32 , 0x4f8);
			PROPERTY(m_MessageAttenuation,int32_t , 0x4fc);
			PROPERTY(m_Radius,float32 , 0x500);
			PROPERTY(m_sNoise,GlobalTypes::CUtlSymbolLarge* , 0x508);
			PROPERTY(m_OnShowMessage,entity2::CEntityIOOutput , 0x510);
			S2_PAD(0x48);
		};
		//static_assert(sizeof(CS2::server::CMessage) == 0x538, "CMessage size should be 0x538");
	}
}
