// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CBaseCSGrenadeProjectile.hpp"
#include "IntervalTimer.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CMolotovProjectile : public CS2::server::CBaseCSGrenadeProjectile {
		public:
			PROPERTY(m_bIsIncGrenade,bool, 0xbb0);
			PROPERTY(m_bDetonated,bool, 0xbc8);
			NESTED_PROPERTY(m_stillTimer,IDENTITY(server::IntervalTimer), 0xbd0);
			S2_PAD(0x100);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CMolotovProjectile) == 0xCB0, "CMolotovProjectile size should be 0xCB0");

#endif
	}
}
