// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseCSGrenadeProjectile.hpp>
#include <SDK/server/IntervalTimer.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CMolotovProjectile : public CS2::server::CBaseCSGrenadeProjectile {
		public:
			PROPERTY(m_bIsIncGrenade,bool , 0xbb0);
			PROPERTY(m_bDetonated,bool , 0xbc8);
			PROPERTY(m_stillTimer,server::IntervalTimer , 0xbd0);
			PROPERTY(m_bHasBouncedOffPlayer,bool , 0xcb0);
			S2_PAD(0x110);
		};
		//static_assert(sizeof(CS2::server::CMolotovProjectile) == 0xCC0, "CMolotovProjectile size should be 0xCC0");
	}
}
