// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLogicalEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CMultiLightProxy : public CS2::server::CLogicalEntity {
		public:
			PROPERTY(m_iszLightNameFilter,GlobalTypes::CUtlSymbolLarge* , 0x4f0);
			PROPERTY(m_iszLightClassFilter,GlobalTypes::CUtlSymbolLarge* , 0x4f8);
			PROPERTY(m_flLightRadiusFilter,float32 , 0x500);
			PROPERTY(m_flBrightnessDelta,float32 , 0x504);
			PROPERTY(m_bPerformScreenFade,bool , 0x508);
			PROPERTY(m_flTargetBrightnessMultiplier,float32 , 0x50c);
			PROPERTY(m_flCurrentBrightnessMultiplier,float32 , 0x510);
			PROPERTY(m_vecLights,server::CUtlVector<GlobalTypes::CHandle<server::CLightEntity>>, 0x518);
			S2_PAD(0x40);
		};
		//static_assert(sizeof(CS2::server::CMultiLightProxy) == 0x530, "CMultiLightProxy size should be 0x530");
	}
}
