// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPointEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPhysExplosion : public CS2::server::CPointEntity {
		public:
			PROPERTY(m_bExplodeOnSpawn,bool , 0x4f0);
			PROPERTY(m_flMagnitude,float32 , 0x4f4);
			PROPERTY(m_flDamage,float32 , 0x4f8);
			PROPERTY(m_radius,float32 , 0x4fc);
			PROPERTY(m_targetEntityName,GlobalTypes::CUtlSymbolLarge* , 0x500);
			PROPERTY(m_flInnerRadius,float32 , 0x508);
			PROPERTY(m_flPushScale,float32 , 0x50c);
			PROPERTY(m_bConvertToDebrisWhenPossible,bool , 0x510);
			PROPERTY(m_bAffectInvulnerableEnts,bool , 0x511);
			PROPERTY(m_OnPushedPlayer,entity2::CEntityIOOutput , 0x518);
			S2_PAD(0x50);
		};
		//static_assert(sizeof(CS2::server::CPhysExplosion) == 0x540, "CPhysExplosion size should be 0x540");
	}
}
