// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CPhysicsProp.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPhysicsPropRespawnable : public CS2::server::CPhysicsProp {
		public:
			PROPERTY(m_vOriginalSpawnOrigin,GlobalTypes::VectorWS, 0xce0);
			PROPERTY(m_vOriginalSpawnAngles,GlobalTypes::QAngle, 0xcec);
			PROPERTY(m_vOriginalMins,GlobalTypes::Vector, 0xcf8);
			PROPERTY(m_vOriginalMaxs,GlobalTypes::Vector, 0xd04);
			PROPERTY(m_flRespawnDuration,float32, 0xd10);
			S2_PAD(0x40);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CPhysicsPropRespawnable) == 0xD20, "CPhysicsPropRespawnable size should be 0xD20");

#endif
	}
}
