// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPhysConstraint.hpp>
#include <SDK/server/ConstraintSoundInfo.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPhysSlideConstraint : public CS2::server::CPhysConstraint {
		public:
			PROPERTY(m_axisEnd,GlobalTypes::VectorWS , 0x568);
			PROPERTY(m_slideFriction,float32 , 0x574);
			PROPERTY(m_systemLoadScale,float32 , 0x578);
			PROPERTY(m_initialOffset,float32 , 0x57c);
			PROPERTY(m_bEnableLinearConstraint,bool , 0x580);
			PROPERTY(m_bEnableAngularConstraint,bool , 0x581);
			PROPERTY(m_flMotorFrequency,float32 , 0x584);
			PROPERTY(m_flMotorDampingRatio,float32 , 0x588);
			PROPERTY(m_bUseEntityPivot,bool , 0x58c);
			PROPERTY(m_soundInfo,server::ConstraintSoundInfo , 0x590);
			S2_PAD(0xC8);
		};
		//static_assert(sizeof(CS2::server::CPhysSlideConstraint) == 0x628, "CPhysSlideConstraint size should be 0x628");
	}
}
