// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLogicalEntity.hpp>
#include <SDK/server/CMotorController.hpp>



namespace CS2 {
	namespace server {
		class CBaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPhysMotor : public CS2::server::CLogicalEntity {
		public:
			PROPERTY(m_nameAttach,GlobalTypes::CUtlSymbolLarge* , 0x4f0);
			PROPERTY(m_nameAnchor,GlobalTypes::CUtlSymbolLarge* , 0x4f8);
			PROPERTY(m_hAttachedObject,GlobalTypes::CHandle<server::CBaseEntity>, 0x500);
			PROPERTY(m_hAnchorObject,GlobalTypes::CHandle<server::CBaseEntity>, 0x504);
			PROPERTY(m_spinUp,float32 , 0x508);
			PROPERTY(m_spinDown,float32 , 0x50c);
			PROPERTY(m_flMotorFriction,float32 , 0x510);
			PROPERTY(m_additionalAcceleration,float32 , 0x514);
			PROPERTY(m_angularAcceleration,float32 , 0x518);
			PROPERTY(m_flTorqueScale,float32 , 0x51c);
			PROPERTY(m_flTargetSpeed,float32 , 0x520);
			PROPERTY(m_flSpeedWhenSpinUpOrSpinDownStarted,float32 , 0x524);
			PROPERTY(m_motor,server::CMotorController , 0x538);
			S2_PAD(0x68);
		};
		//static_assert(sizeof(CS2::server::CPhysMotor) == 0x558, "CPhysMotor size should be 0x558");
	}
}
