// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBreakableProp.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/physicslib/DynamicContinuousContactBehavior_t.hpp>
#include <SDK/server/CrateType_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPhysicsProp : public CS2::server::CBreakableProp {
		public:
			PROPERTY(m_MotionEnabled,entity2::CEntityIOOutput , 0xc60);
			PROPERTY(m_OnAwakened,entity2::CEntityIOOutput , 0xc88);
			PROPERTY(m_OnAwake,entity2::CEntityIOOutput , 0xcb0);
			PROPERTY(m_OnAsleep,entity2::CEntityIOOutput , 0xcd8);
			PROPERTY(m_OnPlayerUse,entity2::CEntityIOOutput , 0xd00);
			PROPERTY(m_OnOutOfWorld,entity2::CEntityIOOutput , 0xd28);
			PROPERTY(m_OnPlayerPickup,entity2::CEntityIOOutput , 0xd50);
			PROPERTY(m_bForceNavIgnore,bool , 0xd78);
			PROPERTY(m_bNoNavmeshBlocker,bool , 0xd79);
			PROPERTY(m_bForceNpcExclude,bool , 0xd7a);
			PROPERTY(m_massScale,float32 , 0xd7c);
			PROPERTY(m_buoyancyScale,float32 , 0xd80);
			PROPERTY(m_damageType,int32_t , 0xd84);
			PROPERTY(m_damageToEnableMotion,int32_t , 0xd88);
			PROPERTY(m_flForceToEnableMotion,float32 , 0xd8c);
			PROPERTY(m_bThrownByPlayer,bool , 0xd90);
			PROPERTY(m_bDroppedByPlayer,bool , 0xd91);
			PROPERTY(m_bTouchedByPlayer,bool , 0xd92);
			PROPERTY(m_bFirstCollisionAfterLaunch,bool , 0xd93);
			PROPERTY(m_bHasBeenAwakened,bool , 0xd94);
			PROPERTY(m_bIsOverrideProp,bool , 0xd95);
			PROPERTY(m_flLastBurn,entity2::GameTime_t , 0xd98);
			PROPERTY(m_nDynamicContinuousContactBehavior,physicslib::DynamicContinuousContactBehavior_t , 0xd9c);
			PROPERTY(m_fNextCheckDisableMotionContactsTime,entity2::GameTime_t , 0xda0);
			PROPERTY(m_iInitialGlowState,int32_t , 0xda4);
			PROPERTY(m_nGlowRange,int32_t , 0xda8);
			PROPERTY(m_nGlowRangeMin,int32_t , 0xdac);
			PROPERTY(m_glowColor,GlobalTypes::Color , 0xdb0);
			PROPERTY(m_bShouldAutoConvertBackFromDebris,bool , 0xdb4);
			PROPERTY(m_bMuteImpactEffects,bool , 0xdb5);
			PROPERTY(m_bAcceptDamageFromHeldObjects,bool , 0xdbf);
			PROPERTY(m_bEnableUseOutput,bool , 0xdc0);
			PROPERTY(m_CrateType,server::CrateType_t , 0xdc4);
			PROPERTY_ARRAY(m_strItemClass,GlobalTypes::CUtlSymbolLarge* , 4 , 0xdc8);
			PROPERTY_ARRAY(m_nItemCount,int32_t , 4 , 0xde8);
			PROPERTY(m_bRemovableForAmmoBalancing,bool , 0xdf8);
			PROPERTY(m_bAwake,bool , 0xdf9);
			PROPERTY(m_bAttachedToReferenceFrame,bool , 0xdfa);
			S2_PAD(0x1B0);
		};
		//static_assert(sizeof(CS2::server::CPhysicsProp) == 0xE00, "CPhysicsProp size should be 0xE00");
	}
}
