// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPhysConstraint.hpp>



namespace CS2 {
	namespace server {
		class CBaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPhysWheelConstraint : public CS2::server::CPhysConstraint {
		public:
			PROPERTY(m_flSuspensionFrequency,float32 , 0x560);
			PROPERTY(m_flSuspensionDampingRatio,float32 , 0x564);
			PROPERTY(m_flSuspensionHeightOffset,float32 , 0x568);
			PROPERTY(m_bEnableSuspensionLimit,bool , 0x56c);
			PROPERTY(m_flMinSuspensionOffset,float32 , 0x570);
			PROPERTY(m_flMaxSuspensionOffset,float32 , 0x574);
			PROPERTY(m_bEnableSteeringLimit,bool , 0x578);
			PROPERTY(m_flMinSteeringAngle,float32 , 0x57c);
			PROPERTY(m_flMaxSteeringAngle,float32 , 0x580);
			PROPERTY(m_flSteeringAxisFriction,float32 , 0x584);
			PROPERTY(m_flSpinAxisFriction,float32 , 0x588);
			PROPERTY(m_hSteeringMimicsEntity,GlobalTypes::CHandle<server::CBaseEntity>, 0x58c);
			S2_PAD(0x38);
		};
		//static_assert(sizeof(CS2::server::CPhysWheelConstraint) == 0x598, "CPhysWheelConstraint size should be 0x598");
	}
}
