// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPointEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPhysImpact : public CS2::server::CPointEntity {
		public:
			PROPERTY(m_damage,float32 , 0x4f0);
			PROPERTY(m_distance,float32 , 0x4f4);
			PROPERTY(m_directionEntityName,GlobalTypes::CUtlSymbolLarge* , 0x4f8);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::server::CPhysImpact) == 0x500, "CPhysImpact size should be 0x500");
	}
}
