// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CPlayerPawnComponent.hpp>
#include <SDK/client/ObserverMode_t.hpp>



namespace CS2 {
	namespace server {
		class CBaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPlayer_ObserverServices : public CS2::client::CPlayerPawnComponent {
		public:
			PROPERTY(m_iObserverMode,uint8_t , 0x40);
			PROPERTY(m_hObserverTarget,GlobalTypes::CHandle<server::CBaseEntity>, 0x44);
			PROPERTY(m_iObserverLastMode,client::ObserverMode_t , 0x48);
			PROPERTY(m_bForcedObserverMode,bool , 0x4c);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::server::CPlayer_ObserverServices) == 0x50, "CPlayer_ObserverServices size should be 0x50");
	}
}
