// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseAnimGraph.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/server/CAttributeContainer.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>
#include <SDK/server/EntitySpottedState_t.hpp>



namespace CS2 {
	namespace server {
		class CCSPlayerPawn;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPlantedC4 : public CS2::server::CBaseAnimGraph {
		public:
			PROPERTY(m_bBombTicking,bool , 0xa98);
			PROPERTY(m_flC4Blow,entity2::GameTime_t , 0xa9c);
			PROPERTY(m_nBombSite,int32_t , 0xaa0);
			PROPERTY(m_nSourceSoundscapeHash,int32_t , 0xaa4);
			PROPERTY(m_bAbortDetonationBecauseWorldIsFrozen,bool , 0xaa8);
			PROPERTY(m_AttributeManager,server::CAttributeContainer , 0xab0);
			PROPERTY(m_OnBombDefused,entity2::CEntityIOOutput , 0xda8);
			PROPERTY(m_OnBombBeginDefuse,entity2::CEntityIOOutput , 0xdd0);
			PROPERTY(m_OnBombDefuseAborted,entity2::CEntityIOOutput , 0xdf8);
			PROPERTY(m_bCannotBeDefused,bool , 0xe20);
			PROPERTY(m_entitySpottedState,server::EntitySpottedState_t , 0xe28);
			PROPERTY(m_nSpotRules,int32_t , 0xe40);
			PROPERTY(m_bTrainingPlacedByPlayer,bool , 0xe44);
			PROPERTY(m_bHasExploded,bool , 0xe45);
			PROPERTY(m_flTimerLength,float32 , 0xe48);
			PROPERTY(m_bBeingDefused,bool , 0xe4c);
			PROPERTY(m_fLastDefuseTime,entity2::GameTime_t , 0xe54);
			PROPERTY(m_flDefuseLength,float32 , 0xe5c);
			PROPERTY(m_flDefuseCountDown,entity2::GameTime_t , 0xe60);
			PROPERTY(m_bBombDefused,bool , 0xe64);
			PROPERTY(m_hBombDefuser,GlobalTypes::CHandle<server::CCSPlayerPawn>, 0xe68);
			PROPERTY(m_iProgressBarTime,int32_t , 0xe6c);
			PROPERTY(m_bVoiceAlertFired,bool , 0xe70);
			PROPERTY_ARRAY(m_bVoiceAlertPlayed,bool , 4 , 0xe71);
			PROPERTY(m_flNextBotBeepTime,entity2::GameTime_t , 0xe78);
			PROPERTY(m_angCatchUpToPlayerEye,GlobalTypes::QAngle , 0xe80);
			PROPERTY(m_flLastSpinDetectionTime,entity2::GameTime_t , 0xe8c);
			S2_PAD(0x400);
		};
		//static_assert(sizeof(CS2::server::CPlantedC4) == 0xE90, "CPlantedC4 size should be 0xE90");
	}
}
