// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CServerOnlyPointEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPointPrefab : public CS2::server::CServerOnlyPointEntity {
		public:
			PROPERTY(m_targetMapName,GlobalTypes::CUtlSymbolLarge* , 0x4f0);
			PROPERTY(m_forceWorldGroupID,GlobalTypes::CUtlSymbolLarge* , 0x4f8);
			PROPERTY(m_associatedRelayTargetName,GlobalTypes::CUtlSymbolLarge* , 0x500);
			PROPERTY(m_fixupNames,bool , 0x508);
			PROPERTY(m_bLoadDynamic,bool , 0x509);
			PROPERTY(m_associatedRelayEntity,GlobalTypes::CHandle<server::CPointPrefab>, 0x50c);
			S2_PAD(0x68);
		};
		//static_assert(sizeof(CS2::server::CPointPrefab) == 0x558, "CPointPrefab size should be 0x558");
	}
}
