// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPointEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPointGamestatsCounter : public CS2::server::CPointEntity {
		public:
			PROPERTY(m_strStatisticName,GlobalTypes::CUtlSymbolLarge* , 0x4f0);
			PROPERTY(m_bDisabled,bool , 0x4f8);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::server::CPointGamestatsCounter) == 0x500, "CPointGamestatsCounter size should be 0x500");
	}
}
