// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CPointClientUIWorldPanel.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPointClientUIWorldTextPanel : public CS2::server::CPointClientUIWorldPanel {
		public:
			PROPERTY_ARRAY(m_messageText,char, 512 , 0x8e8);
			S2_PAD(0x200);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CPointClientUIWorldTextPanel) == 0xAE8, "CPointClientUIWorldTextPanel size should be 0xAE8");

#endif
	}
}
