// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPointEntity.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>



namespace CS2 {
	namespace server {
		class CBaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPointAngleSensor : public CS2::server::CPointEntity {
		public:
			PROPERTY(m_bDisabled,bool , 0x4f0);
			PROPERTY(m_nLookAtName,GlobalTypes::CUtlSymbolLarge* , 0x4f8);
			PROPERTY(m_hTargetEntity,GlobalTypes::CHandle<server::CBaseEntity>, 0x500);
			PROPERTY(m_hLookAtEntity,GlobalTypes::CHandle<server::CBaseEntity>, 0x504);
			PROPERTY(m_flDuration,float32 , 0x508);
			PROPERTY(m_flDotTolerance,float32 , 0x50c);
			PROPERTY(m_flFacingTime,entity2::GameTime_t , 0x510);
			PROPERTY(m_bFired,bool , 0x514);
			PROPERTY(m_OnFacingLookat,entity2::CEntityIOOutput , 0x518);
			PROPERTY(m_OnNotFacingLookat,entity2::CEntityIOOutput , 0x540);
			PROPERTY(m_TargetDir,GlobalTypes::CEntityOutputTemplate<GlobalTypes::Vector>, 0x568);
			PROPERTY(m_FacingPercentage,GlobalTypes::CEntityOutputTemplate< float32 >, 0x590);
			S2_PAD(0xC8);
		};
		//static_assert(sizeof(CS2::server::CPointAngleSensor) == 0x5B8, "CPointAngleSensor size should be 0x5B8");
	}
}
