// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPulseCell_Outflow_PlaySceneBase.hpp>



namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeCChoreoSceneResource;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPulseCell_Outflow_PlayVCD : public CS2::server::CPulseCell_Outflow_PlaySceneBase {
		public:
			PROPERTY(m_hChoreoScene,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCChoreoSceneResource>, 0xf0);
			S2_PAD(0x8);
		};
		//static_assert(sizeof(CS2::server::CPulseCell_Outflow_PlayVCD) == 0xF8, "CPulseCell_Outflow_PlayVCD size should be 0xF8");
	}
}
