// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPhysConstraint.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CRagdollConstraint : public CS2::server::CPhysConstraint {
		public:
			PROPERTY(m_xmin,float32 , 0x560);
			PROPERTY(m_xmax,float32 , 0x564);
			PROPERTY(m_ymin,float32 , 0x568);
			PROPERTY(m_ymax,float32 , 0x56c);
			PROPERTY(m_zmin,float32 , 0x570);
			PROPERTY(m_zmax,float32 , 0x574);
			PROPERTY(m_xfriction,float32 , 0x578);
			PROPERTY(m_yfriction,float32 , 0x57c);
			PROPERTY(m_zfriction,float32 , 0x580);
			S2_PAD(0x28);
		};
		//static_assert(sizeof(CS2::server::CRagdollConstraint) == 0x588, "CRagdollConstraint size should be 0x588");
	}
}
