// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CBarnLight.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CRectLight : public CS2::server::CBarnLight {
		public:
			PROPERTY(m_bShowLight,bool, 0xa20);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CRectLight) == 0xA28, "CRectLight size should be 0xA28");

#endif
	}
}
