// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CSAdditionalPerRoundStats_t  {
		public:
			PROPERTY(m_numChickensKilled,int32_t , 0x0);
			PROPERTY(m_killsWhileBlind,int32_t , 0x4);
			PROPERTY(m_bombCarrierkills,int32_t , 0x8);
			PROPERTY(m_flBurnDamageInflicted,float32 , 0xc);
			PROPERTY(m_flBlastDamageInflicted,float32 , 0x10);
			PROPERTY(m_iDinks,int32_t , 0x14);
			S2_PAD(0x18);
		};
		//static_assert(sizeof(CS2::server::CSAdditionalPerRoundStats_t) == 0x18, "CSAdditionalPerRoundStats_t size should be 0x18");
	}
}
