// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "SceneRequestHandle_t.hpp"
#include "ESceneRequestState_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CSceneRequest  {
		public:
			PROPERTY(m_szPayloadTypeName,GlobalTypes::CUtlSymbolLarge*, 0x0);
			NESTED_PROPERTY(m_uHandle,IDENTITY(server::SceneRequestHandle_t), 0x8);
			PROPERTY(m_state,IDENTITY(server::ESceneRequestState_t), 0xc);
			S2_PAD(0x20);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CSceneRequest) == 0x20, "CSceneRequest size should be 0x20");

#endif
	}
}
