// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CTriggerOnce.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CScriptTriggerOnce : public CS2::server::CTriggerOnce {
		public:
			PROPERTY(m_vExtent,GlobalTypes::Vector, 0x8a8);
			S2_PAD(0x10);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CScriptTriggerOnce) == 0x8B8, "CScriptTriggerOnce size should be 0x8B8");

#endif
	}
}
