// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CGameSceneNode.hpp>
#include <SDK/server/CModelState.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CSkeletonInstance : public CS2::server::CGameSceneNode {
		public:
			PROPERTY(m_modelState,server::CModelState , 0x170);
			PROPERTY(m_bIsAnimationEnabled,bool , 0x3f0);
			PROPERTY(m_bUseParentRenderBounds,bool , 0x3f1);
			PROPERTY(m_bDisableSolidCollisionsForHierarchy,bool , 0x3f2);
			PROPERTY(m_materialGroup,GlobalTypes::CUtlStringToken* , 0x3f4);
			PROPERTY(m_nHitboxSet,uint8_t , 0x3f8);
			S2_PAD(0x330);
		};
		//static_assert(sizeof(CS2::server::CSkeletonInstance) == 0x490, "CSkeletonInstance size should be 0x490");
	}
}
