// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseEntity.hpp>
#include <SDK/server/sky3dparams_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CSkyCamera : public CS2::server::CBaseEntity {
		public:
			PROPERTY(m_skyboxData,server::sky3dparams_t , 0x4f0);
			PROPERTY(m_skyboxSlotToken,GlobalTypes::CUtlStringToken* , 0x580);
			PROPERTY(m_bUseAngles,bool , 0x584);
			PROPERTY(m_pNext,server::CSkyCamera* , 0x588);
			S2_PAD(0xA0);
		};
		//static_assert(sizeof(CS2::server::CSkyCamera) == 0x590, "CSkyCamera size should be 0x590");
	}
}
