// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CSoundEventEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CSoundEventAABBEntity : public CS2::server::CSoundEventEntity {
		public:
			PROPERTY(m_vMins,GlobalTypes::Vector , 0x5b8);
			PROPERTY(m_vMaxs,GlobalTypes::Vector , 0x5c4);
			S2_PAD(0x18);
		};
		//static_assert(sizeof(CS2::server::CSoundEventAABBEntity) == 0x5D0, "CSoundEventAABBEntity size should be 0x5D0");
	}
}
