// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CSoundEventEntity : public CS2::server::CBaseEntity {
		public:
			PROPERTY(m_bStartOnSpawn,bool , 0x4f0);
			PROPERTY(m_bToLocalPlayer,bool , 0x4f1);
			PROPERTY(m_bStopOnNew,bool , 0x4f2);
			PROPERTY(m_bSaveRestore,bool , 0x4f3);
			PROPERTY(m_bSavedIsPlaying,bool , 0x4f4);
			PROPERTY(m_flSavedElapsedTime,float32 , 0x4f8);
			PROPERTY(m_iszSourceEntityName,GlobalTypes::CUtlSymbolLarge* , 0x500);
			PROPERTY(m_iszAttachmentName,GlobalTypes::CUtlSymbolLarge* , 0x508);
			PROPERTY(m_onGUIDChanged,GlobalTypes::CEntityOutputTemplate< uint64 >, 0x510);
			PROPERTY(m_onSoundFinished,entity2::CEntityIOOutput , 0x538);
			PROPERTY(m_flClientCullRadius,float32 , 0x560);
			PROPERTY(m_iszSoundName,GlobalTypes::CUtlSymbolLarge* , 0x590);
			PROPERTY(m_hSource,GlobalTypes::CEntityHandle , 0x5ac);
			PROPERTY(m_nEntityIndexSelection,int32_t , 0x5b0);
			S2_PAD(0xC8);
		};
		//static_assert(sizeof(CS2::server::CSoundEventEntity) == 0x5B8, "CSoundEventEntity size should be 0x5B8");
	}
}
