// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CSoundEventParameter : public CS2::server::CBaseEntity {
		public:
			PROPERTY(m_iszParamName,GlobalTypes::CUtlSymbolLarge* , 0x508);
			PROPERTY(m_flFloatValue,float32 , 0x510);
			S2_PAD(0x28);
		};
		//static_assert(sizeof(CS2::server::CSoundEventParameter) == 0x518, "CSoundEventParameter size should be 0x518");
	}
}
