// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CSoundOpvarSetPointEntity.hpp>



namespace CS2 {
	namespace server {
		class SoundOpvarTraceResult_t;
		class AutoRoomDoorwayPairs_t;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CSoundOpvarSetAutoRoomEntity : public CS2::server::CSoundOpvarSetPointEntity {
		public:
			PROPERTY(m_traceResults,GlobalTypes::CUtlVector<server::SoundOpvarTraceResult_t>, 0x6a8);
			PROPERTY(m_doorwayPairs,GlobalTypes::CUtlVector<server::AutoRoomDoorwayPairs_t>, 0x6c0);
			PROPERTY(m_flSize,float32 , 0x6d8);
			PROPERTY(m_flHeightTolerance,float32 , 0x6dc);
			PROPERTY(m_flSizeSqr,float32 , 0x6e0);
			S2_PAD(0x40);
		};
		//static_assert(sizeof(CS2::server::CSoundOpvarSetAutoRoomEntity) == 0x6E8, "CSoundOpvarSetAutoRoomEntity size should be 0x6E8");
	}
}
