// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CSoundOpvarSetPointEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CSoundOpvarSetPathCornerEntity : public CS2::server::CSoundOpvarSetPointEntity {
		public:
			PROPERTY(m_flDistMinSqr,float32 , 0x6c0);
			PROPERTY(m_flDistMaxSqr,float32 , 0x6c4);
			PROPERTY(m_iszPathCornerEntityName,GlobalTypes::CUtlSymbolLarge* , 0x6c8);
			S2_PAD(0x28);
		};
		//static_assert(sizeof(CS2::server::CSoundOpvarSetPathCornerEntity) == 0x6D0, "CSoundOpvarSetPathCornerEntity size should be 0x6D0");
	}
}
