// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>
#include <SDK/modellib/AttachmentHandle_t.hpp>
#include <SDK/entity2/GameTime_t.hpp>



namespace CS2 {
	namespace server {
		class CBaseEntity;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CSprite : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_hSpriteMaterial,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>, 0x7d8);
			PROPERTY(m_hAttachedToEntity,GlobalTypes::CHandle<server::CBaseEntity>, 0x7e0);
			PROPERTY(m_nAttachment,modellib::AttachmentHandle_t , 0x7e4);
			PROPERTY(m_flSpriteFramerate,float32 , 0x7e8);
			PROPERTY(m_flFrame,float32 , 0x7ec);
			PROPERTY(m_flDieTime,entity2::GameTime_t , 0x7f0);
			PROPERTY(m_nBrightness,uint32_t , 0x800);
			PROPERTY(m_flBrightnessDuration,float32 , 0x804);
			PROPERTY(m_flSpriteScale,float32 , 0x808);
			PROPERTY(m_flScaleDuration,float32 , 0x80c);
			PROPERTY(m_bWorldSpaceScale,bool , 0x810);
			PROPERTY(m_flGlowProxySize,float32 , 0x814);
			PROPERTY(m_flHDRColorScale,float32 , 0x818);
			PROPERTY(m_flLastTime,entity2::GameTime_t , 0x81c);
			PROPERTY(m_flMaxFrame,float32 , 0x820);
			PROPERTY(m_flStartScale,float32 , 0x824);
			PROPERTY(m_flDestScale,float32 , 0x828);
			PROPERTY(m_flScaleTimeStart,entity2::GameTime_t , 0x82c);
			PROPERTY(m_nStartBrightness,int32_t , 0x830);
			PROPERTY(m_nDestBrightness,int32_t , 0x834);
			PROPERTY(m_flBrightnessTimeStart,entity2::GameTime_t , 0x838);
			PROPERTY(m_nSpriteWidth,int32_t , 0x83c);
			PROPERTY(m_nSpriteHeight,int32_t , 0x840);
			S2_PAD(0x70);
		};
		//static_assert(sizeof(CS2::server::CSprite) == 0x848, "CSprite size should be 0x848");
	}
}
