// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLogicalEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTestPulseIO : public CS2::server::CLogicalEntity {
		public:
			PROPERTY(m_OnVariantVoid,entity2::CEntityIOOutput , 0x4f0);
			PROPERTY(m_OnVariantBool,entity2::CEntityIOOutput , 0x518);
			PROPERTY(m_OnVariantInt,entity2::CEntityIOOutput , 0x540);
			PROPERTY(m_OnVariantFloat,entity2::CEntityIOOutput , 0x568);
			PROPERTY(m_OnVariantString,entity2::CEntityIOOutput , 0x590);
			PROPERTY(m_OnVariantColor,entity2::CEntityIOOutput , 0x5b8);
			PROPERTY(m_OnVariantVector,entity2::CEntityIOOutput , 0x5e0);
			PROPERTY(m_bAllowEmptyInputs,bool , 0x608);
			S2_PAD(0x120);
		};
		//static_assert(sizeof(CS2::server::CTestPulseIO) == 0x610, "CTestPulseIO size should be 0x610");
	}
}
