// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseEntity.hpp>
#include <SDK/server/CBeam.hpp>
#include <SDK/entity2/GameTime_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTestEffect : public CS2::server::CBaseEntity {
		public:
			PROPERTY(m_iLoop,int32_t , 0x4f0);
			PROPERTY(m_iBeam,int32_t , 0x4f4);
			PROPERTY_ARRAY(m_pBeam,server::CBeam , 24 , 0x4f8);
			PROPERTY_ARRAY(m_flBeamTime,entity2::GameTime_t , 24 , 0x5b8);
			PROPERTY(m_flStartTime,entity2::GameTime_t , 0x618);
			S2_PAD(0x130);
		};
		//static_assert(sizeof(CS2::server::CTestEffect) == 0x620, "CTestEffect size should be 0x620");
	}
}
