// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTextureBasedAnimatable : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_bLoop,bool , 0x7d8);
			PROPERTY(m_flFPS,float32 , 0x7dc);
			PROPERTY(m_hPositionKeys,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCTextureBase>, 0x7e0);
			PROPERTY(m_hRotationKeys,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCTextureBase>, 0x7e8);
			PROPERTY(m_vAnimationBoundsMin,GlobalTypes::Vector , 0x7f0);
			PROPERTY(m_vAnimationBoundsMax,GlobalTypes::Vector , 0x7fc);
			PROPERTY(m_flStartTime,float32 , 0x808);
			PROPERTY(m_flStartFrame,float32 , 0x80c);
			S2_PAD(0x38);
		};
		//static_assert(sizeof(CS2::server::CTextureBasedAnimatable) == 0x810, "CTextureBasedAnimatable size should be 0x810");
	}
}
