// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseTrigger.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerGameEvent : public CS2::server::CBaseTrigger {
		public:
			PROPERTY(m_strStartTouchEventName,GlobalTypes::CUtlString* , 0x9a8);
			PROPERTY(m_strEndTouchEventName,GlobalTypes::CUtlString* , 0x9b0);
			PROPERTY(m_strTriggerID,GlobalTypes::CUtlString* , 0x9b8);
			S2_PAD(0x18);
		};
		//static_assert(sizeof(CS2::server::CTriggerGameEvent) == 0x9C0, "CTriggerGameEvent size should be 0x9C0");
	}
}
