// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseModelEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerBrush : public CS2::server::CBaseModelEntity {
		public:
			PROPERTY(m_OnStartTouch,entity2::CEntityIOOutput , 0x7d8);
			PROPERTY(m_OnEndTouch,entity2::CEntityIOOutput , 0x800);
			PROPERTY(m_OnUse,entity2::CEntityIOOutput , 0x828);
			PROPERTY(m_iInputFilter,int32_t , 0x850);
			PROPERTY(m_iDontMessageParent,int32_t , 0x854);
			S2_PAD(0x80);
		};
		//static_assert(sizeof(CS2::server::CTriggerBrush) == 0x858, "CTriggerBrush size should be 0x858");
	}
}
