// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseTrigger.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerSndSosOpvar : public CS2::server::CBaseTrigger {
		public:
			PROPERTY(m_hTouchingPlayers,server::CUtlVector<GlobalTypes::CHandle<server::CBaseEntity>>, 0x9a8);
			PROPERTY(m_flPosition,GlobalTypes::Vector , 0x9c0);
			PROPERTY(m_flCenterSize,float32 , 0x9cc);
			PROPERTY(m_flMinVal,float32 , 0x9d0);
			PROPERTY(m_flMaxVal,float32 , 0x9d4);
			PROPERTY(m_opvarName,GlobalTypes::CUtlSymbolLarge* , 0x9d8);
			PROPERTY(m_stackName,GlobalTypes::CUtlSymbolLarge* , 0x9e0);
			PROPERTY(m_operatorName,GlobalTypes::CUtlSymbolLarge* , 0x9e8);
			PROPERTY(m_bVolIs2D,bool , 0x9f0);
			PROPERTY_ARRAY(m_opvarNameChar,char , 256 , 0x9f1);
			PROPERTY_ARRAY(m_stackNameChar,char , 256 , 0xaf1);
			PROPERTY_ARRAY(m_operatorNameChar,char , 256 , 0xbf1);
			PROPERTY(m_VecNormPos,GlobalTypes::Vector , 0xcf4);
			PROPERTY(m_flNormCenterSize,float32 , 0xd00);
			S2_PAD(0x360);
		};
		//static_assert(sizeof(CS2::server::CTriggerSndSosOpvar) == 0xD08, "CTriggerSndSosOpvar size should be 0xD08");
	}
}
