// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseTrigger.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerTeleport : public CS2::server::CBaseTrigger {
		public:
			PROPERTY(m_iLandmark,GlobalTypes::CUtlSymbolLarge* , 0x9a8);
			PROPERTY(m_bUseLandmarkAngles,bool , 0x9b0);
			PROPERTY(m_bMirrorPlayer,bool , 0x9b1);
			PROPERTY(m_bCheckDestIfClearForPlayer,bool , 0x9b2);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::server::CTriggerTeleport) == 0x9B8, "CTriggerTeleport size should be 0x9B8");
	}
}
