// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CBaseTrigger.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerGameEvent : public CS2::server::CBaseTrigger {
		public:
			PROPERTY(m_strStartTouchEventName,GlobalTypes::CUtlString*, 0x890);
			PROPERTY(m_strEndTouchEventName,GlobalTypes::CUtlString*, 0x898);
			PROPERTY(m_strTriggerID,GlobalTypes::CUtlString*, 0x8a0);
			S2_PAD(0x18);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CTriggerGameEvent) == 0x8A8, "CTriggerGameEvent size should be 0x8A8");

#endif
	}
}
