// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CBaseTrigger.hpp"
#include "../entity2/CEntityIOOutput.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerRemove : public CS2::server::CBaseTrigger {
		public:
			NESTED_PROPERTY(m_OnRemove,IDENTITY(entity2::CEntityIOOutput), 0x890);
			S2_PAD(0x18);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::server::CTriggerRemove) == 0x8A8, "CTriggerRemove size should be 0x8A8");

#endif
	}
}
