// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CTriggerMultiple.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerImpact : public CS2::server::CTriggerMultiple {
		public:
			PROPERTY(m_flMagnitude,float32 , 0x9d0);
			PROPERTY(m_flNoise,float32 , 0x9d4);
			PROPERTY(m_flViewkick,float32 , 0x9d8);
			PROPERTY(m_pOutputForce,GlobalTypes::CEntityOutputTemplate<GlobalTypes::Vector>, 0x9e0);
			S2_PAD(0x38);
		};
		//static_assert(sizeof(CS2::server::CTriggerImpact) == 0xA08, "CTriggerImpact size should be 0xA08");
	}
}
