// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseTrigger.hpp>
#include <SDK/entity2/GameTime_t.hpp>
#include <SDK/client/DamageTypes_t.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerHurt : public CS2::server::CBaseTrigger {
		public:
			PROPERTY(m_flOriginalDamage,float32 , 0x9a8);
			PROPERTY(m_flDamage,float32 , 0x9ac);
			PROPERTY(m_flDamageCap,float32 , 0x9b0);
			PROPERTY(m_flLastDmgTime,entity2::GameTime_t , 0x9b4);
			PROPERTY(m_flForgivenessDelay,float32 , 0x9b8);
			PROPERTY(m_bitsDamageInflict,client::DamageTypes_t , 0x9bc);
			PROPERTY(m_damageModel,int32_t , 0x9c0);
			PROPERTY(m_bNoDmgForce,bool , 0x9c4);
			PROPERTY(m_vDamageForce,GlobalTypes::Vector , 0x9c8);
			PROPERTY(m_thinkAlways,bool , 0x9d4);
			PROPERTY(m_hurtThinkPeriod,float32 , 0x9d8);
			PROPERTY(m_OnHurt,entity2::CEntityIOOutput , 0x9e0);
			PROPERTY(m_OnHurtPlayer,entity2::CEntityIOOutput , 0xa08);
			PROPERTY(m_hurtEntities,server::CUtlVector<GlobalTypes::CHandle<server::CBaseEntity>>, 0xa30);
			S2_PAD(0xA0);
		};
		//static_assert(sizeof(CS2::server::CTriggerHurt) == 0xA48, "CTriggerHurt size should be 0xA48");
	}
}
