// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseTrigger.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerPhysics : public CS2::server::CBaseTrigger {
		public:
			PROPERTY(m_gravityScale,float32 , 0x9b8);
			PROPERTY(m_linearLimit,float32 , 0x9bc);
			PROPERTY(m_linearDamping,float32 , 0x9c0);
			PROPERTY(m_angularLimit,float32 , 0x9c4);
			PROPERTY(m_angularDamping,float32 , 0x9c8);
			PROPERTY(m_linearForce,float32 , 0x9cc);
			PROPERTY(m_flFrequency,float32 , 0x9d0);
			PROPERTY(m_flDampingRatio,float32 , 0x9d4);
			PROPERTY(m_vecLinearForcePointAt,GlobalTypes::Vector , 0x9d8);
			PROPERTY(m_bCollapseToForcePoint,bool , 0x9e4);
			PROPERTY(m_vecLinearForcePointAtWorld,GlobalTypes::Vector , 0x9e8);
			PROPERTY(m_vecLinearForceDirection,GlobalTypes::Vector , 0x9f4);
			PROPERTY(m_bConvertToDebrisWhenPossible,bool , 0xa00);
			S2_PAD(0x60);
		};
		//static_assert(sizeof(CS2::server::CTriggerPhysics) == 0xA08, "CTriggerPhysics size should be 0xA08");
	}
}
