// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseTrigger.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerActiveWeaponDetect : public CS2::server::CBaseTrigger {
		public:
			PROPERTY(m_OnTouchedActiveWeapon,entity2::CEntityIOOutput , 0x9a8);
			PROPERTY(m_iszWeaponClassName,GlobalTypes::CUtlSymbolLarge* , 0x9d0);
			S2_PAD(0x30);
		};
		//static_assert(sizeof(CS2::server::CTriggerActiveWeaponDetect) == 0x9D8, "CTriggerActiveWeaponDetect size should be 0x9D8");
	}
}
