// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseTrigger.hpp>



namespace CS2 {
	namespace server {
		class CEnvSoundscapeTriggerable;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerSoundscape : public CS2::server::CBaseTrigger {
		public:
			PROPERTY(m_hSoundscape,GlobalTypes::CHandle<server::CEnvSoundscapeTriggerable>, 0x9a8);
			PROPERTY(m_SoundscapeName,GlobalTypes::CUtlSymbolLarge* , 0x9b0);
			PROPERTY(m_spectators,server::CUtlVector<GlobalTypes::CHandle<server::CBasePlayerPawn>>, 0x9b8);
			S2_PAD(0x28);
		};
		//static_assert(sizeof(CS2::server::CTriggerSoundscape) == 0x9D0, "CTriggerSoundscape size should be 0x9D0");
	}
}
