// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CCSWeaponBase.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CWeaponBaseItem : public CS2::server::CCSWeaponBase {
		public:
			PROPERTY(m_bSequenceInProgress,bool , 0x11d0);
			PROPERTY(m_bRedraw,bool , 0x11d1);
			S2_PAD(0x10);
		};
		//static_assert(sizeof(CS2::server::CWeaponBaseItem) == 0x11E0, "CWeaponBaseItem size should be 0x11E0");
	}
}
