// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/SimpleConstraintsSoundProfileKeypoints_t.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class SimpleConstraintSoundProfile  {
		public:
			PROPERTY(eKeypoints,server::SimpleConstraintsSoundProfileKeypoints_t , 0x8);
			PROPERTY_ARRAY(m_keyPoints,float32 , 2 , 0xc);
			PROPERTY_ARRAY(m_reversalSoundThresholds,float32 , 3 , 0x14);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::server::SimpleConstraintSoundProfile) == 0x20, "SimpleConstraintSoundProfile size should be 0x20");
	}
}
