#pragma once
#include <CS2/Interfaces/Manager.h>
#include <CS2/Interfaces/CGameResourceService.h>
#include <CS2/Interfaces/CGameEntitySystem.h>
#include <CS2/Interfaces/CGameTraceManager.h>
#include <CS2/Interfaces/CCSGOInput.h>
#include <CS2/Interfaces/CMaterialSystem2.h>
#include <CS2/Interfaces/CPanoramaUIEngine.h>
#include <CS2/Interfaces/CUIEngineSource2.h>
#include <CS2/Interfaces/CSchemaSystem.h>
#include <CS2/Interfaces/CLegacyGameUI.h>
#include <CS2/Interfaces/CSource2Client.h>
#include <CS2/Interfaces/CSceneViewDebugOverlays.h>
#include <CS2/Interfaces/CCSGO_Hud.h>