// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/smartprops/CSmartPropOperation.hpp>
#include <SDK/smartprops/CSmartPropAttributeChoiceSelectionMode.hpp>
#include <SDK/smartprops/CSmartPropAttributeApplyColorMode.hpp>



namespace CS2 {
	namespace smartprops {
		class ColorChoice_t;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace smartprops {
		class CSmartPropOperation_SetTintColor : public CS2::smartprops::CSmartPropOperation {
		public:
			PROPERTY(m_SelectionMode,smartprops::CSmartPropAttributeChoiceSelectionMode , 0x50);
			PROPERTY(m_ColorSelection,GlobalTypes::CSmartPropAttributeInt , 0x90);
			PROPERTY(m_Mode,smartprops::CSmartPropAttributeApplyColorMode , 0xd0);
			PROPERTY(m_ColorChoices,GlobalTypes::CUtlVector<smartprops::ColorChoice_t>, 0x110);
			S2_PAD(0xD8);
		};
		//static_assert(sizeof(CS2::smartprops::CSmartPropOperation_SetTintColor) == 0x128, "CSmartPropOperation_SetTintColor size should be 0x128");
	}
}
