// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CSmartPropVariable.hpp"
#include "../resourcesystem/InfoForResourceTypeCModel.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace smartprops {
		class CSmartPropVariable_Model : public CS2::smartprops::CSmartPropVariable {
		public:
			PROPERTY(m_DefaultValue,IDENTITY(GlobalTypes::CResourceNameTyped<GlobalTypes::CWeakHandle<resourcesystem::InfoForResourceTypeCModel>>), 0x38);
			S2_PAD(0xE0);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::smartprops::CSmartPropVariable_Model) == 0x118, "CSmartPropVariable_Model size should be 0x118");

#endif
	}
}
