// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CSmartPropOperation.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace smartprops {
		class CSmartPropOperation_SaveColor : public CS2::smartprops::CSmartPropOperation {
		public:
			PROPERTY(m_VariableName,GlobalTypes::CUtlString*, 0x50);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::smartprops::CSmartPropOperation_SaveColor) == 0x58, "CSmartPropOperation_SaveColor size should be 0x58");

#endif
	}
}
