// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animgraphlib/CAnimUpdateNodeRef.hpp>
#include <SDK/animationsystem/HSequence.hpp>



namespace CS2 {
	namespace animgraphlib {
		class TagSpan_t;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class BlendItem_t  {
		public:
			PROPERTY(m_tags,GlobalTypes::CUtlVector<animgraphlib::TagSpan_t>, 0x0);
			PROPERTY(m_pChild,animgraphlib::CAnimUpdateNodeRef , 0x18);
			PROPERTY(m_hSequence,animationsystem::HSequence , 0x28);
			PROPERTY(m_vPos,GlobalTypes::Vector2D , 0x2c);
			PROPERTY(m_flDuration,float32 , 0x34);
			PROPERTY(m_bUseCustomDuration,bool , 0x38);
			S2_PAD(0x40);
		};
		//static_assert(sizeof(CS2::animgraphlib::BlendItem_t) == 0x40, "BlendItem_t size should be 0x40");
	}
}
