// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animgraphlib/CUnaryUpdateNode.hpp>
#include <SDK/animgraphlib/HitReactFixedSettings_t.hpp>
#include <SDK/animgraphlib/CAnimParamHandle.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CHitReactUpdateNode : public CS2::animgraphlib::CUnaryUpdateNode {
		public:
			PROPERTY(m_opFixedSettings,animgraphlib::HitReactFixedSettings_t , 0x70);
			PROPERTY(m_triggerParam,animgraphlib::CAnimParamHandle , 0xbc);
			PROPERTY(m_hitBoneParam,animgraphlib::CAnimParamHandle , 0xbe);
			PROPERTY(m_hitOffsetParam,animgraphlib::CAnimParamHandle , 0xc0);
			PROPERTY(m_hitDirectionParam,animgraphlib::CAnimParamHandle , 0xc2);
			PROPERTY(m_hitStrengthParam,animgraphlib::CAnimParamHandle , 0xc4);
			PROPERTY(m_flMinDelayBetweenHits,float32 , 0xc8);
			PROPERTY(m_bResetChild,bool , 0xcc);
			S2_PAD(0x60);
		};
		//static_assert(sizeof(CS2::animgraphlib::CHitReactUpdateNode) == 0xD0, "CHitReactUpdateNode size should be 0xD0");
	}
}
