// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CUnaryUpdateNode.hpp"
#include "JiggleBoneSettingsList_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CJiggleBoneUpdateNode : public CS2::animgraphlib::CUnaryUpdateNode {
		public:
			NESTED_PROPERTY(m_opFixedData,IDENTITY(animgraphlib::JiggleBoneSettingsList_t), 0x70);
			S2_PAD(0x20);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animgraphlib::CJiggleBoneUpdateNode) == 0x90, "CJiggleBoneUpdateNode size should be 0x90");

#endif
	}
}
