// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/animgraphlib/CVectorQuantizer.hpp>
#include <SDK/animgraphlib/SampleCode.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CMotionSearchNode  {
		public:
			PROPERTY(m_children,GlobalTypes::CUtlVector<animgraphlib::CMotionSearchNode*>, 0x0);
			PROPERTY(m_quantizer,animgraphlib::CVectorQuantizer , 0x18);
			PROPERTY(m_sampleCodes,GlobalTypes::CUtlVector<GlobalTypes::CUtlVector<animgraphlib::SampleCode>>, 0x38);
			PROPERTY(m_sampleIndices,GlobalTypes::CUtlVector<GlobalTypes::CUtlVector<int32_t>>, 0x50);
			PROPERTY(m_selectableSamples,GlobalTypes::CUtlVector< int32 >, 0x68);
			S2_PAD(0x80);
		};
		//static_assert(sizeof(CS2::animgraphlib::CMotionSearchNode) == 0x80, "CMotionSearchNode size should be 0x80");
	}
}
