// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace animgraphlib {
		class TagSpan_t;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CSequenceTagSpans  {
		public:
			PROPERTY(m_sSequenceName,GlobalTypes::CGlobalSymbol , 0x0);
			PROPERTY(m_tags,GlobalTypes::CUtlVector<animgraphlib::TagSpan_t>, 0x8);
			S2_PAD(0x20);
		};
		//static_assert(sizeof(CS2::animgraphlib::CSequenceTagSpans) == 0x20, "CSequenceTagSpans size should be 0x20");
	}
}
