// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace animgraphlib {
		class CCachedPose;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CStaticPoseCache  {
		public:
			PROPERTY(m_poses,GlobalTypes::CUtlVector<animgraphlib::CCachedPose>, 0x10);
			PROPERTY(m_nBoneCount,int32_t , 0x28);
			PROPERTY(m_nMorphCount,int32_t , 0x2c);
			S2_PAD(0x30);
		};
		//static_assert(sizeof(CS2::animgraphlib::CStaticPoseCache) == 0x30, "CStaticPoseCache size should be 0x30");
	}
}
