// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem_voicecontainers/CAudioMorphData.hpp>



namespace CS2 {
	namespace soundsystem_voicecontainers {
		class CAudioPhonemeTag;
		class CAudioEmphasisSample;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_voicecontainers {
		class CAudioSentence  {
		public:
			PROPERTY(m_bShouldVoiceDuck,bool , 0x0);
			PROPERTY(m_RunTimePhonemes,GlobalTypes::CUtlVector<soundsystem_voicecontainers::CAudioPhonemeTag>, 0x8);
			PROPERTY(m_EmphasisSamples,GlobalTypes::CUtlVector<soundsystem_voicecontainers::CAudioEmphasisSample>, 0x20);
			PROPERTY(m_morphData,soundsystem_voicecontainers::CAudioMorphData , 0x38);
			S2_PAD(0xA0);
		};
		//static_assert(sizeof(CS2::soundsystem_voicecontainers::CAudioSentence) == 0xA0, "CAudioSentence size should be 0xA0");
	}
}
