// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace soundsystem_voicecontainers {
		class CHarmonic;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_voicecontainers {
		class CTone  {
		public:
			PROPERTY(m_harmonics,GlobalTypes::CUtlVector<soundsystem_voicecontainers::CVoiceContainerStaticAdditiveSynth::CHarmonic>, 0x0);
			PROPERTY(m_curve,GlobalTypes::CPiecewiseCurve , 0x18);
			PROPERTY(m_bSyncInstances,bool , 0x58);
			S2_PAD(0x60);
		};
		//static_assert(sizeof(CS2::soundsystem_voicecontainers::CTone) == 0x60, "CVoiceContainerStaticAdditiveSynth::CTone size should be 0x60");
	}
}
