// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem_voicecontainers/CVoiceContainerBase.hpp>
#include <SDK/soundsystem_voicecontainers/CSoundContainerReference.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_voicecontainers {
		class CVoiceContainerParameterBlender : public CS2::soundsystem_voicecontainers::CVoiceContainerBase {
		public:
			PROPERTY(m_firstSound,soundsystem_voicecontainers::CSoundContainerReference , 0xb8);
			PROPERTY(m_secondSound,soundsystem_voicecontainers::CSoundContainerReference , 0xd0);
			PROPERTY(m_bEnableOcclusionBlend,bool , 0xe8);
			PROPERTY(m_curve1,GlobalTypes::CPiecewiseCurve , 0xf0);
			PROPERTY(m_curve2,GlobalTypes::CPiecewiseCurve , 0x130);
			PROPERTY(m_bEnableDistanceBlend,bool , 0x170);
			PROPERTY(m_curve3,GlobalTypes::CPiecewiseCurve , 0x178);
			PROPERTY(m_curve4,GlobalTypes::CPiecewiseCurve , 0x1b8);
			S2_PAD(0x140);
		};
		//static_assert(sizeof(CS2::soundsystem_voicecontainers::CVoiceContainerParameterBlender) == 0x1F8, "CVoiceContainerParameterBlender size should be 0x1F8");
	}
}
