// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem_voicecontainers/CVoiceContainerBase.hpp>
#include <SDK/soundsystem_voicecontainers/CSoundContainerReference.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_voicecontainers {
		class CVoiceContainerBlender : public CS2::soundsystem_voicecontainers::CVoiceContainerBase {
		public:
			PROPERTY(m_firstSound,soundsystem_voicecontainers::CSoundContainerReference , 0xb8);
			PROPERTY(m_secondSound,soundsystem_voicecontainers::CSoundContainerReference , 0xd0);
			PROPERTY(m_flBlendFactor,float32 , 0xe8);
			S2_PAD(0x38);
		};
		//static_assert(sizeof(CS2::soundsystem_voicecontainers::CVoiceContainerBlender) == 0xF0, "CVoiceContainerBlender size should be 0xF0");
	}
}
