// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CVoiceContainerBase.hpp"
#include "CVoiceContainerSetElement.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_voicecontainers {
		class CVoiceContainerSet : public CS2::soundsystem_voicecontainers::CVoiceContainerBase {
		public:
			NESTED_PROPERTY(m_soundsToPlay,IDENTITY(GlobalTypes::CUtlVector<soundsystem_voicecontainers::CVoiceContainerSetElement>), 0xa8);
			S2_PAD(0x18);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::soundsystem_voicecontainers::CVoiceContainerSet) == 0xC0, "CVoiceContainerSet size should be 0xC0");

#endif
	}
}
