// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/soundsystem_voicecontainers/CVoiceContainerBase.hpp>
#include <SDK/soundsystem_voicecontainers/CSoundContainerReference.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace soundsystem_voicecontainers {
		class CVoiceContainerLoopTrigger : public CS2::soundsystem_voicecontainers::CVoiceContainerBase {
		public:
			PROPERTY(m_sound,soundsystem_voicecontainers::CSoundContainerReference , 0xb8);
			PROPERTY(m_flRetriggerTimeMin,float32 , 0xd0);
			PROPERTY(m_flRetriggerTimeMax,float32 , 0xd4);
			PROPERTY(m_flFadeTime,float32 , 0xd8);
			PROPERTY(m_bCrossFade,bool , 0xdc);
			S2_PAD(0x28);
		};
		//static_assert(sizeof(CS2::soundsystem_voicecontainers::CVoiceContainerLoopTrigger) == 0xE0, "CVoiceContainerLoopTrigger size should be 0xE0");
	}
}
