// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CNmEvent.hpp"
#include "NmFrameSnapEventMode_t.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmFrameSnapEvent : public CS2::animlib::CNmEvent {
		public:
			PROPERTY(m_frameSnapMode,IDENTITY(animlib::NmFrameSnapEventMode_t), 0x20);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animlib::CNmFrameSnapEvent) == 0x28, "CNmFrameSnapEvent size should be 0x28");

#endif
	}
}
