// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CNmBoolValueNode_CDefinition.hpp"
#include "NmFootPhaseCondition_t.hpp"
#include "CNmBitFlags.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmFootEventConditionNode_CDefinition : public CS2::animlib::CNmBoolValueNode_CDefinition {
		public:
			PROPERTY(m_nSourceStateNodeIdx,int16_t, 0x10);
			PROPERTY(m_phaseCondition,IDENTITY(animlib::NmFootPhaseCondition_t), 0x12);
			NESTED_PROPERTY(m_eventConditionRules,IDENTITY(animlib::CNmBitFlags), 0x14);
			S2_PAD(0x8);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animlib::CNmFootEventConditionNode_CDefinition) == 0x18, "CNmFootEventConditionNode::CDefinition size should be 0x18");

#endif
	}
}
