// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeCNmSkeleton;
	}
	namespace animlib {
		class ReferencedGraphSlot_t;
		class ExternalGraphSlot_t;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmGraphDefinition  {
		public:
			PROPERTY(m_variationID,GlobalTypes::CGlobalSymbol , 0x0);
			PROPERTY(m_skeleton,GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCNmSkeleton>, 0x8);
			PROPERTY(m_persistentNodeIndices,GlobalTypes::CUtlVector< int16 >, 0x10);
			PROPERTY(m_nRootNodeIdx,int16_t , 0x28);
			PROPERTY(m_controlParameterIDs,GlobalTypes::CUtlVector<GlobalTypes::CGlobalSymbol>, 0x30);
			PROPERTY(m_virtualParameterIDs,GlobalTypes::CUtlVector<GlobalTypes::CGlobalSymbol>, 0x48);
			PROPERTY(m_virtualParameterNodeIndices,GlobalTypes::CUtlVector< int16 >, 0x60);
			PROPERTY(m_referencedGraphSlots,GlobalTypes::CUtlVector<animlib::CNmGraphDefinition::ReferencedGraphSlot_t>, 0x78);
			PROPERTY(m_externalGraphSlots,GlobalTypes::CUtlVector<animlib::CNmGraphDefinition::ExternalGraphSlot_t>, 0x90);
			PROPERTY(m_nodePaths,GlobalTypes::CUtlVector<GlobalTypes::CUtlString>, 0x118);
			PROPERTY(m_resources,GlobalTypes::CUtlVector<GlobalTypes::CStrongHandleVoid>, 0x130);
			S2_PAD(0x180);
		};
		//static_assert(sizeof(CS2::animlib::CNmGraphDefinition) == 0x180, "CNmGraphDefinition size should be 0x180");
	}
}
