// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CNmIDValueNode_CDefinition.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmIDSelectorNode_CDefinition : public CS2::animlib::CNmIDValueNode_CDefinition {
		public:
			// PROPERTY(m_conditionNodeIndices,IDENTITY(GlobalTypes::CUtlVectorFixedGrowable< int16, 5 >), 0x10);
			// PROPERTY(m_values,IDENTITY(GlobalTypes::CUtlVectorFixedGrowable<GlobalTypes::CGlobalSymbol>), 0x38);
			PROPERTY(m_defaultValue,GlobalTypes::CGlobalSymbol, 0x78);
			S2_PAD(0x70);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animlib::CNmIDSelectorNode_CDefinition) == 0x80, "CNmIDSelectorNode::CDefinition size should be 0x80");

#endif
	}
}
