// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CNmPoseNode_CDefinition.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmParameterizedBlendNode_CDefinition : public CS2::animlib::CNmPoseNode_CDefinition {
		public:
			// PROPERTY(m_sourceNodeIndices,IDENTITY(GlobalTypes::CUtlVectorFixedGrowable< int16, 5 >), 0x10);
			PROPERTY(m_nInputParameterValueNodeIdx,int16_t, 0x38);
			PROPERTY(m_bAllowLooping,bool, 0x3a);
			S2_PAD(0x30);
		};
#ifdef USE_STATIC_ASSERTS
		//static_assert(sizeof(CS2::animlib::CNmParameterizedBlendNode_CDefinition) == 0x40, "CNmParameterizedBlendNode::CDefinition size should be 0x40");

#endif
	}
}
